(function(){
 'use strict';
 const $=id=>document.getElementById(id),PAGE=200,LIMIT=500000;
 let result=null,indices=[],page=0,changePosition=-1,request=0;
 const sources={left:[],right:[]},generation={left:0,right:0};
 const read=key=>{try{return JSON.parse(sessionStorage.getItem(key)||'null');}catch{return null;}};
 function status(message,error=false){$('compareStatus').textContent=message;$('compareStatus').classList.toggle('error',error);}
 function invalidate(){request++;result=null;$('compareResult').hidden=true;status('Inputs changed. Run comparison to refresh the result.');}
 function setText(side,text,label){$(side+'Text').value=text;$(side+'Label').value=String(label||side).slice(0,120);updateInfo(side);invalidate();}
 function updateInfo(side){const text=$(side+'Text').value;$(side+'Info').textContent=text.length+' characters · '+(text?text.replace(/\r\n?/g,'\n').split('\n').length:0)+' lines';}
 function extract(project){const data=project?.reporting||project;const names=new Map((data?.devices||[]).map(d=>[d.id,d.logicalHostname||d.hostname||d.observedHostname||d.id]));return (data?.configurations||[]).filter(c=>typeof c.text==='string'&&c.text.length).map(c=>({text:c.text,label:names.get(c.deviceId)||c.deviceId||'Device',vendor:data.vendor||'',project:project?.name||data?.name||''}));}
 function devices(side,project,label){const configs=extract(project);if(!configs.length)throw Error('This source has no saved device configurations. Generate a design report first, or upload / paste a configuration.');sources[side]=configs;const select=$(side+'Device');select.replaceChildren();configs.forEach((c,i)=>{const option=document.createElement('option');option.value=i;option.textContent=c.label+(c.vendor?' · '+c.vendor:'');select.append(option);});$(side+'DeviceLabel').hidden=false;select.onchange=()=>{const c=sources[side][Number(select.value)];setText(side,c.text,(label||c.project)+' · '+c.label);};select.onchange();}
 async function api(path){const r=await fetch(path);const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Unable to read saved projects.');return data;}
 async function library(side){
  const node=$(side+'Library');node.hidden=false;node.replaceChildren();const token=++generation[side];
  const help=document.createElement('p');help.textContent='Select a saved project, revision and device. Your active project will not be changed.';node.append(help);
  const search=document.createElement('input');search.type='search';search.placeholder='Search project name';search.maxLength=120;
  const refresh=document.createElement('button');refresh.type='button';refresh.textContent='Search';const list=document.createElement('select');list.setAttribute('aria-label','Saved project');
  const rev=document.createElement('select');rev.setAttribute('aria-label','Revision');const load=document.createElement('button');load.type='button';load.textContent='Load revision';load.disabled=true;
  const note=document.createElement('p');const prev=document.createElement('button'),next=document.createElement('button');prev.type=next.type='button';prev.textContent='Previous projects';next.textContent='Next projects';let offset=0,currentId='',revToken=0;
  for(const element of [search,refresh,list,rev,load,prev,next,note])node.append(element);
  let listingToken=0;
  async function revisions(){const id=list.value,t=++revToken;currentId=id;load.disabled=true;rev.replaceChildren();if(!id)return;try{const data=await api('/api/projects/'+encodeURIComponent(id)+'/revisions');if(t!==revToken||generation[side]!==token)return;for(const r of data.revisions){const o=document.createElement('option');o.value=r.revision;o.textContent='Revision '+r.revision+(r.revision===data.current_revision?' · current':'')+(r.note?' · '+r.note:'');rev.append(o);}load.disabled=!rev.options.length;note.textContent='Choose revision and load its saved device configurations.';}catch(e){note.textContent=e.message;}}
  async function listing(){const t=++listingToken;revToken++;load.disabled=true;list.replaceChildren();rev.replaceChildren();note.textContent='Loading projects…';try{const data=await api('/api/projects?q='+encodeURIComponent(search.value.trim())+'&offset='+offset);if(t!==listingToken||generation[side]!==token)return;for(const p of data.projects){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;list.append(o);}prev.disabled=offset===0;next.disabled=offset+data.limit>=data.total;note.textContent=data.projects.length?'':'No saved projects found.';await revisions();}catch(e){note.textContent=e.message;}}
  list.onchange=revisions;refresh.onclick=()=>{offset=0;listing();};search.onkeydown=e=>{if(e.key==='Enter'){offset=0;listing();}};prev.onclick=()=>{offset=Math.max(0,offset-50);listing();};next.onclick=()=>{offset+=50;listing();};
  load.onclick=async()=>{const id=currentId,version=rev.value;load.disabled=true;try{const data=await api('/api/projects/'+encodeURIComponent(id)+'/revisions/'+encodeURIComponent(version));if(currentId!==id||rev.value!==version||generation[side]!==token)return;devices(side,data.document,(data.document.name||'Project')+' · r'+version);note.textContent='Revision loaded. Choose a device above.';}catch(e){note.textContent=e.message;}finally{if(generation[side]===token)load.disabled=false;}};
  await listing();
 }
 for(const side of ['left','right']){
  $(side+'Text').addEventListener('input',()=>{generation[side]++;updateInfo(side);invalidate();});$(side+'Label').addEventListener('input',invalidate);
  $(side+'File').onchange=async()=>{const file=$(side+'File').files?.[0];if(!file)return;const token=++generation[side];try{if(file.size>2000000)throw Error('Each file must be at most 2 MB (500,000 decoded characters).');const bytes=new Uint8Array(await file.arrayBuffer());let text;if(bytes[0]===255&&bytes[1]===254)text=new TextDecoder('utf-16le',{fatal:true}).decode(bytes);else if(bytes[0]===254&&bytes[1]===255)text=new TextDecoder('utf-16be',{fatal:true}).decode(bytes);else text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(token!==generation[side])return;if(text.length>LIMIT||text.includes('\0'))throw Error('Upload a UTF-8 or UTF-16 text configuration up to 500,000 characters.');sources[side]=[];$(side+'DeviceLabel').hidden=true;$(side+'Library').hidden=true;setText(side,text,file.name);status('Loaded '+file.name+'. You can edit the text before comparing.');}catch(e){status(e.message,true);}finally{$(side+'File').value='';}};
 }
 document.querySelectorAll('[data-current]').forEach(button=>button.onclick=()=>{const side=button.dataset.current;generation[side]++;$(side+'Library').hidden=true;try{const current=read('networkConfigurator.compare.current');const fallback=read('networkConfigurator.report.current');devices(side,current?.configurations?.length?current:fallback,'Current design');status('Generated device configurations loaded. Select the device to compare.');}catch(e){status(e.message,true);}});
 document.querySelectorAll('[data-library]').forEach(button=>button.onclick=()=>library(button.dataset.library));
 for(const id of ['ignoreTrailing','ignoreIndentation','ignoreBlank','ignoreMetadata','excludePrefixes'])$(id).addEventListener('input',invalidate);
 function payload(){return {left:$('leftText').value,right:$('rightText').value,left_label:$('leftLabel').value||'Baseline',right_label:$('rightLabel').value||'Candidate',ignore_trailing_space:$('ignoreTrailing').checked,ignore_indentation:$('ignoreIndentation').checked,ignore_blank_lines:$('ignoreBlank').checked,ignore_metadata:$('ignoreMetadata').checked,exclude_prefixes:$('excludePrefixes').value.split('\n').map(x=>x.trim()).filter(Boolean)};}
 $('compareRun').onclick=async()=>{
  const p=payload(),token=++request;$('compareResult').hidden=true;result=null;if(!p.left&&!p.right){status('Add at least one configuration to compare.',true);return;}if(p.left.length>LIMIT||p.right.length>LIMIT){status('Each configuration supports up to 500,000 characters.',true);return;}
  $('compareRun').disabled=true;status('Comparing configurations…');
  try{const r=await fetch('/api/config-compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const data=await r.json();if(token!==request)return;if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Invalid input. Check the size and comparison options.');result={...data,comparedAt:new Date().toISOString()};changePosition=-1;page=0;$('compareResult').hidden=false;$('compareLeftTitle').textContent=p.left_label;$('compareRightTitle').textContent=p.right_label;$('compareCounts').replaceChildren();for(const [kind,count]of Object.entries(data.counts)){const el=document.createElement('span'),n=document.createElement('b');n.textContent=count;el.append(n,kind[0].toUpperCase()+kind.slice(1));$('compareCounts').append(el);}$('compareIgnored').textContent='Excluded lines: baseline '+data.ignored.left+' · candidate '+data.ignored.right+'. Original source line numbers are retained. Ignore options: '+(Object.entries(data.options).filter(([k,v])=>k.startsWith('ignore_')&&v).map(([k])=>k.replaceAll('_',' ')).join(', ')||'none')+'.';filter();status(data.identical?(data.ignored.left||data.ignored.right||p.ignore_trailing_space||p.ignore_indentation?'No differences under the selected comparison options.':'Configurations match after line-ending normalization.'):'Comparison complete. Review the highlighted changes.');}
  catch(e){if(token===request)status('Comparison failed: '+e.message,true);}finally{$('compareRun').disabled=false;}
 };
 function filter(){if(!result)return;const mode=$('compareView').value,visible=new Set();result.rows.forEach((r,i)=>{if(mode==='all'||r.kind!=='unchanged'){if(mode==='context'){for(let j=Math.max(0,i-3);j<=Math.min(result.rows.length-1,i+3);j++)visible.add(j);}else visible.add(i);}});indices=[...visible].sort((a,b)=>a-b);page=0;render();}
 function render(){if(!result)return;const body=$('compareRows');body.replaceChildren();const slice=indices.slice(page*PAGE,(page+1)*PAGE);for(const i of slice){const row=result.rows[i],tr=document.createElement('tr');tr.className=row.kind;tr.dataset.index=i;for(const side of ['left','right']){const number=document.createElement('td'),code=document.createElement('td'),pre=document.createElement('pre');number.className='number';number.textContent=row[side+'Number']??'';code.className='code'+(row[side]===null?' absent':'');pre.textContent=row[side]??'';code.append(pre);tr.append(number,code);}body.append(tr);}if(!slice.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.textContent='No differences in this view. Select All lines to review the content.';tr.append(td);body.append(tr);}const pages=Math.max(1,Math.ceil(indices.length/PAGE));$('comparePage').textContent='Page '+(page+1)+' / '+pages+' · '+indices.length+' displayed rows';$('comparePrevious').disabled=page===0;$('compareNext').disabled=page+1>=pages;const noChanges=result.identical;$('comparePrevChange').disabled=$('compareNextChange').disabled=noChanges;}
 $('compareView').onchange=filter;$('comparePrevious').onclick=()=>{if(page>0){page--;render();}};$('compareNext').onclick=()=>{if((page+1)*PAGE<indices.length){page++;render();}};
 function nextChange(direction){if(!result)return;const changes=[];result.rows.forEach((r,i)=>{if(r.kind!=='unchanged'&&(i===0||result.rows[i-1].kind==='unchanged'))changes.push(i);});if(!changes.length)return;changePosition=(changePosition+direction+changes.length)%changes.length;const target=changes[changePosition],position=indices.indexOf(target);if(position<0)return;page=Math.floor(position/PAGE);render();document.querySelector('tr[data-index="'+target+'"]').scrollIntoView({block:'center',behavior:'smooth'});}
 $('compareNextChange').onclick=()=>nextChange(1);$('comparePrevChange').onclick=()=>{if(changePosition===-1)changePosition=0;nextChange(-1);};
 function download(content,type,filename){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 $('compareDownload').onclick=()=>{if(result)download(result.diff||'# No differences under the selected options.\n','text/plain;charset=utf-8','configuration-comparison.diff');};$('compareDownloadJson').onclick=()=>{if(result)download(JSON.stringify(result,null,2),'application/json','configuration-comparison.json');};
 $('compareSwap').onclick=()=>{generation.left++;generation.right++;const text=$('leftText').value,label=$('leftLabel').value;$('leftText').value=$('rightText').value;$('leftLabel').value=$('rightLabel').value;$('rightText').value=text;$('rightLabel').value=label;for(const s of ['left','right']){$(s+'DeviceLabel').hidden=true;$(s+'Library').hidden=true;sources[s]=[];updateInfo(s);}invalidate();};
 $('compareClear').onclick=()=>{for(const s of ['left','right']){generation[s]++;$(s+'Text').value='';$(s+'Label').value=s==='left'?'Baseline':'Candidate';$(s+'DeviceLabel').hidden=true;$(s+'Library').hidden=true;sources[s]=[];updateInfo(s);}invalidate();status('Both sources cleared.');};
 window.NetworkConfigCompare={extract,payload};
})();
