/* Shared report and Design Notes localization. Engineer text and CLI remain unchanged. */
(function(root){
  const reportWords={
    tr:{draft:"Ağ tasarımı · Taslak rapor",enterName:"Proje adını girin",meta:"Raporlama ve Envanter",devices:"cihaz",links:"Planlanan fiziksel bağlantılar",overview:"1 · Proje özeti",architecture:"Mimari",platform:"Platform",technology:"Teknoloji",scope:"Proje kapsamı ve tasarım amacı mühendis tarafından girilmelidir.",topology:"2 · Planlanan topoloji",plannedDevices:"planlanan cihaz",generatedConfigs:"üretilen konfigürasyon",schedule:"Bağlantı çizelgesi",upperDevice:"Cihaz A",lowerDevice:"Cihaz B",port:"Port",connection:"Bağlantı / hız",noLinks:"Fiziksel bağlantı modellenmedi",special:"Özel bağlantılar ve kontrol yolları",type:"Tür",endpointA:"Uç A / port",endpointB:"Uç B / port",details:"Detaylar",logical:"mantıksal",logicalNote:"Mantıksal kontrol yolları uç arayüzlerini ve adresleri gösterir; doğrudan fiziksel kablo anlamına gelmez.",approach:"3 · Teknoloji yaklaşımı",intentOnly:"Bu bölüm tasarım amacını gösterir; operasyonel durum henüz doğrulanmamıştır.",decisions:"Teknoloji kararları ve ağa etkileri",decisionNote:"Mimari ve operasyonel davranış seçilen tasarımı yansıtır. Gerçek trafik iletimi eş cihaz konfigürasyonu ve cihaz durumuna bağlıdır.",assumptions:"Tasarım varsayımları ve uygulama notları",inventory:"4 · Cihaz envanteri",device:"Cihaz",role:"Rol",model:"Model",serial:"Seri numarası",source:"Kaynak",confirm:"5 · Doğrulanacak hususlar",appendix:"Ek · Planlanan cihaz konfigürasyonları",configNote:"Üretilen konfigürasyon tasarım girdilerini yansıtır ve cihaz üzerinde doğrulanmamıştır. Kullanımdan önce hedef model ve yazılım sürümüyle karşılaştırılmalıdır.",footer:"Planlanan proje topolojisinden üretilmiştir. Kimlik bilgileri rapora dahil edilmemiştir. Durum: Taslak.",tbd:"Belirlenecek"},
    en:{draft:"Network design · Draft report",enterName:"Enter project name",meta:"Maintenance and Reporting",devices:"devices",links:"Planned physical links",overview:"1 · Project overview",architecture:"Architecture",platform:"Platform",technology:"Technology",scope:"Project scope and design intent await engineer input.",topology:"2 · Planned topology",plannedDevices:"planned devices",generatedConfigs:"generated configurations",schedule:"Connection schedule",upperDevice:"Device A",lowerDevice:"Device B",port:"Port",connection:"Connection / speed",noLinks:"No physical links modeled",special:"Special connections and control paths",type:"Type",endpointA:"Endpoint A / port",endpointB:"Endpoint B / port",details:"Details",logical:"logical",logicalNote:"Logical control paths show endpoint interfaces and addresses; they do not imply a direct cable.",approach:"3 · Technology approach",intentOnly:"Design intent only; operational state has not been verified.",decisions:"Technology decisions and network impact",decisionNote:"Architecture and operational behavior reflect the selected design. Actual forwarding depends on peer configuration and device state.",assumptions:"Design assumptions and implementation notes",inventory:"4 · Device inventory",device:"Device",role:"Role",model:"Model",serial:"Serial",source:"Source",confirm:"5 · Items to confirm",appendix:"Appendix · Planned device configurations",configNote:"Generated configuration reflects design inputs and has not been validated on a device. Review it against the target model and software release before use.",footer:"Generated from the planned project topology. Credentials are excluded from the report. Status: Draft.",tbd:"TBD"}
  };
  const trDecisionLabels={"Management access and recovery":"Yönetim erişimi ve kurtarma","Management-plane visibility":"Yönetim düzlemi görünürlüğü","Time and audit consistency":"Zaman ve denetim tutarlılığı","External connectivity and route exchange":"Harici bağlantı ve rota değişimi","Outbound traffic preference":"Giden trafik tercihi","Inbound traffic influence":"Gelen trafik yönlendirme etkisi","Session resilience and route safeguards":"Oturum dayanıklılığı ve rota korumaları","OSPF adjacency and flooding domain":"OSPF komşuluğu ve yayılım alanı","Route selection":"Rota seçimi","Loop-free Layer 2 architecture":"Döngüsüz Katman 2 mimarisi","Spanning-tree root and failover":"Spanning-tree kök ve yedeklilik davranışı","Loop and edge protections":"Döngü ve uç port korumaları","Frame size and path compatibility":"Çerçeve boyutu ve yol uyumluluğu","Traffic classification":"Trafik sınıflandırması","Congestion and bandwidth policy":"Tıkanıklık ve bant genişliği politikası","EVPN fabric and control plane":"EVPN fabric ve kontrol düzlemi","Layer 2 extension":"Katman 2 genişletme","Tenant routing and IP prefix exchange":"Tenant yönlendirme ve IP prefix değişimi","Cisco NX-OS forwarding realization":"Cisco NX-OS trafik iletim modeli","Arista EOS forwarding realization":"Arista EOS trafik iletim modeli","Huawei CloudEngine forwarding realization":"Huawei CloudEngine trafik iletim modeli","Overlay resilience and neighbor handling":"Overlay dayanıklılığı ve komşuluk yönetimi","Site identity and overlay membership":"Saha kimliği ve overlay üyeliği","Transport diversity and preference":"Taşıma çeşitliliği ve yol tercihi","Control connections and failure detection":"Kontrol bağlantıları ve hata algılama","Active-active access architecture":"Aktif-aktif erişim mimarisi","Peer-link purpose and forwarding behavior":"Peer-link görevi ve trafik iletim davranışı","Independent liveness and failure containment":"Bağımsız canlılık kontrolü ve hata sınırlandırma","Role, consistency and gateway behavior":"Rol, tutarlılık ve gateway davranışı","Spanning-tree integration and loop protection":"Spanning-tree entegrasyonu ve döngü koruması","Service restoration after failure":"Arıza sonrası servis geri dönüşü","Dual-attached MLAG service":"Çift bağlı MLAG servisi","Inter-peer state and liveness":"Eşler arası durum ve canlılık","Service restoration and spanning tree":"Servis geri dönüşü ve spanning tree","Dual-attached M-LAG service":"Çift bağlı M-LAG servisi","Peer synchronization and dual-active detection":"Eş senkronizasyonu ve dual-active algılama","VLAN scope and loop prevention":"VLAN kapsamı ve döngü önleme","Service restoration after peer recovery":"Eş cihaz geri dönüşünden sonra servis açılması","Single logical core":"Tek mantıksal core","Chassis interconnect and dual-active protection":"Şasiler arası bağlantı ve dual-active koruması","Spanning-tree role and access scope":"Spanning-tree rolü ve erişim kapsamı"};
  const trImpact={
    "Management access and recovery":"Seçilen merkezi AAA ve yerel erişim seçenekleri yönetim sürekliliğini belirler. OOB erişimi, AAA erişimi ve yerel kurtarma hesabı aynı hata alanına bağlı olmamalı; veri düzlemi kaybı yönetim erişimini ortadan kaldırmamalıdır.",
    "Management-plane visibility":"Syslog ve güvenli SNMP seçenekleri olayların merkezi izlenmesini sağlar. Sunucu erişimi, kaynak arayüzü, kimlik doğrulama ve şifreleme ayarları NMS tarafıyla eşleşmelidir.",
    "Time and audit consistency":"NTP kaynakları log, AAA ve olay kayıtlarının ortak zaman çizgisinde ilişkilendirilmesini sağlar. Zaman kaynağı erişilebilirliği ve yönetim VRF yönlendirmesi devreye alma öncesinde doğrulanmalıdır.",
    "External connectivity and route exchange":"Seçilen CE–ISP modeli eBGP rota değişimini tanımlar. Gerçek yedeklilik için devrelerin, sağlayıcı yollarının ve CE cihazlarının bağımsız hata alanlarında bulunması; öğrenilen rotaların RIB ve FIB'e doğru kurulması gerekir.",
    "Outbound traffic preference":"Local Preference değerleri müşteri AS'i içindeki çıkış tercihini belirler; yüksek değer karşılaştırılabilir rotalarda önceliklidir. Prefix erişilebilirliği ve daha üst öncelikli BGP nitelikleri gerçek yolu değiştirebilir.",
    "Inbound traffic influence":"AS-path prepend, MED ve community dış ağların giriş tercihini etkileyebilir ancak nihai karar upstream politikasına aittir. Asimetrik trafik güvenlik duvarı, NAT ve uRPF davranışıyla birlikte test edilmelidir.",
    "Session resilience and route safeguards":"BFD arıza algılamasını hızlandırabilir; maximum-prefix ise beklenmeyen rota hacmini sınırlar. Eşik ve zamanlayıcıların iki uçta uyumlu olması ve meşru rota büyümesini engellememesi gerekir.",
    "OSPF adjacency and flooding domain":"Area, ağ tipi, kimlik doğrulama, MTU ve zamanlayıcıların iki uçta uyumlu olması gerekir. Full komşuluk yalnız kontrol düzlemini doğrular; LSDB, RIB/FIB ve veri iletimi ayrıca test edilmelidir.",
    "Route selection":"OSPF toplam yol maliyetini karşılaştırır ve düşük maliyetli yolu tercih eder. Seçilen cost ancak alternatif yol mevcut olduğunda trafik tercihi ve yedeklilik üzerinde etkili olur.",
    "Loop-free Layer 2 architecture":"STP yedek fiziksel yolları döngüsüz tutar; bu bağlantılar aktif-aktif kapasite değil, gerektiğinde devreye giren yedek yollardır. Arıza halinde topoloji değişimi ve MAC yeniden öğrenme süresi ölçülmelidir.",
    "Spanning-tree root and failover":"Düşük bridge priority tercih edilen root rolünü destekler. Gerçek root seçimi bridge ID ve instance/VLAN kapsamıyla birlikte doğrulanmalı; root veya uplink kaybındaki yakınsama süresi test edilmelidir.",
    "Loop and edge protections":"PortFast, BPDU Guard, Root Guard, Loop Guard ve UDLD yalnız doğru port rollerinde kullanılmalıdır. Yanlış yerleşim servis kesintisine veya döngü korumasının etkisiz kalmasına yol açabilir.",
    "Frame size and path compatibility":"MTU uçtan uca bir yol özelliğidir. Tüm switch, routed hop ve encapsulation yükleri aynı efektif çerçeve boyutunu desteklemeli; büyük uygulama paketleriyle PMTUD ve drop davranışı doğrulanmalıdır.",
    "Traffic classification":"Trust sınırı ve DSCP değerleri trafiğin hangi sınıfa alınacağını belirler. Yanlış işaretlenmiş trafiğin istemeden öncelik kazanmaması için sınıflandırma ve remark politikası gerçek paketlerle doğrulanmalıdır.",
    "Congestion and bandwidth policy":"Policing fazla trafiği düşürebilir veya yeniden işaretleyebilir; shaping trafiği tamponlayarak gecikme ekleyebilir; WRED seçilen eşiklerde olasılıksal drop uygular. Etkin kuyruk ve bant genişliği davranışı hedef arayüzde ölçülmelidir.",
    "EVPN fabric and control plane":"BGP EVPN endpoint ve tenant erişilebilirliğini dağıtır; routed underlay ise loopback/VTEP erişimi ve yeterli MTU sağlamalıdır. EVPN komşuluğunun kurulması VXLAN veri düzleminin çalıştığını tek başına kanıtlamaz.",
    "Layer 2 extension":"VLAN–VNI eşlemeleri Layer 2 broadcast domain'ini katılımcı VTEP'ler arasında genişletir. Type-2 öğrenimi ve BUM taşıma yöntemi doğrulanmalı; genişletilen VLAN'ın hata alanını da büyüttüğü dikkate alınmalıdır.",
    "Tenant routing and IP prefix exchange":"Her VRF kendi L3VNI ve route-target politikasıyla ayrıştırılır. Import/export eşleşmesi hangi uzak prefixlerin kabul edileceğini belirler; Type-5 rotaların geçerli yerel kaynak ve next-hop ile üretilmesi gerekir.",
    "Cisco NX-OS forwarding realization":"Nexus VTEP'lerde overlay; NVE, VLAN–VNI ve BGP L2VPN EVPN bileşenleriyle gerçekleştirilir. VXLAN üzerinden genişletilen ve yönlendirilen bir VLAN'ın SVI'ında Anycast Gateway bulunmalıdır; aksi halde segment üretim trafiğine hazır değildir. ARP suppression yalnız güncel Type-2 MAC/IP bağlarıyla güvenilir çalışır. Özellikle border node'larda benzersiz RD kullanımı, bilinçli RT import/export politikası ve PIP/virtual RMAC ilan davranışı devreye alma testlerinde doğrulanmalıdır.",
    "Arista EOS forwarding realization":"EOS üzerinde overlay; Vxlan1, VLAN/VRF–VNI eşlemeleri ve BGP EVPN adres ailesiyle gerçekleştirilir. Aktif-aktif host bağlantısında MLAG veya EVPN Ethernet Segment seçimi; ESI benzersizliği, DF seçimi, split-horizon ve ortak VTEP kimliği üzerinde doğrudan etkilidir. Anycast gateway MAC/IP değerleri tüm ilgili leaf'lerde tutarlı olmalı; Type-1, Type-2 ve Type-4 rotalar ile tekil leaf ve peer-link arızasındaki veri yolu birlikte doğrulanmalıdır.",
    "Huawei CloudEngine forwarding realization":"CloudEngine üzerinde overlay; bridge-domain, VBDIF, NVE ve VPN-instance–VNI bağlarıyla gerçekleştirilir. Dağıtık gateway kullanılan tenant'larda gateway MAC/IP ve route-target politikaları ilgili leaf'lerde tutarlı olmalıdır. M-LAG kullanılıyorsa DFS group, peer-link, dual-active detection ve V-STP davranışı aynı hata senaryosunda doğrulanmalı; eş kaybında MAC/ARP öğrenimi ile northbound yönlendirme kesintisiz kalmalıdır.",
    "Overlay resilience and neighbor handling":"ARP/ND suppression BUM yükünü azaltır ancak yalnız EVPN MAC/IP bağları doğru ve güncelse güvenlidir; eski kayıtlar blackhole oluşturabilir. Anycast gateway, multihoming ve hızlı hata algılama ayarları tekil leaf, uplink ve host-link arızalarında test edilmeli; kontrol düzlemi yakınsaması ile gerçek veri iletiminin geri dönüş süresi ayrı ayrı ölçülmelidir.",
    "Active-active access architecture":"vPC eşleri bağımsız kontrol düzlemlerini korurken downstream port-channel'ı tek mantıksal bağlantı olarak sunar. Her iki üye aktif kullanılabilir; peer, üye veya şasi arızasında trafik davranışı ayrı senaryolarla test edilmelidir.",
    "Peer-link purpose and forwarding behavior":"Peer-link durum senkronizasyonu, BPDU ve gerekli flooded/failure trafiğini taşır. Doğrudan, yedekli ve arıza anındaki yükü karşılayacak kapasitede tasarlanmalı; VLAN kapsamı iki eşte tutarlı olmalıdır.",
    "Independent liveness and failure containment":"Peer-keepalive peer-link'ten bağımsız bir Layer 3 hata alanında çalışmalıdır. Peer-link kaybında keepalive erişilebilir kaldığında secondary eşin dual-active oluşmasını engelleyen davranışı doğrulanmalıdır.",
    "Role, consistency and gateway behavior":"Role priority amaçlanan primary rolünü etkiler; operasyonel rol devreye alma sonrasında doğrulanmalıdır. Type-1 parametreleri iki eşte aynı olmalı; peer-gateway ve ARP/ND senkronizasyonunun arıza davranışı test edilmelidir.",
    "Spanning-tree integration and loop protection":"peer-switch ve eş STP ayarları vPC çiftinin ortak root görünümünü destekler. Bridge Assurance, Root Guard ve BPDU Guard yalnız uygun bağlantı rollerine uygulanmalıdır.",
    "Service restoration after failure":"Delay restore ve auto-recovery zamanlayıcıları kontrol düzlemi toparlanmadan servis portlarının erken açılmasını önler. Değerler ölçülen yakınsama süresine göre belirlenmeli ve iki eşte simetrik test edilmelidir.",
    "Dual-attached MLAG service":"MLAG iki EOS switch'i bağımsız kontrol düzlemleriyle çalıştırırken downstream port-channel'ı tek mantıksal bağlantı olarak sunar. Port-channel, VLAN, LACP ve MLAG ID değerleri iki eşte simetrik olmalı; tekil üye, peer-link ve eş cihaz arızalarında trafik kaybı ve MAC yeniden öğrenme davranışı ölçülmelidir.",
    "Inter-peer state and liveness":"Peer-link durum ve gerekli veri trafiğini taşırken peer-address heartbeat eşin canlılığını bağımsız olarak izlemelidir. Bu yolların aynı hata alanını paylaşması split-brain riskini artırır; reload-delay ve dual-primary algılama davranışı kontrollü arıza testleriyle doğrulanmalıdır.",
    "Service restoration and spanning tree":"MLAG eşlerinin STP modu, priority ve VLAN kapsamı tutarlı olmalıdır. Reload-delay, routing convergence ve MAC/ARP yeniden öğrenimi tamamlanmadan üye portların açılmasını önleyecek şekilde ölçülmeli; geri dönen eşin root ve forwarding rollerinde geçici döngü oluşturmadığı kanıtlanmalıdır.",
    "Dual-attached M-LAG service":"Huawei M-LAG, iki CloudEngine cihazını aktif-aktif bir erişim çifti olarak sunar. Eth-Trunk, M-LAG ID, VLAN ve LACP parametreleri eşleşmeli; tekil üye, peer-link ve şasi kaybında kalan yolun trafiği taşıdığı doğrulanmalıdır.",
    "Peer synchronization and dual-active detection":"DFS group ve peer-link eşler arasında durum senkronizasyonu sağlar; dual-active detection ise peer-link kaybında iki tarafın aynı anda aktif kalmasını engeller. DAD yolu peer-link'ten bağımsız tasarlanmalı ve ortak hata alanı, split-brain ile yanlış izolasyon senaryoları test edilmelidir.",
    "VLAN scope and loop prevention":"Peer-link ve M-LAG üye bağlantılarındaki VLAN kapsamı iki eşte simetrik olmalıdır. V-STP veya seçilen STP mekanizması access ve interconnect rollerine uygun uygulanmalı; izin verilmeyen ya da yalnız tek tarafta bulunan VLAN'ların trafik kaybı veya Layer 2 döngü üretmediği doğrulanmalıdır.",
    "Service restoration after peer recovery":"Eş cihaz geri döndüğünde routing, DFS ve MAC/ARP senkronizasyonu tamamlanmadan servis portlarının açılması geçici blackhole veya döngü oluşturabilir. Recovery delay değerleri ölçülen kontrol ve veri düzlemi toparlanma süresine göre belirlenmelidir.",
    "Single logical core":"StackWise Virtual iki IOS-XE şasiyi tek mantıksal switch olarak işletir; tek yönetim ve kontrol düzlemi görünümü erişim katmanını basitleştirir. Gerçek dayanıklılık için chassis, supervisor, güç ve uplink hata alanları ayrıştırılmalı; active/standby switchover sırasında routing ve MEC trafiği ölçülmelidir.",
    "Chassis interconnect and dual-active protection":"StackWise Virtual Link kontrol, senkronizasyon ve bazı arıza trafiklerini taşır; farklı line-card ve fiziksel güzergâhlara dağıtılmış yeterli kapasitede üyelerle kurulmalıdır. Dual-active detection bağımsız bir mekanizma üzerinden doğrulanmalı; tüm SVL üyelerinin kaybında iki şasinin aynı anda aktif kalmadığı test edilmelidir.",
    "Spanning-tree role and access scope":"StackWise Virtual çifti STP açısından tek bridge gibi görünür; root önceliği VLAN veya instance kapsamına göre bilinçli seçilmelidir. MEC ve orphan portların loop korumaları farklıdır; BPDU Guard, Root Guard ve Loop Guard yalnız doğru port rollerine uygulanmalıdır.",
    "Site identity and overlay membership":"Site ID ve system IP SD-WAN fabric kimliğini belirler. Kimliklerin benzersizliği, sertifika/organization eşleşmesi ve controller erişimi overlay üyeliğinden önce doğrulanmalıdır.",
    "Transport diversity and preference":"Birden fazla taşıma hattı ancak bağımsız underlay ve controller erişimi varsa gerçek yol çeşitliliği sağlar. Color ve weight değerleri uygulama SLA politikasının yerine geçmez.",
    "Control connections and failure detection":"Hello ve tolerance değerleri kontrol bağlantısı arızasının algılanma süresini etkiler. Aşırı agresif değerler kararsız hatlarda yanlış failover üretebilir; BFD veri düzlemi davranışı ayrıca ölçülmelidir."
  };
  const noteLabels={tr:{"Peer-link resiliency and capacity":"Peer-link dayanıklılığı ve kapasitesi","Failure-domain separation":"Hata alanlarının ayrıştırılması","Spanning-tree integration":"Spanning-tree entegrasyonu","Gateway forwarding continuity":"Gateway iletim sürekliliği","Multi-chassis consistency":"Çok şasili yapı tutarlılığı","Failure recovery behavior":"Arıza sonrası toparlanma davranışı","Layer 2 protection scope":"Katman 2 koruma kapsamı","Failure detection and convergence":"Arıza algılama ve yakınsama","Routing policy effect":"Yönlendirme politikasının etkisi","MTU and encapsulation validation":"MTU ve encapsulation doğrulaması","Administrative access resilience":"Yönetim erişimi dayanıklılığı","Control-plane protection":"Kontrol düzlemi koruması","Connectivity resilience":"Bağlantı dayanıklılığı","Internal route propagation":"İç rota dağıtımı","Asymmetric forwarding risk":"Asimetrik trafik riski","Route scale safeguard":"Rota ölçeği koruması","Management-plane isolation":"Yönetim düzlemi ayrıştırması","Secure administration":"Güvenli yönetim erişimi","Service hardening boundary":"Servis sıkılaştırma sınırı","ISP configuration scope":"ISP konfigürasyon kapsamı","Core configuration scope":"Core konfigürasyon kapsamı","Operational visibility":"Operasyonel görünürlük","Time and audit integrity":"Zaman ve denetim bütünlüğü","Production acceptance criteria":"Üretim kabul kriterleri","Design scope and boundary":"Tasarım kapsamı ve sınırları"},en:{}};
  const noteImpacts={
    tr:{
      "Peer-link resiliency and capacity":"Peer-link yalnız durum senkronizasyonunu değil, bazı arıza koşullarında flooded ve yedek veri trafiğini de taşır. Üye bağlantılar farklı fiziksel hata alanlarına dağıtılmalı, port-channel kapasitesi tek üye veya downstream yol kaybındaki en kötü trafik profiline göre boyutlandırılmalı ve LACP üye durumu yük altında doğrulanmalıdır.",
      "Failure-domain separation":"Canlılık veya dual-active algılama yolu peer-link ile aynı arayüzü, kablo güzergâhını, line-card'ı ya da ara ağı paylaşmamalıdır. Aksi halde tek bir fiziksel arıza hem eşler arası senkronizasyonu hem de uzak şasinin hayatta olduğuna ilişkin kararı ortadan kaldırarak split-brain riskini büyütür.",
      "Spanning-tree integration":"STP modu, VLAN/instance eşlemeleri, bridge priority ve peer davranışı iki cihazda tutarlı olmalıdır. Amaçlanan root rolü yalnız konfigürasyon değeriyle varsayılmamalı; her VLAN veya MST instance için operasyonel root, port rolü ve arıza sonrası yakınsama doğrulanmalıdır.",
      "Gateway forwarding continuity":"Peer-gateway ile ARP/ND senkronizasyonu, trafik peer-link üzerinden gereksiz dolaşmadan yerel şaside yönlendirilebilmesini ve eş arızasında komşuluk bilgisinin korunmasını hedefler. Ortak gateway kimliği, MAC/IP tutarlılığı ve tek eş kaybındaki northbound/downstream trafik yolu test edilmelidir.",
      "Multi-chassis consistency":"VLAN listesi, native VLAN, MTU, switchport modu, LACP parametreleri, port-channel kimliği ve çok şasili bundle kimliği iki eşte simetrik olmalıdır. Type-1 veya eşdeğer kritik uyumsuzluklar üye portları askıya alabilir; global ve arayüz bazlı consistency çıktıları servis açılışından önce temiz olmalıdır.",
      "Failure recovery behavior":"Delay-restore, reload-delay ve auto-recovery zamanlayıcıları cihaz ayağa kalktığında veri portlarının kontrol düzlemi hazır olmadan erken açılmasını önler. Bu süreler varsayılan olarak kabul edilmemeli; routing, MAC/ARP senkronizasyonu ve peer komşuluğunun ölçülen toparlanma süresine göre belirlenmelidir.",
      "Layer 2 protection scope":"Bridge Assurance, Root Guard, BPDU Guard, Loop Guard ve UDLD aynı probleme yönelik değildir. Her özellik yalnız uygun port rolünde kullanılmalı; örneğin BPDU Guard gerçek edge portlarla, Bridge Assurance network portlarla, Root Guard ise istenmeyen root ilanını engelleyecek downstream sınırlarla kısıtlanmalıdır.",
      "Failure detection and convergence":"BFD, hello/hold veya vendor canlılık zamanlayıcıları arızanın ne kadar hızlı algılanacağını belirler; ancak hızlı algılama tek başına hızlı ve kararlı yakınsama sağlamaz. İki uçtaki değerler uyumlu olmalı ve paket kaybı, gecikme ile CPU baskısı altında yanlış failover üretmediği ölçülmelidir.",
      "Routing policy effect":"Local Preference, AS-path prepend, MED, community ve filtreler farklı yönlerde ve farklı karar alanlarında etkili olur. Local Preference yerel AS içindeki çıkışı belirlerken prepend/MED/community upstream giriş seçimini yalnız etkileyebilir; prefix kapsamı, politika sırası, sayaçlar, RIB/FIB sonucu ve asimetrik dönüş yolu birlikte doğrulanmalıdır.",
      "MTU and encapsulation validation":"MTU tek cihaz ayarı değil uçtan uca yol özelliğidir. VXLAN, IPsec veya diğer encapsulation başlıkları hesaba katılarak underlay ve servis arayüzleri uyumlu boyutlandırılmalı; DF set edilmiş büyük paketler, PMTUD, fragmentasyon ve sessiz drop senaryoları gerçek paket boyutlarıyla test edilmelidir.",
      "Administrative access resilience":"Merkezi AAA tercih edilse bile bağımsız bir OOB yolu ve kontrollü yerel break-glass hesabı korunmalıdır. AAA sunucusu, DNS/NTP bağımlılıkları ve management VRF aynı arızadan etkilenmemeli; merkezi servis kaybında console/OOB erişimi ile yetkilendirme ve accounting davranışı doğrulanmalıdır.",
      "Control-plane protection":"CoPP/CPPr ve control-plane ACL politikaları routing protokolleri, yönetim trafiği ve gerekli altyapı servislerini korurken istenmeyen trafiği sınırlandırmalıdır. Politika hedef model ve yazılım sürümünün sınıflandırma davranışına göre tasarlanmalı; normal kontrol trafiğini düşürmediği ve saldırı/yoğunluk altında CPU'yu koruduğu sayaçlar ve yük testleriyle doğrulanmalıdır.",
      "Connectivity resilience":"Seçilen CE–ISP modeli birden fazla eBGP komşuluğu oluşturur; ancak komşuluk sayısı tek başına yedeklilik sağlamaz. CE cihazları, devreler, provider PE'leri, fiziksel güzergâhlar ve enerji/line-card bağımlılıkları ortak hata alanı taşımamalı; her tekil arızada kalan yolun gerekli prefixleri RIB/FIB'e kurduğu ve trafiği taşıdığı test edilmelidir.",
      "Internal route propagation":"Bir CE'nin harici komşudan öğrendiği rotanın diğer CE tarafından kullanılabilmesi için iBGP veya eşdeğer iç rota dağıtımı ve geçerli next-hop erişimi gerekir. Komşuluk kurulmuş olsa bile next-hop çözülemiyorsa rota forwarding tablosuna girmeyebilir; edge arızasında rota yayılımı ve veri yolu birlikte doğrulanmalıdır.",
      "Asymmetric forwarding risk":"Giden ve gelen trafik için farklı ISP'lerin tercih edilmesi asimetrik yol oluşturabilir. Stateful firewall oturumları, NAT eşlemeleri, uRPF kontrolleri ve izleme araçları bu davranışı desteklemiyorsa erişim kesilebilir; ileri ve dönüş yolları gerçek akışlarla birlikte test edilmelidir.",
      "Route scale safeguard":"Maximum-prefix limiti yanlış veya beklenmeyen rota hacmine karşı koruma sağlar; ancak meşru büyüme eşiği aşarsa komşuluğun kapanmasına ya da yeni rotaların kabul edilmemesine yol açabilir. Uyarı seviyesi, platform aksiyonu, restart davranışı ve beklenen büyüme payı devreye alma öncesinde belirlenmelidir.",
      "Management-plane isolation":"OOB ağı veya management VRF, kullanıcı veri düzleminden bağımsız bir yönetim ve kurtarma yolu sağlamalıdır. Routing, ACL, source-interface ve merkezi servis erişimi ayrı hata alanlarında tasarlanmalı; üretim veri yolu kesildiğinde SSH, AAA, NTP, syslog ve izleme erişiminin devam ettiği kanıtlanmalıdır.",
      "Secure administration":"Yönetim erişimi SSH ve mümkünse sertifika tabanlı kimlik doğrulama üzerinden sağlanmalı; Telnet ve kullanılmayan HTTP/HTTPS servisleri kapatılmalıdır. Kullanılan algoritmalar, anahtar boyutu, idle timeout, erişim ACL'i ve local recovery yöntemi hedef NOS sürümüyle uyumlu olarak doğrulanmalıdır.",
      "Service hardening boundary":"BOOTP, PAD, source routing veya DHCP service gibi servislerin kapatılması cihaz rolüne göre uygulanmalıdır. Özellikle DHCP relay/server veya başka altyapı görevi bulunan cihazlarda genel hardening şablonu işlevsel servisi kesmemeli; her kapatma seçeneği rol ve bağımlılık analiziyle onaylanmalıdır.",
      "ISP configuration scope":"ISP yönlendiricileri bu çalışma alanında harici eşlerdir; uygulama yalnız müşteri CE cihazlarının konfigürasyonunu üretir. ISP tarafındaki neighbor, prefix-filter, community aksiyonu, maximum-prefix, BFD ve inbound politika gereksinimleri sağlayıcıyla ayrı bir demarkasyon dokümanında mutabık kalınmalı ve uçtan uca kabul testine dahil edilmelidir.",
      "Core configuration scope":"StackWise Virtual çifti tek mantıksal core olarak çalıştığından üretilen konfigürasyon iki bağımsız cihaz tasarımı olarak değerlendirilmemelidir. Şasiye özgü hazırlık, SVL/DAD bağlantıları, member uyumluluğu ve active/standby durumları mantıksal konfigürasyondan ayrı doğrulanmalıdır.",
      "Operational visibility":"Syslog, SNMPv3 ve telemetry hedefleri olay, performans ve güvenlik kayıtlarının merkezi izlenmesini sağlamalıdır. Kaynak arayüzü/VRF, zaman damgası, severity, authentication/privacy ayarları ve collector erişimi iki yönlü kontrol edilmeli; cihazda oluşan örnek bir olayın merkezi sistemde görüldüğü kanıtlanmalıdır.",
      "Time and audit integrity":"NTP kaynakları bağımsız ve yönetim ağı üzerinden erişilebilir olmalıdır. Saat sapması; log korelasyonu, sertifika doğrulaması ve AAA kayıtlarını etkiler. Senkronizasyon durumu, seçilen source-interface/VRF ve bir NTP kaynağı kaybedildiğinde diğer kaynağa geçiş doğrulanmalıdır.",
      "Production acceptance criteria":"Kabul testi yalnız komşuluk veya session durumuna bakmamalıdır. Kontrol düzlemi, RIB/FIB, politika sayaçları, gerçek veri iletimi ve her planlı link/cihaz arızasındaki yakınsama birlikte doğrulanmalı; beklenen sonuç, ölçülen kesinti ve rollback eşiği kayıt altına alınmalıdır.",
      "Design scope and boundary":"Bu bölümde üretilmeyen cihazlar, servisler veya kontrol düzlemi bileşenleri tasarım dışında bırakılmış kabul edilmemelidir. Harici bağımlılıklar, sorumluluk sınırı, gerekli ek konfigürasyon ve entegrasyon testleri HLD/LLD ile kabul planında açıkça tanımlanmalıdır."
    },
    en:{
      "Peer-link resiliency and capacity":"The peer-link carries state synchronization and, under specific failures, flooded or backup data traffic. Distribute members across physical failure domains, size the bundle for worst-case failure load, and verify LACP member state under traffic.",
      "Failure-domain separation":"The liveness or dual-active detection path must not share the peer-link's interface, cable path, line card, or transit network. A shared failure could remove both synchronization and remote-peer reachability, increasing split-brain risk.",
      "Spanning-tree integration":"STP mode, VLAN or instance mappings, bridge priority, and peer behavior must match. Verify the operational root and port roles per VLAN or MST instance and measure convergence after failure.",
      "Gateway forwarding continuity":"Peer gateway and ARP/ND synchronization aim to keep local forwarding efficient and retain neighbor state across peer failure. Validate common gateway identity and traffic paths with either peer unavailable.",
      "Multi-chassis consistency":"VLANs, native VLAN, MTU, switchport mode, LACP settings, port-channel IDs, and multi-chassis bundle IDs must be symmetric. Clear global and interface consistency checks before service activation.",
      "Failure recovery behavior":"Delay-restore, reload-delay, and auto-recovery prevent data ports from returning before the control plane is ready. Base timers on measured routing, neighbor-state, and peer-adjacency recovery rather than universal defaults.",
      "Layer 2 protection scope":"Bridge Assurance, Root Guard, BPDU Guard, Loop Guard, and UDLD address different failure modes. Apply each only to the appropriate port role and validate the resulting shutdown or blocking behavior.",
      "Failure detection and convergence":"BFD and protocol timers control detection speed but do not guarantee stable convergence. Match both ends and test under loss, latency, and control-plane load to avoid false failover.",
      "Routing policy effect":"Local Preference, AS-path prepend, MED, communities, and filters act in different decision domains. Verify prefix scope, policy order, counters, RIB/FIB outcome, and asymmetric return paths together.",
      "MTU and encapsulation validation":"MTU is an end-to-end path property. Include encapsulation overhead and test large DF packets, PMTUD, fragmentation, and silent drops using realistic application packet sizes.",
      "Administrative access resilience":"Central AAA still requires independent OOB access and a controlled local break-glass account. Test authorization, accounting, and recovery access during central-service loss.",
      "Control-plane protection":"Design CoPP/CPPr and control-plane ACL policy for the target platform so required routing and management traffic remains available while unwanted traffic is rate-limited. Validate class counters and CPU protection under representative load.",
      "Connectivity resilience":"Multiple eBGP adjacencies provide resilience only when CE devices, circuits, provider paths, power, and line-card dependencies do not share a failure domain. Test RIB/FIB installation and forwarding after every single planned failure.",
      "Internal route propagation":"Routes learned by one CE require internal distribution and reachable next hops before another CE can forward them. Validate iBGP or equivalent propagation, next-hop resolution, RIB/FIB installation, and forwarding during edge failure.",
      "Asymmetric forwarding risk":"Different preferred ingress and egress providers can create asymmetric paths. Validate stateful firewalls, NAT, uRPF, monitoring, and both directions of real application flows.",
      "Route scale safeguard":"Maximum-prefix protects against unexpected route volume but can interrupt learning when legitimate growth exceeds the threshold. Define warning, shutdown, and restart behavior with suitable growth margin.",
      "Management-plane isolation":"OOB or a management VRF must preserve administrative recovery independently of the user data plane. Verify SSH, AAA, NTP, syslog, and monitoring access during production-path failure.",
      "Secure administration":"Use SSH and, where appropriate, certificate-based administration; disable unused Telnet and HTTP services. Validate algorithms, key size, timeouts, access controls, and recovery access on the target NOS release.",
      "Service hardening boundary":"Disable legacy or unnecessary services only after checking the device role. A generic hardening control must not remove required DHCP relay/server or other infrastructure functions.",
      "ISP configuration scope":"ISP routers are external peers, and this workspace generates only customer CE configuration. Agree provider-side neighbors, filters, communities, maximum-prefix, BFD, and inbound policy in a separate demarcation record and include them in acceptance testing.",
      "Core configuration scope":"A StackWise Virtual pair is one logical core; the output is not two independent device configurations. Validate chassis preparation, SVL/DAD, member compatibility, and operational roles separately.",
      "Operational visibility":"Syslog, SNMPv3, and telemetry must deliver usable events to the central collectors. Verify source interface or VRF, timestamps, severity, security settings, and end-to-end receipt of a test event.",
      "Time and audit integrity":"Use independent reachable time sources. Verify synchronization, source interface or VRF, and failover because clock drift affects log correlation, certificates, and AAA records.",
      "Production acceptance criteria":"Acceptance must cover control plane, RIB/FIB, policy counters, real forwarding, and convergence for every planned link or device failure, with measured outage and rollback thresholds recorded.",
      "Design scope and boundary":"Components not generated here still require explicit ownership, configuration, and integration testing. Record external dependencies and boundaries in the HLD, LLD, and acceptance plan."
    }
  };
  const additional={
    "Management topology scope":["Yönetim topolojisinin kapsamı","OOB ağı ve merkezi yönetim servisleri harici uçlardır; yalnız konfigürasyonu üretilen cihaz tasarım kapsamındadır.","The OOB network and management services are external endpoints; only the configured device is in the design scope."],
    "Underlay scope":["Underlay kapsamı","EVPN komşulukları mantıksal oturumlardır. Fiziksel underlay portları topoloji görselinden çıkarılmaz; loopback erişimi, yönlendirme ve MTU ayrıca tasarlanmalıdır.","EVPN adjacencies are logical sessions. Physical underlay ports are not inferred from the diagram; loopback reachability, routing and MTU require separate engineering."],
    "Route reflector scope":["Route reflector kapsamı","İki RR yalnız EVPN kontrol düzlemini üstlenir. Dört VTEP her iki RR ile aynı overlay ASN içinde komşuluk kurar. RR'lar veri trafiğini sonlandırmaz; fiziksel underlay erişimi ve bağımsız hata alanları ayrıca tasarlanmalıdır.","Two control-plane-only RRs serve the four VTEPs in one overlay ASN. Each VTEP peers with both RRs. The RRs do not terminate overlay data traffic; underlay reachability and independent failure domains require separate engineering."],
    "Leaf uplink configuration":["Leaf uplink konfigürasyonu","Huawei leaf fiziksel uplink portları sahaya göre atanmalıdır. Uplink, Eth-Trunk ve M-LAG kimlikleri gerçek port planıyla karşılaştırılmadan uygulamaya hazır kabul edilmemelidir.","Huawei physical leaf uplinks are deployment-specific. Validate assigned ports, Eth-Trunks and M-LAG identifiers against the actual port plan before deployment."],
    "SD-WAN scope":["SD-WAN kapsamı","Yalnız seçilen uç cihaz için konfigürasyon üretilir. Controller, taşıma ağları ve diğer sahalar harici gösterimlerdir; bunlar envanter cihazı olarak varsayılmamalıdır.","Only the selected edge has generated configuration. Controllers, transports and other sites are external representations and must not be assumed to be inventory devices."],
    "SD-WAN validation pending":["SD-WAN doğrulaması bekliyor","Seçilen uç cihazın saha, kimlik ve taşıma girdileri Workspace doğrulamasından geçmelidir. Eksik veya hatalı girdiler tamamlanmadan konfigürasyon uygulanmamalıdır.","The selected edge's site, identity and transport inputs must pass workspace validation. Do not deploy configuration while required inputs are missing or invalid."],
    "Configuration pending":["Konfigürasyon bekliyor","Excel planından yönlendirici seçin veya cihaz kimliği ve bağlantı bilgilerini Technology Workspace içinde tamamlayın. Ardından raporu yeniden aktarın.","Select a router from the Excel plan or complete its identity and connection details in Technology Workspaces, then refresh the report."],
    "SD-WAN design status":["SD-WAN tasarım durumu","Saha ve taşıma bilgileri tamamlanıp seçilen uç cihaz doğrulanana kadar topoloji ve konfigürasyon eki taslaktır.","Topology and configuration remain a draft until site and transport inputs are complete and the selected edge passes workspace validation."],
    "Router identity stability":["Yönlendirici kimliğinin kararlılığı","OSPF router ID değerleri benzersiz ve kararlı olmalıdır. Kimlik değişikliği süreç veya komşuluk yeniden kuruluşuna yol açabileceği için kontrollü değişiklik olarak planlanmalıdır.","OSPF router IDs must remain unique and stable. A change may restart the process or adjacency and requires a controlled change plan."],
    "Neighbor discovery scope":["Komşu keşfinin kapsamı","CDP yalnız Cisco platformunda, LLDP desteklenen switching platformlarında kullanılır. Keşif bilgisi port planı için yardımcı kanıttır; servis erişimi veya bağlantı doğruluğunu tek başına kanıtlamaz.","CDP applies to Cisco platforms and LLDP to supported switching platforms. Discovery assists port-plan verification but does not independently prove service reachability."],
    "EVPN route distribution":["EVPN rota dağıtımı","Type-2 endpoint MAC/IP erişimini, Type-3 IMET BUM çoğaltma üyeliğini, Type-5 ise tenant IP prefix erişimini taşır. Rota bulunması yeterli değildir; RT kabulü, VTEP next-hop çözümü ve donanım iletimi birlikte doğrulanmalıdır.","Type-2 carries endpoint MAC/IP reachability, Type-3 IMET signals BUM replication membership and Type-5 carries tenant IP prefixes. Validate RT import, VTEP next-hop resolution and hardware forwarding alongside the route table."]
  };
  for(const [label,[trLabel,tr,en]] of Object.entries(additional)){
    noteLabels.tr[label]=trLabel;noteImpacts.tr[label]=tr;noteImpacts.en[label]=en;trImpact[label]=tr;trDecisionLabels[label]=trLabel;
  }
  const classifyLegacyNote=(label,impact)=>{
    if(!/implementation consideration$/i.test(label))return label;
    const text=String(impact||"").toLowerCase();
    if(/architecture intent|evpn domains|single evpn fabric/.test(text))return "EVPN fabric and control plane";
    if(/tenant routing intent/.test(text))return "Tenant routing and IP prefix exchange";
    if(/evpn route behavior/.test(text))return "EVPN route distribution";
    if(/cisco overlay realization|cisco route identity|cisco next-hop behavior/.test(text))return "Cisco NX-OS forwarding realization";
    if(/arista overlay realization/.test(text))return "Arista EOS forwarding realization";
    if(/huawei overlay realization|huawei distributed gateway/.test(text))return "Huawei CloudEngine forwarding realization";
    if(/endpoint optimization|endpoint and bum handling/.test(text))return "Overlay resilience and neighbor handling";
    if(/network type|area .*backbone area/.test(text))return "OSPF adjacency and flooding domain";
    if(/interface cost/.test(text))return "Route selection";
    if(/router ids/.test(text))return "Router identity stability";
    if(/intended as root|stp mode\/priority/.test(text))return "Spanning-tree root and failover";
    if(/vlan scope|downstream policy/.test(text))return "VLAN scope and loop prevention";
    if(/physically dual-attached/.test(text))return "Loop-free Layer 2 architecture";
    if(/eth-trunk \/ m-lag id/.test(text))return "Multi-chassis consistency";
    if(/class .*matches critical dscp/.test(text))return "Traffic classification";
    if(/policing|shaping|wred|explicit scheduler/.test(text))return "Congestion and bandwidth policy";
    if(/system ip|system-ip|organization name|certificate identity/.test(text))return "Site identity and overlay membership";
    if(/wan-1 .*color|restricted.*tunnels|restricted.*nat/.test(text))return "Transport diversity and preference";
    if(/cdp cisco/.test(text))return "Neighbor discovery scope";
    if(/copp|cppr|control-plane acl|control plane acl/.test(text))return "Control-plane protection";
    if(/selected .*ce.*isp|ebgp adjacenc|circuits, provider paths|physical or operational failure domain/.test(text))return "Connectivity resilience";
    if(/ibgp distributes|next-hop reachability|internal ce peering|learned by one ce/.test(text))return "Internal route propagation";
    if(/asymmetric forwarding|stateful firewall|nat, urpf|return path/.test(text))return "Asymmetric forwarding risk";
    if(/maximum-prefix|maximum prefix|route volume/.test(text))return "Route scale safeguard";
    if(/oob management|management vrf|management plane/.test(text))return "Management-plane isolation";
    if(/ssh|telnet|http\/https|certificate-based management/.test(text))return "Secure administration";
    if(/dhcp service|bootp|source routing|service-hardening/.test(text))return "Service hardening boundary";
    return label;
  };
  const localizeDecisionValue=value=>{
    const phrases={
      "dual data center with two configured route reflectors":"İki route reflector ile çift veri merkezi","multi-site with border gateways":"Border gateway ile çok sahalı fabric","dual data center":"Çift veri merkezi","single fabric":"Tek fabric",
      "Anycast Gateway not selected":"Anycast Gateway seçilmedi","ARP flooding retained":"ARP flooding korunuyor","PIP/virtual RMAC advertisement":"PIP/virtual RMAC ilanı","default next-hop behavior":"varsayılan next-hop davranışı","Gateway location requires review":"Gateway konumu gözden geçirilmeli","Centralized gateway requires review":"Merkezi gateway gözden geçirilmeli","Distributed gateway":"Dağıtık gateway","single attachment":"tekil bağlantı","MLAG/standalone attachment":"MLAG/standalone bağlantı","No trust boundary selected":"Trust sınırı seçilmedi","standard MTU":"standart MTU","No active Local Preference policy":"Etkin Local Preference politikası yok","No explicit congestion action selected":"Açık bir tıkanıklık aksiyonu seçilmedi","No internal CE peering":"İç CE peering seçilmedi","Inbound traffic engineering disabled":"Gelen trafik mühendisliği devre dışı","Outbound traffic engineering disabled":"Giden trafik mühendisliği devre dışı","not selected":"seçilmedi","member links":"üye bağlantı","dual-attached leaves":"çift bağlı leaf","intended primary":"amaçlanan primary","Preferred ISP":"Tercih edilen ISP","central AAA with local fallback":"yerel yedekli merkezi AAA","central syslog":"merkezi syslog","NTP sources":"NTP kaynağı"
    };
    let result=String(value||"");
    Object.entries(phrases).sort((a,b)=>b[0].length-a[0].length).forEach(([source,target])=>{result=result.replace(new RegExp(source.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"gi"),target);});
    return result.replace(/ authentication/gi," kimlik doğrulaması").replace(/ enabled/gi," etkin");
  };
  const localizeParameter=(p,language="en")=>{
    if(p.impactTr)return {...p,label:language==="tr"?p.labelTr:p.label,impact:language==="tr"?p.impactTr:p.impact,value:language==="tr"?(p.valueTr||p.value):p.value};
    const parts=String(p.label||"").split(" · "),rawBase=parts.pop(),base=classifyLegacyNote(rawBase,p.impact),prefix=parts.join(" · ");
    if(language==="en")return {...p,label:[prefix,base].filter(Boolean).join(" · "),impact:p.value==="Design boundary"?(noteImpacts.en[base]||p.impact):p.impact};
    const translated=trDecisionLabels[base]||noteLabels.tr[base]||base.replace(/ implementation consideration$/i," uygulama değerlendirmesi"),label=[prefix,translated].filter(Boolean).join(" · ");
    const impact=p.value==="Design boundary"?(noteImpacts.tr[base]||trImpact[base]||p.impact):(trImpact[base]||p.impact);
    const value=localizeDecisionValue(p.value);
    return {...p,label,value,impact};
  };

root.NetworkLocale=Object.freeze({reportWords,localizeParameter,classifyNote:classifyLegacyNote});
})(typeof window!=="undefined"?window:globalThis);
