/* Project-specific operational explanations. Only modeled or configured
 * mechanisms are described; acceptance scenarios are plans, not test results. */
(function(root){
 'use strict';
 const vendorName=v=>({'Huawei_CE_SW':'Huawei CloudEngine','Cisco IOS-XE':'Cisco IOS XE'}[v]||v);
 const unique=rows=>[...new Set(rows)];
 function kind(scope){const key=scope.module||scope.moduleKey;return key||(/EVPN|VXLAN/i.test(scope.technology)?'EVPN':/iStack|StackWise|vPC|M.?LAG/i.test(scope.technology)?'VPC':/system|management/i.test(scope.technology)?'BASIC':/SD.?WAN/i.test(scope.technology)?'SDWAN':/QoS/i.test(scope.technology)?'QOS':/OSPF/i.test(scope.technology)?'OSPF':/BGP/i.test(scope.technology)?'BGP':/STP/i.test(scope.technology)?'STP':'');}
 function build(state){
  const tr=state.language==='tr',p=(a,b)=>tr?a:b;
  const scopes=state.moduleReports?.length?state.moduleReports:[{module:state.source?.module,technology:state.technology,vendor:state.vendor,design:state}];
  const sections=[],sources=[];
  const referenceMap={BGP:[p('RFC 4271 · BGP rota seçimi','RFC 4271 · BGP route selection'),'https://www.rfc-editor.org/rfc/rfc4271'],OSPF:[p('RFC 2328 · OSPF komşuluk ve SPF','RFC 2328 · OSPF adjacency and SPF'),'https://www.rfc-editor.org/rfc/rfc2328'],QOS:[p('RFC 2474 · Farklılaştırılmış hizmetler','RFC 2474 · Differentiated Services'),'https://www.rfc-editor.org/rfc/rfc2474'],EVPN:[p('RFC 7432 · EVPN kontrol düzlemi','RFC 7432 · EVPN control plane'),'https://www.rfc-editor.org/rfc/rfc7432'],BASIC:[p('RFC 5905 · NTP senkronizasyonu','RFC 5905 · NTP synchronization'),'https://www.rfc-editor.org/rfc/rfc5905']};
  for(const scope of scopes){
   const type=kind(scope);if(!type)continue;
   const ref=referenceMap[type]||(type==='VPC'?(scope.vendor==='Arista EOS'?['Arista EOS · MLAG','https://www.arista.com/en/um-eos/eos-multi-chassis-link-aggregation']:scope.vendor==='Huawei_CE_SW'?['Huawei · M-LAG','https://info.support.huawei.com/info-finder/encyclopedia/en/M-LAG.html']:null):null);
   if(ref&&!sources.some(s=>s.url===ref[1]))sources.push({title:ref[0],url:ref[1]});
   const design=scope.design||state,devices=(design.devices||[]).filter(d=>!d.inventoryOnly&&!d.external),names=unique(devices.map(d=>d.logicalHostname||d.hostname).filter(Boolean));
   const targets=(state.devices||[]).filter(d=>names.includes(d.hostname)&&(!d.vendor||d.vendor===scope.vendor));
   const texts=(state.configurations||[]).filter(c=>targets.some(d=>d.id===c.deviceId)||(!state.moduleReports?.length&&devices.some(d=>d.id===c.deviceId))).map(c=>{const raw=c.text||'',parts=raw.split(/^######## (.*?) · .*? ########\s*$/m);if(parts.length===1)return raw;const selected=[];for(let i=1;i<parts.length;i+=2)if(parts[i].trim()===(scope.title||scope.technology||type).toUpperCase())selected.push(parts[i+1]);return selected.length?selected.join('\n'):raw;});
   const text=texts.join('\n'),links=(design.links||[]).filter(l=>l.enabled),paragraphs=[],scenarios=[];
   const identity=scope.technology||scope.title||type;
   const records=(state.verificationPlan||[]).filter(r=>r.included&&r.vendor===scope.vendor&&(r.technology===identity||r.technology===scope.title));
   const add=(title,impact,acceptance,pattern)=>{const evidence=records.filter(r=>pattern.test(r.command)).map(r=>`${r.hostname}: ${r.command}`);scenarios.push({title,impact,acceptance,evidence:evidence.length?unique(evidence).join('\n'):p('Kabul planı; bu senaryo için komut kanıtı henüz seçilmedi.','Acceptance plan; command evidence has not yet been selected for this scenario.'),status:p('Test edilmedi','Not tested')});};
   if(!texts.length){paragraphs.push(p('Bu teknoloji için cihaz konfigürasyonu oluşturulduğunda, seçili mekanizmaların işletim değerlendirmesi ve kabul senaryoları bu bölüme eklenecektir.','Operational assessment and acceptance scenarios for selected mechanisms will be included when device configurations are generated for this technology.'));sections.push({title:`${identity} · ${vendorName(scope.vendor)}`,paragraphs,scenarios});continue;}
   if(type==='BGP'){
    const peers=unique([...text.matchAll(/(?:neighbor|peer)\s+(\d+(?:\.\d+){3})\s+(?:remote-as|as-number)\s+(\d+)/g)].map(m=>`${m[1]} / AS ${m[2]}`));
    const preferences=unique([...text.matchAll(/(?:set|apply)\s+local-preference\s+(\d+)/g)].map(m=>Number(m[1]))).sort((a,b)=>b-a);
    paragraphs.push(p(`Konfigürasyonlarda ${peers.length} farklı BGP komşu adresi/ASN eşleşmesi bulunur. Rota öğrenimi, rota politikası ve next-hop erişimi ayrı işlevlerdir: oturumun Established olması, alınan prefixin yönlendirme tablosuna kurulmasını veya hizmet trafiğinin doğru çıkıştan iletilmesini tek başına kanıtlamaz.`,`The configurations contain ${peers.length} distinct BGP peer-address/ASN combinations. Route learning, route policy and next-hop reachability are separate functions: an Established session alone does not prove that a received prefix is installed or service traffic uses the intended exit.`));
    if(preferences.length)paragraphs.push(p(`Seçili politikalarda Local Preference değerleri ${preferences.join(' / ')} olarak üretilmiştir. Daha önce değerlendirilen platform kriterleri eşit olduğunda yüksek değer çıkış yolunu tercih ettirir. Bu politika müşteri AS'i içindeki seçimi etkiler; dış ağların giriş yönündeki kararlarını belirlemez. Eşit maliyetli kullanımın oluşması için diğer gerekli path kriterlerinin de uyumlu olması gerekir.`,`Selected policies generate Local Preference values ${preferences.join(' / ')}. When preceding platform criteria are equal, the higher value favors the outbound path. This controls selection within the customer AS, not inbound decisions made by external networks. Multipath additionally requires compatible eligible path attributes.`));
    if(/(?:as-path.*prepend|apply as-path|set aspath|set as-path)/i.test(text))paragraphs.push(p('AS-path düzenlemesi, ilan edilen yolun dış ağlar tarafından değerlendirilmesini etkileyebilir. Sağlayıcının Local Preference ve import politikaları bu etkiyi geçersiz kılabilir; inbound tercih kabulü dış noktadan gözlem gerektirir.','AS-path manipulation can influence evaluation of the advertised path by external networks. Provider Local Preference and import policies can override that influence; inbound-path acceptance requires an observation point outside the customer network.'));
    const providers=devices.length?(design.devices||[]).filter(d=>d.external).length:0;
    add(p('CE–ISP oturumu veya devre kaybı','CE–ISP session or circuit loss'),providers>1?p(`${providers} ISP cihazı modellenmiştir. Alternatif prefix ve erişilebilir next-hop varsa kalan yol kullanılabilir; fiziksel/provider ortak bağımlılıkları ayrıca değerlendirilir.`,`${providers} ISP devices are modeled. A surviving path is usable only when an alternative prefix and reachable next hop exist; shared physical/provider dependencies require separate review.`):p('İkinci ISP yolu modellenmediğinden sağlayıcılar arası failover iddiası kurulamaz; etkilenen prefixler için hizmet kaybı beklenebilir.','No second ISP path is modeled, so inter-provider failover cannot be asserted; affected prefixes may lose service.'),p('Seçili prefixlerde normal best path, oturum kaybından sonraki route withdrawal ve gerçek trafik yolu kaydedilir. Tek sağlayıcıda hizmet etkisi, çok sağlayıcıda kalan yolun kullanılabilirliği doğrulanır.','Record the normal best path, withdrawal after session loss and actual traffic path for selected prefixes. Verify service impact with one provider or surviving-path usability with multiple providers.'),/bgp|route|routing-table|traceroute|ping/i);
    add(p('Rota politikasının doğru prefixe uygulanması','Route policy applied to the intended prefix'),p('Yanlış import/export eşleşmesi rota kaybı, beklenmeyen ilan veya yanlış çıkış seçimi doğurabilir.','Incorrect import/export matching can cause route loss, unintended advertisement or incorrect exit selection.'),p('İzin verilen ve reddedilen test prefixleri, ilan/alım tabloları ve seçili policy attribute değerleri birlikte karşılaştırılır.','Compare permitted and rejected test prefixes, advertised/received routes and selected policy attributes together.'),/bgp|route|policy|prefix/i);
   }else if(type==='OSPF'){
    const areas=unique([...text.matchAll(/\barea\s+([\d.]+)/g)].map(m=>m[1]));
    const ptp=/network(?:-type)?\s+(?:point-to-point|p2p)/i.test(text);
    paragraphs.push(p(`Konfigürasyonda OSPF area değerleri ${areas.join(', ')} olarak yer alır. ${ptp?'Seçili point-to-point ağ tipi iki uç arasında DR/BDR seçimi gerektirmez.':'Ağ tipi ve DR/BDR davranışı arayüz konfigürasyonu ve ortak segment yapısıyla birlikte değerlendirilir.'} SPF sonucu toplam path cost ile belirlenir; tek arayüz cost değerinin değiştirilmesi ancak mevcut alternatif yollarla karşılaştırıldığında trafik yönünü etkiler.`,`Configured OSPF areas are ${areas.join(', ')}. ${ptp?'The selected point-to-point network type avoids DR/BDR election between its two endpoints.':'Network type and DR/BDR behavior must be assessed against interface configuration and the shared segment.'} SPF uses accumulated path cost; changing one interface cost affects traffic selection only relative to available alternative paths.`));
    add(p('OSPF komşuluğu veya yönlendirilmiş bağlantı kaybı','OSPF adjacency or routed-link loss'),links.length>1?p('LSA değişimi ve SPF yeniden hesaplaması kalan modellenmiş yolları değerlendirebilir; birden fazla çizilen bağlantı tek başına uçtan uca yedek yol garantisi değildir.','LSA changes and SPF recomputation may use remaining modeled paths; multiple drawn links alone do not guarantee end-to-end redundancy.'):p('Tek bağlantılı modelde alternatif OSPF yolu modellenmemiştir; bağlantı kaybı ilgili prefix erişimini kesebilir.','The single-link model contains no modeled alternative OSPF path; link loss can interrupt reachability to affected prefixes.'),p('Area, ağ tipi, gerekli komşuluk durumu, LSDB, kurulan rota ve uçtan uca erişim birlikte doğrulanır; kesinti süresi kabul testinde ölçülür.','Verify area, network type, required adjacency state, LSDB, installed route and end-to-end reachability together; measure interruption during acceptance.'),/ospf|route|routing-table|ping|traceroute/i);
   }else if(type==='VPC'){
    const stack=scope.vendor==='Huawei iStack'||/StackWise/i.test(identity),special=(design.specialLinks||[]),peer=special.filter(s=>/peer.?link|stack|svl/i.test(s.kind||'')&&!s.logical),liveness=special.filter(s=>/keepalive|dad|mad/i.test(s.kind||''));
    paragraphs.push(stack?p(`Bu tasarımda stack üyeleri tek mantıksal switch hizmeti sunar. Stack/SVL bağlantıları kontrol ve üyeler arası veri iletiminin parçasıdır; bağımsız cihaz yönetimi yerine ortak servis konfigürasyonu esas alınır. Rapordaki özel bağlantı planında ${peer.length} stack/SVL bağlantı kaydı bulunur.`,`Stack members provide one logical switch service in this design. Stack/SVL interconnects participate in control and inter-member forwarding; shared service configuration applies instead of independent device management. The special-connection plan contains ${peer.length} stack/SVL connection records.`):p(`${identity}, eş cihazların downstream link aggregation hizmetini koordine eder; cihazları tek bir routing/control-plane haline getirmez. Özel bağlantı planında ${peer.length} fiziksel peer-link kaydı bulunur. Bir akış, port-channel/Eth-Trunk hash sonucunda bir üyeyi kullanır; tek akış için bundle toplam bant genişliği varsayılmamalıdır.`,`${identity} coordinates downstream link aggregation between peers; it does not merge their routing/control planes. The special-connection plan contains ${peer.length} physical peer-link records. A flow uses a member selected by the port-channel/Eth-Trunk hash; aggregate bundle bandwidth must not be assumed for one flow.`));
    const hasDetection=stack?/\bmad\b|dual-active-detection/i.test(text):scope.vendor==='Cisco NX-OS'?/peer-keepalive/i.test(text):scope.vendor==='Huawei_CE_SW'?/dual-active|source ip|peer-link/i.test(text):/mlag configuration/i.test(text);
    if(stack){add(p('Stack/SVL bölünmesi veya üye kaybı','Stack/SVL partition or member loss'),hasDetection?p('Konfigürasyonda dual-active/MAD mekanizması bulunur; bölünmede bağımsız aktif parçaların aynı hizmeti eşzamanlı sunması engellenmelidir. Kalan üye kapasitesi ve cross-member bundle davranışı ayrıca değerlendirilir.','Dual-active/MAD configuration is present; independently active partitions must be prevented from serving the same service simultaneously. Assess surviving member capacity and cross-member bundle behavior separately.'):p('Üretilen konfigürasyonda dual-active/MAD mekanizması tespit edilmedi; partition koruması doğrulanmadan split senaryosu için süreklilik iddia edilmez.','No dual-active/MAD mechanism was detected in the generated configuration; partition continuity cannot be asserted until split protection is verified.'),p('Üye rolleri, interconnect durumu, koruma aksiyonu, aktif bundle üyeleri ve hizmet erişimi arıza öncesi/sonrası kaydedilir.','Record member roles, interconnect state, protection action, active bundle members and service reachability before and after failure.'),/stack|mad|virtual|etherchannel|eth-trunk|interface/i);}
    else{
     const cisco=scope.vendor==='Cisco NX-OS';
     add(p('Peer-link erişiminin kaybı','Peer-link reachability loss'),cisco?p('Keepalive eşin canlı olduğunu doğruluyorsa Cisco vPC secondary, etkilenen vPC member bağlantılarını askıya alarak dual-active iletimi sınırlar. Orphan bağlantıları ve gateway etkisi ayrı incelenir.','When keepalive confirms the peer is alive, the Cisco vPC secondary suspends affected vPC member links to contain dual-active forwarding. Orphan attachments and gateway impact require separate review.'):scope.vendor==='Arista EOS'?p('EOS MLAG peer IP erişimi ve peer-link üzerinden durum eşlemesi kesilebilir. Üye portların kullanılabilirliği ve dual-primary koruması, konfigürasyonda seçilen EOS mekanizmalarıyla değerlendirilir.','EOS MLAG peer IP reachability and peer-link state synchronization can be interrupted. Assess member-port availability and dual-primary protection against the selected EOS mechanisms.'):p('Huawei DFS eş ilişkisi ve M-LAG durum eşlemesi etkilenir. Üye Eth-Trunk iletimi, DFS rolü ve dual-active koruması birlikte doğrulanır.','Huawei DFS peer relationship and M-LAG state synchronization are affected. Verify member Eth-Trunk forwarding, DFS role and dual-active protection together.'),p('Peer ilişkisi, member durumu, VLAN/konfigürasyon tutarlılığı ve dual-homed hizmet erişimi birlikte kaydedilir; kalan yol kapasitesi ölçülür.','Record peer state, member status, VLAN/configuration consistency and dual-homed service reachability together; measure surviving-path capacity.'),/vpc|mlag|m-lag|dfs|port-channel|eth-trunk|interface/i);
     if(liveness.length)add(p('Bağımsız canlılık/dual-active yolunun kaybı','Independent liveness / dual-active path loss'),p(`${liveness.length} özel canlılık bağlantısı kaydı vardır. Peer-link sağlamken yalnız bu yolun kaybı ile peer-link de kaybedildiğinde oluşan durum farklı arıza koşullarıdır.`,`${liveness.length} dedicated liveness-path records exist. Losing only this path with a healthy peer-link differs from losing the peer-link as well.`),p('Her yol ayrı test edilir; koruma davranışı ve servis durumu seçili platform, arıza sırası ve hedef sürümle karşılaştırılır.','Test each path separately; compare protection behavior and service state against the selected platform, failure order and target release.'),/vpc|mlag|dfs|ping|interface/i);
    }
    const delay=unique([...text.matchAll(/(?:delay restore|reload-delay(?: mlag)?|up-delay)\s+(\d+)/g)].map(m=>m[1]));if(delay.length)paragraphs.push(p(`Konfigürasyonda ${delay.join(' / ')} saniyelik servis geri dönüş gecikmeleri bulunur. Bu süreler arıza tespit süresi değil, yeniden katılan cihazın servis sunmasını erteleyen koşullardır; ölçülen kontrol düzlemi yakınsamasıyla değerlendirilir.`,`The configuration contains service-restoration delays of ${delay.join(' / ')} seconds. These are not failure-detection times; they defer service from a recovering device and must be assessed against measured control-plane convergence.`));
   }else if(type==='EVPN'){
    const vnis=unique([...text.matchAll(/(?:vn-segment|vni)\s+(\d+)/g)].map(m=>m[1]));
    paragraphs.push(p(`Konfigürasyonlarda ${vnis.length} farklı VNI değeri bulunur. Underlay, uzak VTEP'e IP erişimi sağlar; BGP EVPN hizmet erişim bilgisini dağıtır; VXLAN veri paketlerini taşır. Bu üç katmanın sağlığı ayrı kontrol edilir. Route-target import/export eşleşmesi tenant erişim sınırını, gateway yerleşimi ise yerel/uzak yönlendirme davranışını belirler.`,`The configurations contain ${vnis.length} distinct VNI values. The underlay provides IP reachability to remote VTEPs, BGP EVPN distributes service reachability, and VXLAN carries data packets. Verify these three layers independently. Route-target import/export matching defines tenant reachability boundaries; gateway placement determines local versus remote routing behavior.`));
    add(p('VTEP veya underlay bağlantı erişiminin kaybı','VTEP or underlay-link reachability loss'),p('IP erişimi kaybolursa geçerli görünen EVPN kaydı veri iletimi için yeterli olmayabilir. Alternatif underlay yolunun ve kullanılan encapsulation MTU değerinin çalışması gerekir.','Loss of IP reachability can make an apparently valid EVPN entry unusable for forwarding. Any alternative underlay path and the effective encapsulation MTU must operate correctly.'),p('Uzak VTEP erişimi, EVPN rotası, VNI eşleşmesi ve tenant içi gerçek trafik arıza öncesi/sonrası karşılaştırılır.','Compare remote VTEP reachability, EVPN routes, VNI mappings and real tenant traffic before and after failure.'),/evpn|vxlan|nve|vni|route|ping/i);
    add(p('Tenant izolasyonu ve gateway erişimi','Tenant isolation and gateway reachability'),p('Yanlış RT veya VLAN/VNI eşleşmesi istenmeyen tenant erişimi ya da hizmet kaybı yaratabilir.','Incorrect RT or VLAN/VNI mapping can create unintended tenant reachability or service loss.'),p('İzin verilen same-VRF erişimler ve izin verilmeyen cross-VRF erişimler birlikte test edilir; gateway ve MAC/IP kayıtları ilgili tenant kapsamında olmalıdır.','Test permitted same-VRF and prohibited cross-VRF reachability together; gateway and MAC/IP records must belong to the intended tenant.'),/evpn|vxlan|nve|vni|vrf|mac|arp|route|ping/i);
   }else if(type==='STP'){
    const priorities=unique([...text.matchAll(/(?:priority|root priority)\s+(\d+)/g)].map(m=>m[1]));
    paragraphs.push(p(`STP seçimi Layer 2 döngüleri engellemek için bazı yedek yolları blocking/discarding durumunda tutabilir. Konfigürasyondaki priority değerleri ${priorities.join(' / ')} olarak yer alır; root seçimi priority ile birlikte bridge MAC kimliğine bağlıdır. Fiziksel yedeklilik, bütün bağlantıların aynı anda veri taşıdığı anlamına gelmez.`,`STP may keep redundant paths blocking/discarding to prevent Layer 2 loops. Configured priority values are ${priorities.join(' / ')}; root election depends on bridge MAC identity as well as priority. Physical redundancy does not mean every link forwards service traffic simultaneously.`));
    add(p('Root veya aktif uplink kaybı','Root or forwarding-uplink loss'),p('Kalan Layer 2 yollar için port rolleri yeniden hesaplanır. VLAN/instance kapsamı, edge davranışı ve koruma ayarları hizmetin hangi yoldan döneceğini etkiler.','Port roles are recalculated for remaining Layer 2 paths. VLAN/instance scope, edge behavior and protection settings affect the restored forwarding path.'),p('Beklenen root/secondary kimliği, forwarding/discarding portları, topology-change kayıtları ve gerçek hizmet erişimi arıza öncesi/sonrası karşılaştırılır.','Compare intended root/secondary identity, forwarding/discarding ports, topology-change records and actual service reachability before and after failure.'),/spanning|stp|interface|mac|ping/i);
    if(/bpdu.?guard|bpdu-protection/i.test(text))add(p('Edge portta beklenmeyen BPDU','Unexpected BPDU on an edge port'),p('Seçili BPDU koruması yanlış switch bağlantısını sınırlandırabilir; korumaya giren portun hizmet etkisi ve geri alma prosedürü işletim planına dahildir.','Selected BPDU protection can contain an unintended switch attachment; service impact and recovery procedure for the protected port belong in the operating plan.'),p('Koruma aksiyonu, alarm ve kontrollü port geri dönüşü doğrulanır.','Verify the protection action, alarm and controlled port recovery.'),/stp|spanning|errdisable|interface/i);
   }else if(type==='QOS'){
    const rates=unique([...text.matchAll(/\b(?:police|shape|cir)\s+(?:cir\s+)?(?:average\s+)?(\d+)/g)].map(m=>m[1]));
    paragraphs.push(p(`QoS sınıflandırması, marking/trust sınırı ve egress işlem sırası birlikte değerlendirilir. ${rates.length?`Konfigürasyonda ${rates.length} farklı rate değeri bulunur; bunların birimi ve bağlı olduğu sınıf/arayüz platform çıktısıyla karşılaştırılır.`:'Konfigürasyonda rate işlemi tespit edilmedi; marking veya MTU ayarı tek başına bant genişliği rezervasyonu oluşturmaz.'} Öncelik yalnız politikanın uygulandığı kuyruk ve darboğaz kapsamında anlamlıdır.`,`Assess QoS classification, marking/trust boundaries and egress action order together. ${rates.length?`The configuration contains ${rates.length} distinct rate values; verify their units and associated class/interface against platform output.`:'No rate action was detected; marking or MTU configuration alone does not reserve bandwidth.'} Priority has meaning only within the queue and bottleneck where the policy is applied.`));
    add(p('Kontrollü yoğunluk altında sınıf davranışı','Class behavior under controlled congestion'),p('Queueing, policing veya shaping seçimi burst, drop ve gecikmeyi farklı şekilde etkiler; toplam port yükü sınıf davranışından ayrı değildir.','Queueing, policing and shaping affect bursts, drops and delay differently; total port load influences class behavior.'),p('Tanımlı test trafiğinin doğru sınıfa eşleşmesi, politikanın doğru arayüz/yönde bulunması ve sınıf bazında rate/drop/queue sayaçları doğrulanır. Gecikme/kayıp eşiği proje kabul gereksinimiyle karşılaştırılır.','Verify that defined test traffic matches the intended class, that the policy applies on the intended interface/direction, and check per-class rate/drop/queue counters. Compare delay/loss against project acceptance requirements.'),/policy|qos|queue|traffic|interface|ping/i);
   }else if(type==='BASIC'){
    const ntp=unique([...text.matchAll(/ntp(?:-service)?\s+(?:server|unicast-server)\s+(\S+)/g)].map(m=>m[1]).concat([...(text.match(/config system ntp[\s\S]*?\nend/i)?.[0]||'').matchAll(/set server \"?([^\"\s]+)/g)].map(m=>m[1])));
    paragraphs.push(p(`Yönetim hizmetleri üretim trafiğinin routing veya switching kontrolünden ayrı bir işletim katmanıdır. Konfigürasyonlarda ${ntp.length} farklı NTP kaynak kaydı bulunur. Merkezi erişim, zaman senkronizasyonu ve log toplama birlikte olayların aynı zaman çizgisinde incelenmesini destekler; servis konfigürasyonunun varlığı sunucu erişiminin çalıştığını kanıtlamaz.`,`Management services form an operating layer distinct from production routing or switching control. The configurations contain ${ntp.length} distinct NTP source records. Central access, time synchronization and log collection support a consistent incident timeline; configuration presence alone does not prove server reachability.`));
    if(/tacacs|radius|authentication.*(?:group|radius|hwtacacs)/i.test(text))add(p('Merkezi AAA sunucusuna erişim kaybı','Loss of reachability to central AAA'),p('Authentication ve authorization davranışı seçilen yöntem sırasına bağlıdır; yerel kullanıcı bulunması tek başına başarılı fallback garantisi değildir.','Authentication and authorization behavior depend on method order; a local user alone does not guarantee successful fallback.'),p('Yetkili test kullanıcılarıyla normal login, AAA erişim kaybı, yerel yöntem ve komut yetkileri doğrulanır; kurtarma erişimi bakım planıyla eşleştirilir.','Verify normal login, AAA reachability loss, local method and command authorization with approved test accounts; align recovery access with the maintenance plan.'),/aaa|tacacs|radius|user|access|ssh/i);
    if(ntp.length||/logging|info-center|syslog/i.test(text))add(p('Zaman ve merkezi olay görünürlüğü','Time and centralized event visibility'),p('Saat sapması veya log sunucusu erişim kaybı olay korelasyonunu bozabilir; forwarding hizmeti sürerken operasyonel kanıt kaybı yaşanabilir.','Clock drift or log-server reachability loss can impair incident correlation; forwarding may continue while operational evidence is lost.'),p('Seçilen zaman kaynağı ve senkronizasyon durumu kontrol edilir; kontrollü olayın merkezi logda doğru cihaz ve zamanla görüldüğü doğrulanır.','Check selected time source and synchronization; verify that a controlled event appears in the central log with the correct device and timestamp.'),/ntp|clock|logging|logbuffer|info-center/i);
   }else if(type==='SDWAN'){
    const transports=unique((design.specialLinks||[]).filter(l=>/transport|wan/i.test(l.kind||'')).map(l=>l.detail||l.kind));
    paragraphs.push(p(`Seçili Cisco cEdge için underlay erişimi, control connection/OMP bilgisi ve tunnel/data-plane durumu ayrı sorumluluklardır. ${transports.length?`${transports.length} transport kaydı modellenmiştir.`:'Transport kapsamı cihaz konfigürasyonundaki arayüz ve tunnel ayarlarından değerlendirilir.'} Aktif control connection bulunması uygulamanın doğru VPN ve transport üzerinden taşındığını tek başına kanıtlamaz.`,`For the selected Cisco cEdge, underlay reachability, control connection/OMP information and tunnel/data-plane state are separate responsibilities. ${transports.length?`${transports.length} transport records are modeled.`:'Transport scope is assessed from configured interface and tunnel settings.'} An active control connection alone does not prove that an application uses the intended VPN and transport.`));
    add(p('WAN transport erişiminin kaybı','WAN transport reachability loss'),p('Kalan transport üzerinden forwarding ancak kullanılabilir tunnel, öğrenilmiş route ve uygun policy varsa devam edebilir. Controller ve circuit ortak bağımlılıkları ayrı değerlendirilir.','Forwarding over a surviving transport requires a usable tunnel, learned route and eligible policy. Review controller and circuit dependencies separately.'),p('Control connection, OMP route, BFD/tunnel durumu ve uygulama trafiğinin gerçek yolu arıza öncesi/sonrası karşılaştırılır.','Compare control connections, OMP routes, BFD/tunnel state and the actual application traffic path before and after failure.'),/sdwan|omp|bfd|tunnel|route|ping/i);
   }
   sections.push({title:`${identity} · ${vendorName(scope.vendor)}`,paragraphs,scenarios});
  }
  if(!sections.length)return null;
  return {title:p('Mühendislik kararlarının işletim etkisi ve kabul planı','Operational impact of engineering decisions and acceptance plan'),introduction:p('Aşağıdaki değerlendirme seçili teknoloji, üretilen konfigürasyon ve modellenmiş bağlantılardan türetilmiştir. Mevcut karar açıklamalarıyla birlikte okunur. Senaryolar kabul planıdır; canlı test sonucu veya ölçülmüş yakınsama süresi içermez.','The assessment below derives from selected technologies, generated configurations and modeled connections. Read it alongside the design decision explanations. Scenarios are acceptance plans; they are not live test results or measured convergence times.'),sections,sources};
 }
 root.NetworkEngineeringReport={build};
})(typeof window==='undefined'?globalThis:window);
