(function(root){
 'use strict';
 const vendor='Huawei iStack',source='https://info.support.huawei.com/network/ptmngsys/Web/tsrev_s/en/content/s/07_Failed_to_Set_Up_a_Stack/edesk_Failed_to_Set_Up_a_Stack_edesk002.html';
 const get=id=>document.getElementById(id)?.value||'',on=id=>!!document.getElementById(id)?.checked;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const field=(id,label,value,type='text')=>`<div><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(value)}"></div>`;
 const count=()=>Math.max(2,Math.min(8,Number(get('isLeafCount'))||4));
 const leaves=()=>Array.from({length:count()},(_,i)=>{const n=i+1;return {id:n,name:get(`isLeaf${n}`),po:get(`isPo${n}`),a:get(`isCore1_${n}`),b:get(`isCore2_${n}`),u1:get(`isUp1_${n}`),u2:get(`isUp2_${n}`)};});
 function sync(){document.querySelectorAll('[data-istack-leaf]').forEach(el=>el.hidden=+el.dataset.istackLeaf>count());document.querySelectorAll('#isOutput option[data-leaf]').forEach(el=>{el.hidden=+el.dataset.leaf>count();el.disabled=el.hidden;});if(/^LEAF/.test(get('isOutput'))&&+get('isOutput').slice(4)>count())document.getElementById('isOutput').value='CORE';}
 function ui(refresh){
  const cards=(title,content)=>`<section class="vpc-v42-card"><div class="vpc-v42-title">${title}</div>${content}</section>`;
  const grid=s=>`<div class="param-grid">${s}</div>`;
  document.getElementById('params').innerHTML=cards('1 · Huawei iStack · Logical Switch & Compatibility',grid(field('isHost','Logical Hostname','CORE-ISTACK')+field('isModel','Product Model','S5720 (service-port stacking)')+field('isRelease','Software Release','V200R023')+'<div><label>Command Profile</label><input value="S series · stack slot / port interface" readonly></div>')+'<p class="vpc-v42-sub">Two physical members, one logical switch. Confirm service-port stacking support for the exact product and release. Member preparation runs separately before the stack is formed.</p>')
  +cards('2 · Members & Stack Interconnect',grid([1,2].map((s,i)=>field(`isName${s}`,`Member-${s} Physical Label`,`CORE-MEMBER-${i}`)+field(`isId${s}`,`Member-${s} Planned ID`,String(i),'number')+field(`isCurrent${s}`,`Member-${s} Current ID (before preparation)`,'0','number')+field(`isPriority${s}`,`Member-${s} Election Priority`,s===1?'200':'100','number')+field(`isLink${s}a`,`Member-${s} Stack-Port 1 Physical Interface`,`XGigabitEthernet${i}/0/27`)+field(`isLink${s}b`,`Member-${s} Stack-Port 2 Physical Interface`,`XGigabitEthernet${i}/0/28`)).join(''))+grid('<div><label>Stack Connection</label><select id="isTopology"><option value="ring">Ring · two independent stack links</option><option value="chain">Chain · one stack link</option></select></div>'+field('isStackSpeed','Stack Link Speed','10G')+field('isMacDelay','Stack MAC Switch Delay (minutes)','10','number')))
  +cards('3 · Multi-Active Detection & Loop Protection','<label class="check"><input type="checkbox" id="isMad" checked> Dedicated direct-mode MAD link</label>'+grid(field('isMad1','Member-1 MAD Interface','GigabitEthernet0/0/24')+field('isMad2','Member-2 MAD Interface','GigabitEthernet1/0/24')+'<div><label>STP Mode</label><select id="isStp"><option value="mstp">MSTP · common instance</option><option value="rstp">RSTP</option></select></div>'+field('isCorePriority','Logical Core STP Priority','4096','number')+field('isLeafPriority','Leaf STP Priority','32768','number'))+'<label class="check"><input type="checkbox" id="isRootGuard" checked> Root protection on core downstream Eth-Trunks</label>')
  +cards('4 · VLANs & Downstream Leaf Connectivity',grid(field('isVlans','Service VLANs','10,20,30')+'<div><label>Trunk Policy</label><select id="isTrunk"><option value="created">Selected service VLANs</option><option value="all">All VLANs</option></select></div><div><label>Leaf Count</label><select id="isLeafCount">'+Array.from({length:7},(_,i)=>`<option ${i===2?'selected':''}>${i+2}</option>`).join('')+'</select></div>')+Array.from({length:8},(_,i)=>{const n=i+1;return `<div data-istack-leaf="${n}">${grid(field(`isLeaf${n}`,`Leaf-${n} Hostname`,`LEAF-${String(n).padStart(2,'0')}`)+field(`isPo${n}`,'Eth-Trunk ID',String(10+n),'number')+field(`isCore1_${n}`,'Member-1 Downstream Interface',`GigabitEthernet0/0/${n}`)+field(`isCore2_${n}`,'Member-2 Downstream Interface',`GigabitEthernet1/0/${n}`)+field(`isUp1_${n}`,'Leaf Uplink to Member-1','GigabitEthernet0/0/1')+field(`isUp2_${n}`,'Leaf Uplink to Member-2','GigabitEthernet0/0/2'))}</div>`;}).join(''))
  +cards('5 · Device Configuration & Preparation',grid('<div><label>Configuration Output</label><select id="isOutput"><option value="CORE">Logical Stack · Complete Design Configuration</option><option value="MEMBER1">Member-1 · Standalone Preparation</option><option value="MEMBER2">Member-2 · Standalone Preparation</option>'+Array.from({length:8},(_,i)=>`<option data-leaf="${i+1}" value="LEAF${i+1}">Leaf-${i+1}</option>`).join('')+'<option value="ALL">All Outputs · Separate Execution Phases</option></select></div>'));
  sync();document.querySelectorAll('#params input,#params select').forEach(el=>{const update=()=>{if(/^isId[12]$/.test(el.id)){const side=+el.id.slice(-1);for(const id of ['isLink'+side+'a','isLink'+side+'b','isMad'+side,...Array.from({length:8},(_,i)=>'isCore'+side+'_'+(i+1))]){const f=document.getElementById(id);f.value=finalPort(side,id);}}sync();refresh();};el.addEventListener('input',update);el.addEventListener('change',update);});
 }
 function validate(){
  const number=(id,min,max)=>{const s=get(id),n=Number(s);if(!s.trim()||!Number.isInteger(n)||n<min||n>max)throw Error(`${id}: expected ${min}–${max}`);return n;};
  for(let s=1;s<=2;s++){number(`isId${s}`,0,8);number(`isCurrent${s}`,0,8);number(`isPriority${s}`,1,255);}
  if(get('isId1')===get('isId2'))throw Error('Stack member IDs must be unique.');
  for(const id of ['isCorePriority','isLeafPriority'])if(number(id,0,61440)%4096)throw Error('STP priority must be a multiple of 4096.');
  number('isMacDelay',0,60);
  for(const id of ['isHost','isName1','isName2',...leaves().map(l=>`isLeaf${l.id}`)])if(!/^[A-Za-z0-9_.-]{1,64}$/.test(get(id)))throw Error('Enter a valid, non-empty hostname or member label.');
  const used=new Set(),trunks=new Set();
  const iface=(x)=>{if(!/^[A-Za-z][A-Za-z0-9-]*\d+\/\d+\/\d+$/.test(x))throw Error('Use a physical interface such as XGigabitEthernet0/0/27.');if(used.has(x.toLowerCase()))throw Error('Physical interface assigned to multiple roles: '+x);used.add(x.toLowerCase());};
  for(let s=1;s<=2;s++){iface(finalPort(s,'isLink'+s+'a'));if(get('isTopology')==='ring')iface(finalPort(s,'isLink'+s+'b'));if(on('isMad'))iface(finalPort(s,'isMad'+s));}
  for(const l of leaves()){iface(finalPort(1,'isCore1_'+l.id));iface(finalPort(2,'isCore2_'+l.id));const id=number(`isPo${l.id}`,1,127);if(trunks.has(id))throw Error('Downstream Eth-Trunk IDs must be unique.');trunks.add(id);if(l.u1===l.u2)throw Error('Leaf uplinks must use distinct physical interfaces.');for(const x of [l.u1,l.u2])if(!/^[A-Za-z][A-Za-z0-9-]*\d+\/\d+\/\d+$/.test(x))throw Error('Enter both leaf uplink interfaces.');}
  const names=leaves().map(l=>l.name);if(new Set(names).size!==names.length||names.includes(get('isHost')))throw Error('Device hostnames must be unique.');
  if(!/^\d+(?:\s*(?:,|-)\s*\d+)*$/.test(get('isVlans'))||!vlans().length)throw Error('Enter valid service VLAN IDs/ranges (1–4094).');
  if(vlans().includes(4093))throw Error('VLAN 4093 is reserved for the selected stack profile; exclude it from service VLANs.');
 }
 function vlans(){return get('isVlans').split(',').flatMap(t=>{const [a,b=a]=t.trim().split('-').map(Number);if(a<1||b>4094||b<a)throw Error('VLAN range must be within 1–4094.');return Array.from({length:b-a+1},(_,i)=>a+i);}).filter((x,i,a)=>a.indexOf(x)===i);}
 const finalPort=(s,id)=>get(id).replace(/(\D)\d+(\/\d+\/\d+)$/,`$1${get('isId'+s)}$2`);
 const localPort=(s,id)=>finalPort(s,id).replace(/(\D)\d+(\/\d+\/\d+)$/,`$1${get('isCurrent'+s)}$2`);
 function stackPorts(s,local=false){const id=get((local?'isCurrent':'isId')+s),port=key=>local?localPort(s,key):finalPort(s,key),ring=get('isTopology')==='ring';return `interface stack-port ${id}/${!ring&&s===2?2:1}\n port interface ${port('isLink'+s+'a')} enable\nquit\n${ring?`interface stack-port ${id}/2\n port interface ${port('isLink'+s+'b')} enable\nquit\n`:''}`;}
 function stackConfiguration(){return '# Stack interconnect design · planned member IDs after formation\n'+[1,2].map(s=>`stack slot ${get('isId'+s)} priority ${get('isPriority'+s)}\n${stackPorts(s)}`).join('');}
 function prepare(s){const cur=get('isCurrent'+s),planned=get('isId'+s);return `# Standalone member-${s} preparation; execute while isolated from the stack.\n# Save and restart only during an approved maintenance window; ID changes take effect after restart.\n# After the stack forms, apply the shared service configuration once to ${get('isHost')}.\nsystem-view\nstack slot ${cur} priority ${get('isPriority'+s)}\n${stackPorts(s,true)}${cur!==planned?`stack slot ${cur} renumber ${planned}\n`:''}return`;}
 function service(leaf,includeStack=true){const id=leaf?leaf.po:null,host=leaf?leaf.name:get('isHost'),priority=get(leaf?'isLeafPriority':'isCorePriority'),allow=get('isTrunk')==='all'?'1 to 4094':vlans().join(' '),items=leaf?[leaf]:leaves();return `# ${leaf?'Leaf':'Shared logical iStack'} service configuration${leaf?'':'; apply once after stack formation'}\nsystem-view\nsysname ${host}\n${!leaf&&includeStack?stackConfiguration():''}vlan batch ${vlans().join(' ')}\nstp mode ${get('isStp')}\nstp enable\nstp priority ${priority}\n${leaf?'':`stack timer mac-address switch-delay ${get('isMacDelay')}\n`}${!leaf&&on('isMad')?[1,2].map(s=>`interface ${finalPort(s,'isMad'+s)}\n mad detect mode direct\nquit\n`).join(''):''}${items.map(l=>`interface Eth-Trunk ${id||l.po}\n description ${leaf?'TO_'+get('isHost'):'TO_'+l.name}\n mode lacp-static\n port link-type trunk\n port trunk allow-pass vlan ${allow}\n${!leaf&&on('isRootGuard')?' stp root-protection\n':''}quit\n${(leaf?[l.u1,l.u2]:[finalPort(1,'isCore1_'+l.id),finalPort(2,'isCore2_'+l.id)]).map(x=>`interface ${x}\n eth-trunk ${id||l.po}\n undo shutdown\nquit`).join('\n')}`).join('\n')}\nreturn`;}
 function commands(){return ['display stack','display stack configuration','display stack current-configuration','display stack port','display stack topology',...(on('isMad')?['display mad']:[]),'display device','display version','display stp brief','display vlan','display port vlan','display interface brief',...leaves().map(l=>'display eth-trunk '+l.po),'display logbuffer'];}
 function decisions(){return [
 {label:'iStack logical control plane',labelTr:'iStack mantıksal kontrol düzlemi',value:`${get('isHost')} · ${get('isModel')} · ${get('isRelease')}`,impact:`Two physical members form one managed switch. Configuration and control-plane state synchronize inside the stack; the shared service configuration is applied once. Member IDs ${get('isId1')} / ${get('isId2')} identify physical port namespaces, not separate routing peers. Product and release compatibility must match the selected S-series command profile.`,impactTr:`İki fiziksel üye tek yönetilen switch oluşturur. Konfigürasyon ve kontrol düzlemi durumu stack içinde eşitlenir; ortak servis konfigürasyonu bir kez uygulanır. ${get('isId1')} / ${get('isId2')} üye kimlikleri fiziksel port ad alanlarını belirtir. Ürün ve sürüm, seçilen S serisi komut profiliyle uyumlu olmalıdır.`},
 {label:'Stack interconnect resilience',labelTr:'Stack bağlantısı dayanıklılığı',value:`${get('isTopology')} · ${get('isStackSpeed')}`,impact:get('isTopology')==='ring'?'Two independent stack paths connect each member’s Stack-Port 1 to the other member’s Stack-Port 2. A single path failure can leave a chain; surviving bandwidth and member reachability must be measured. Stack capacity must accommodate inter-member service traffic and synchronization.':'The selected chain has one stack path; losing that path can split the stack. Direct MAD and residual service capacity must be included in the acceptance tests.',impactTr:get('isTopology')==='ring'?'İki bağımsız stack yolu, her üyenin Stack-Port 1 bağlantısını diğer üyenin Stack-Port 2 bağlantısıyla eşleştirir. Tek yol kaybında yapı zincire dönüşebilir; kalan kapasite ve üyeler arası erişim ölçülmelidir. Stack kapasitesi üyeler arası servis trafiği ve senkronizasyona göre boyutlandırılmalıdır.':'Seçilen zincirde tek stack yolu vardır; yol kaybı stack’i bölebilir. Doğrudan MAD ve kalan servis kapasitesi kabul testlerine dahil edilmelidir.'},
 {label:'Election and multi-active containment',labelTr:'Rol seçimi ve çoklu aktif durumun sınırlandırılması',value:`Priorities ${get('isPriority1')} / ${get('isPriority2')} · MAD ${on('isMad')?'enabled':'disabled'}`,impact:`Higher stack priority influences master election but does not guarantee the operational role when startup state differs. ${on('isMad')?'A dedicated direct MAD link is reserved for split detection; it must remain separate from service trunks and stack failure paths.':'MAD is not configured; a split may leave independently active partitions and requires a documented protection decision.'} MAC switch delay ${get('isMacDelay')} minutes controls stack MAC persistence after master change and must be tested against convergence targets.`,impactTr:`Yüksek stack önceliği master seçimini etkiler; farklı başlangıç durumlarında işletim rolünü garanti etmez. ${on('isMad')?'Ayrılmış doğrudan MAD bağlantısı bölünme algılaması için kullanılır; servis trunk’larından ve stack hata yollarından ayrı tutulmalıdır.':'MAD konfigüre edilmemiştir; bölünme bağımsız aktif parçalar oluşturabilir ve koruma kararı belgelenmelidir.'} ${get('isMacDelay')} dakikalık MAC değişim gecikmesi master değişiminden sonra stack MAC adresinin korunmasını düzenler; yakınsama hedefleriyle test edilmelidir.`},
 {label:'Cross-member access and loop control',labelTr:'Üyeler arası erişim ve döngü kontrolü',value:`${count()} leaves · LACP · ${get('isStp')}`,impact:`Each leaf uses one Eth-Trunk with one physical member on each stack chassis. A chassis failure preserves the remaining path only when LACP membership, permitted VLANs and forwarding state are consistent. STP priorities ${get('isCorePriority')} / ${get('isLeafPriority')} express the intended core/root hierarchy; root protection applies to downstream core trunks. MSTP uses the common instance unless a separate region/instance design is supplied.`,impactTr:`Her leaf, her stack şasisinde bir fiziksel üyeye sahip tek Eth-Trunk kullanır. Şasi kaybında kalan yolun çalışması LACP üyeliği, izin verilen VLAN’lar ve iletim durumunun tutarlılığına bağlıdır. ${get('isCorePriority')} / ${get('isLeafPriority')} STP öncelikleri core/root hiyerarşisini ifade eder; root koruması core’un downstream trunk’larına uygulanır. Ayrı region/instance tasarımı yoksa MSTP ortak instance üzerinden çalışır.`}
 ].map(p=>({...p,valueTr:p.value.replace(/^Priorities /,'Öncelikler ').replace('MAD enabled','MAD etkin').replace('MAD disabled','MAD devre dışı').replace(/^ring /,'halka ').replace(/^chain /,'zincir ').replace(' leaves',' leaf')}));}
 function generate(tab){if(tab==='verify')return commands().join('\n');if(tab==='config')validate();if(tab==='notes')return 'Huawei iStack engineering design\n'+decisions().map(x=>x.impact).join('\n');if(tab==='trouble')return 'Verify planned member IDs and roles with display stack. Compare stack port/topology state, direct MAD and Eth-Trunk forwarding. Isolate stack split and ordinary link failures before recovery.';const out=get('isOutput');if(out==='CORE')return service(null,tab!=='deploy');if(/^MEMBER/.test(out))return prepare(+out.slice(6));if(/^LEAF/.test(out))return service(leaves()[+out.slice(4)-1]);return [1,2].map(s=>`######## ${get('isName'+s)} · STANDALONE PREPARATION ########\n${prepare(s)}`).concat(`######## ${get('isHost')} · SHARED LOGICAL CONFIGURATION ########\n${service()}`,leaves().map(l=>`######## ${l.name} ########\n${service(l)}`)).join('\n\n');}
 function topology(){const node=(x,y,name,sub,w=190)=>`<g><rect class="vpc-device" x="${x-w/2}" y="${y}" width="${w}" height="65" rx="12"/><text class="vpc-device-name" x="${x}" y="${y+25}" text-anchor="middle">${esc(name)}</text><text class="vpc-small" x="${x}" y="${y+48}" text-anchor="middle">${esc(sub)}</text></g>`;return `<div class="vpc-svg-wrap"><svg class="vpc-svg" viewBox="0 0 950 540" role="img" aria-label="Huawei iStack physical member and leaf topology"><text class="vpc-domain-title" x="475" y="30" text-anchor="middle">HUAWEI iStack · ${esc(get('isHost'))}</text><rect class="vpc-domain-box" x="165" y="70" width="620" height="155" rx="15"/><text class="vpc-small" x="475" y="92" text-anchor="middle">Single logical switch · ${esc(get('isModel'))}</text><line class="vpc-peer-line" x1="395" y1="145" x2="555" y2="145"/>${get('isTopology')==='ring'?'<line class="vpc-peer-line" x1="395" y1="161" x2="555" y2="161"/>':''}<text class="vpc-peer-title" x="475" y="128" text-anchor="middle">${esc(get('isTopology'))} · ${esc(get('isStackSpeed'))}</text>${node(300,110,get('isName1'),'Member '+get('isId1')+' · priority '+get('isPriority1'))}${node(650,110,get('isName2'),'Member '+get('isId2')+' · priority '+get('isPriority2'))}${on('isMad')?'<line class="vpc-ka-line" x1="300" y1="195" x2="650" y2="195"/><text class="vpc-peer-title" x="475" y="213" text-anchor="middle">Dedicated direct MAD</text>':''}${leaves().map((l,i)=>{const x=85+780*i/(count()-1);return `<line class="vpc-member-line" x1="300" y1="175" x2="${x}" y2="360"/><line class="vpc-member-line" x1="650" y1="175" x2="${x}" y2="360"/>${node(x,360,l.name,'Eth-Trunk '+l.po,95)}<text class="vpc-small" x="${x}" y="444" text-anchor="middle">${esc(get('designUplinkSpeed'))}</text>`;}).join('')}<text class="vpc-small" x="475" y="500" text-anchor="middle">Cross-member LACP · ${esc(get('isStp'))} · VLAN ${esc(get('isVlans'))}</text></svg></div>`;}
 root.HuaweiIStack={vendor,source,ui,sync,count,leaves,generate,commands,decisions,topology,service,prepare,stackPorts,stackConfiguration,validate,finalPort};
})(typeof window==='undefined'?globalThis:window);
