(function(){
'use strict';
const reportPage=!!document.getElementById('reportLanguage'),contextKey='networkConfigurator.library.context';
let available=false,username='',offset=0,total=0,busy=false;
const read=key=>{try{return JSON.parse(sessionStorage.getItem(key)||'null');}catch{return null;}};
const clean=value=>Array.isArray(value)?value.map(clean):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([key])=>!/password|passwd|secret|token|private.?key|credential/i.test(key)).map(([key,v])=>[key,clean(v)])):value;
const context=()=>{const c=read(contextKey);return c?.username===username?c:null;};
const reset=()=>sessionStorage.removeItem(contextKey);
const panel=document.createElement('div');panel.className='nc-library-modal';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','ncLibraryTitle');
panel.innerHTML='<section class="nc-library-card"><header><div><span class="nc-flow-kicker">PROJECT WORKSPACE</span><h2 id="ncLibraryTitle">Project Library</h2></div><button type="button" data-library-close aria-label="Close Project Library">×</button></header><p class="nc-library-status" role="status" aria-live="polite"></p><div class="nc-library-save"><label>Project name<input id="ncLibraryName" maxlength="120" placeholder="Enter project name"></label><label>Revision note<input id="ncLibraryNote" maxlength="500" placeholder="Describe this saved version"></label><div class="nc-library-actions"><button type="button" data-library-save>Save</button><button type="button" data-library-revision>Create revision</button><button type="button" data-library-copy>Save as new project</button><button type="button" data-library-export>Export full project</button><label class="nc-library-file">Open full project<input type="file" accept=".json,application/json" data-library-file hidden></label></div></div><p class="nc-library-help">Save updates the current revision. Create revision preserves the previous revision and starts the next one. Delete removes the project and its entire saved history.</p><div class="nc-library-toolbar"><label>Search project name<input type="search" id="ncLibrarySearch" placeholder="Search saved projects"></label><button type="button" data-library-refresh>Refresh</button></div><div class="nc-library-results"></div><div class="nc-library-pagination"><button type="button" data-library-prev>Previous</button><span data-library-page></span><button type="button" data-library-next>Next</button></div><details class="nc-library-local"><summary>Existing browser projects · import without deleting local copies</summary><div data-library-local></div></details><section class="nc-library-history" hidden><h3>Revision history</h3><div data-library-history></div></section></section>';
document.body.append(panel);
const $=selector=>panel.querySelector(selector),status=(message,error=false)=>{const node=$('.nc-library-status');node.textContent=message;node.classList.toggle('error',error);};
let previousFocus;
function close(){panel.hidden=true;previousFocus?.focus();}
function show(){previousFocus=document.activeElement;panel.hidden=false;const bundle=collect();$('#ncLibraryName').value=bundle.name;$('#ncLibraryNote').value='';$('#ncLibraryName').focus();refresh();}
$('[data-library-close]').onclick=close;panel.onclick=e=>{if(e.target===panel)close();};
document.addEventListener('keydown',e=>{if(panel.hidden)return;if(e.key==='Escape')close();if(e.key==='Tab'){const items=[...panel.querySelectorAll('button,input,a,summary')].filter(el=>!el.disabled&&!el.hidden&&el.getClientRects().length);if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
async function api(path,options){const r=await fetch(path,options);let data;try{data=await r.json();}catch{throw Error('Unable to read the project service response.');}if(!r.ok){const error=Error(typeof data.detail==='string'?data.detail:'Project request failed.');error.status=r.status;throw error;}return data;}
function collect(designOverride){
 const design=designOverride||window.NetworkWorkspaceProject?.snapshot()||read('networkConfigurator.workflow.design');
 let report=window.NetworkReportProject?.snapshot()||read('networkConfigurator.report.current');
 if(design&&report?.source?.projectId&&report.source.projectId!==(design.project?.id||'active'))report=null;
 const nativeName=reportPage?report?.name:design?.project?.name;
 const name=nativeName&&nativeName!=='Untitled Network Project'?nativeName:report?.name||'';
 return clean({schema:'network-configurator-project-v1',name,design:design||null,reporting:report||null});
}
function named(document){const name=$('#ncLibraryName').value.trim()||document.name;if(!name||name==='Untitled Network Project')throw Error('Enter a project name before saving.');document.name=name;if(document.design?.project)document.design.project.name=name;if(document.reporting)document.reporting.name=name;return document;}
function setContext(record){sessionStorage.setItem(contextKey,JSON.stringify({id:record.id,version:record.version,updated_at:record.updated_at,username}));}
async function persist(document,{copy=false,note='',activate=true,createRevision=false}={}){
 const current=copy?null:context();const result=await api('/api/projects'+(current?'/'+current.id:''),{method:current?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:clean(document),version:current?.version,expected_updated_at:current?.updated_at,create_revision:createRevision,note})});
 if(activate)setContext(result);return result;
}
function controls(){panel.querySelectorAll('[data-library-save],[data-library-revision],[data-library-copy],[data-library-local] button').forEach(button=>button.disabled=busy||!available);}
async function save(copy=false,designOverride,createRevision=false){
 if(!available)throw Error('Connect a PostgreSQL database before saving to the Library. File export remains available.');
 if(busy)return;
 busy=true;controls();try{const document=named(collect(designOverride)),result=await persist(document,{copy,createRevision,note:$('#ncLibraryNote').value.trim()||(reportPage?'Saved from Maintenance and Reporting':'Saved from Network Design')});status('Saved '+result.name+' · revision '+result.version+'.');if(!panel.hidden)await list();return result;}catch(error){status(error.message,true);if(error.status===409)status(error.message+' Your current work is unchanged; use Save as new project to keep a separate copy.',true);throw error;}finally{busy=false;controls();}
}
$('[data-library-save]').onclick=()=>save().catch(()=>{});$('[data-library-revision]').onclick=()=>save(false,undefined,true).catch(()=>{});$('[data-library-copy]').onclick=()=>save(true).catch(()=>{});
function exportFile(designOverride){const document=named(collect(designOverride));const blob=new Blob([JSON.stringify(document,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=window.document.createElement('a');link.href=url;link.download=document.name.replace(/[^a-z0-9_-]+/gi,'_')+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Full project exported: design, inventory and reporting data.');}
$('[data-library-export]').onclick=()=>{try{exportFile();}catch(error){status(error.message,true);}};
function restore(document,{destination,workingCopy=false}={}){
 if(document.schema!=='network-configurator-project-v1'||(!document.design&&!document.reporting))throw Error('Unsupported full project document.');
 document=clean(document);
 for(const key of Object.keys(sessionStorage)){if(key.startsWith("networkConfigurator.report.edit."))sessionStorage.removeItem(key);}
 if(document.design?.project)document.design.project.name=document.name;if(document.reporting)document.reporting.name=document.name;
 if(workingCopy){reset();const id='p_'+(crypto.randomUUID?crypto.randomUUID():Date.now());if(document.design?.project)document.design.project.id=id;if(document.reporting?.source)document.reporting.source.projectId=id;}
 if(document.design)sessionStorage.setItem('networkConfigurator.workflow.design',JSON.stringify(document.design));else sessionStorage.removeItem('networkConfigurator.workflow.design');
 if(document.reporting){sessionStorage.setItem('networkConfigurator.report.current',JSON.stringify(document.reporting));sessionStorage.setItem('networkConfigurator.report.import',JSON.stringify(document.reporting));}else{sessionStorage.removeItem('networkConfigurator.report.current');sessionStorage.removeItem('networkConfigurator.report.import');}
 destination=destination||(document.design?'design':'report');
 if(destination==='design'&&document.design&&window.NetworkWorkspaceProject){window.NetworkWorkspaceProject.apply(document.design);close();}
 else if(destination==='report'&&document.reporting&&window.NetworkReportProject){window.NetworkReportProject.apply(document.reporting);sessionStorage.removeItem('networkConfigurator.report.import');close();}
 else location.assign(destination==='design'&&document.design?'/?resume=1':'/reporting?view=design');
}
async function open(id,destination){try{const record=await api('/api/projects/'+id);setContext(record);restore(record.document,{destination});}catch(error){status(error.message,true);}}
function action(label,handler){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=handler;return b;}
function card(record){const row=document.createElement('article');row.className='nc-library-row';const content=document.createElement('div'),name=document.createElement('strong'),detail=document.createElement('small');name.textContent=record.name;detail.textContent=[(record.modules||[]).join(' / '),(record.vendors||[]).join(' / '),'Revision '+record.version,new Date(record.updated_at).toLocaleString(),(record.inventory_count||0)+' inventory records',Math.ceil((record.document_bytes||0)/1024)+' KB'].filter(Boolean).join(' · ');content.append(name,detail);const actions=document.createElement('div');actions.className='nc-library-actions';if(record.has_design)actions.append(action('Open design',()=>open(record.id,'design')));if(record.has_reporting)actions.append(action('Open report',()=>open(record.id,'report')));actions.append(action('Duplicate',async()=>{try{const source=await api('/api/projects/'+record.id);source.document.name=(source.document.name+' — copy').slice(0,120);if(source.document.design?.project)source.document.design.project.name=source.document.name;if(source.document.reporting)source.document.reporting.name=source.document.name;await persist(source.document,{copy:true,note:'Duplicated project',activate:false});await list();status('Copy saved; source project preserved.');}catch(error){status(error.message,true);}}),action('History',()=>history(record)),action('Delete',()=>remove(record)));row.append(content,actions);return row;}
async function remove(record){
 if(!confirm('Are you sure you want to permanently delete "'+record.name+'" and ALL its revisions? This cannot be undone.'))return;
 try{await api('/api/projects/'+record.id,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true,expected_updated_at:record.updated_at})});if(context()?.id===record.id)reset();$('.nc-library-history').hidden=true;offset=0;await list();status('Project and all saved revisions deleted. Current on-screen work and downloaded files are retained.');}catch(error){status(error.message,true);}
}
async function history(record){try{const data=await api('/api/projects/'+record.id+'/revisions'),section=$('.nc-library-history'),root=$('[data-library-history]');section.hidden=false;root.replaceChildren();for(const revision of data.revisions){const row=document.createElement('div');row.className='nc-library-row';const text=document.createElement('span');text.textContent='Revision '+revision.revision+' · '+new Date(revision.created_at).toLocaleString()+' · '+revision.note;row.append(text,action('Open as working copy',async()=>{try{const old=await api('/api/projects/'+record.id+'/revisions/'+revision.revision);old.document.name=(old.document.name+' · revision '+revision.revision).slice(0,120);restore(old.document,{workingCopy:true});}catch(error){status(error.message,true);}}));if(revision.revision<data.current_revision)row.append(action('Delete revision',async()=>{if(!confirm('Are you sure you want to permanently delete Revision '+revision.revision+' of "'+record.name+'"? The current revision will be kept.'))return;try{await api('/api/projects/'+record.id+'/revisions/'+revision.revision,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true})});await history(record);status('Revision '+revision.revision+' deleted. Current revision retained.');}catch(error){status(error.message,true);}}));else{const badge=document.createElement('small');badge.textContent='Current revision · protected';row.append(badge);}root.append(row);}section.scrollIntoView({behavior:'smooth',block:'nearest'});}catch(error){status(error.message,true);}}
async function list(){const data=await api('/api/projects?q='+encodeURIComponent($('#ncLibrarySearch').value.trim())+'&offset='+offset);total=data.total;const root=$('.nc-library-results');root.replaceChildren();data.projects.forEach(record=>root.append(card(record)));if(!data.projects.length)root.textContent='No matching saved projects.';$('[data-library-page]').textContent=total?(offset+1)+'–'+Math.min(offset+50,total)+' of '+total:'0 projects';$('[data-library-prev]').disabled=offset===0;$('[data-library-next]').disabled=offset+50>=total;}
function localProjects(){const root=$('[data-library-local]');root.replaceChildren();let saved={};try{saved=JSON.parse(localStorage.getItem('networkConfigurator.v3.projects')||'{}');}catch{}for(const design of Object.values(saved)){if(design?.schema!=='network-configurator-v3')continue;const row=document.createElement('div');row.className='nc-library-row';const label=document.createElement('span');label.textContent=design.project?.name||'Untitled project';row.append(label,action('Import to Library',async()=>{try{const document=collect(design);document.name=design.project?.name||'';if(!document.name)throw Error('Open this project and enter a name before import.');await persist(document,{copy:true,note:'Imported from browser storage',activate:false});await list();status('Imported '+document.name+'. Local copy retained.');}catch(error){status(error.message,true);}}));root.append(row);}if(!root.children.length)root.textContent='No browser projects to import.';controls();}
async function refresh(){status('Checking project storage…');try{const data=await api('/api/projects/status');available=!!data.available;window.NetworkProjects.available=available;if(!available){$('.nc-library-results').textContent='Database storage is not connected. Existing workspaces and project files remain available.';status(data.configured?'Database connection unavailable. Retry after checking the server connection.':'Database not configured. Add DATABASE_URL in Render to enable persistent project storage.');$('[data-library-prev]').disabled=true;$('[data-library-next]').disabled=true;}else{await list();status('PostgreSQL storage connected · projects are scoped to the signed-in account.');}}catch(error){available=false;window.NetworkProjects.available=false;status(error.message,true);}localProjects();controls();}
$('[data-library-refresh]').onclick=refresh;let timer;$('#ncLibrarySearch').oninput=()=>{offset=0;clearTimeout(timer);timer=setTimeout(()=>{if(available)list().catch(error=>status(error.message,true));},250);};$('[data-library-prev]').onclick=()=>{offset=Math.max(0,offset-50);list().catch(error=>status(error.message,true));};$('[data-library-next]').onclick=()=>{offset+=50;list().catch(error=>status(error.message,true));};
$('[data-library-file]').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>16*1024*1024)throw Error('Project file exceeds the 16 MB import limit.');restore(JSON.parse(await file.text()),{workingCopy:true});}catch(error){status(error.message,true);}finally{e.target.value='';}};
window.NetworkProjects={available:false,show,save,saveCurrent:async design=>{await initialization;if(!available)await refresh();$('#ncLibraryName').value=collect(design).name;$('#ncLibraryNote').value='';return save(false,design);},downloadCurrent:design=>{$('#ncLibraryName').value=collect(design).name;exportFile(design);},collect,reset,openFile:document=>restore(document,{workingCopy:true})};
const group=document.querySelector('[data-nc-group="projects"]>div');if(group){const link=document.createElement('a');link.className='nc-nav-item nc-nav-sub';link.href='#project-library';link.textContent='Project Library';link.onclick=e=>{e.preventDefault();show();};group.prepend(link);}
const header=document.querySelector(reportPage?'.shell>.nav':'.v3-topbar');if(header){const button=action('Project Library',show);button.className='nc-signout';button.setAttribute('aria-haspopup','dialog');header.append(button);}
const initialization=fetch('/auth/status').then(r=>r.json()).then(s=>{username=s.username||'local-development';if(read(contextKey)?.username!==username)reset();return api('/api/projects/status');}).then(s=>{available=!!s.available;window.NetworkProjects.available=available;}).catch(()=>{});
})();
