const fs=require('fs'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{JSDOM,VirtualConsole}=require('jsdom');
function parse(sources){return JSON.parse(execFileSync('python',['-c','import json,sys;from network_discovery import build_graph;from discovery_details import enrich_graph;s=json.load(sys.stdin);print(json.dumps(enrich_graph(build_graph(s),s)))'],{input:JSON.stringify(sources),encoding:'utf8'}));}
const local={platform:'Cisco IOS-XE',protocol:'lldp',deviceName:'CORE',target:'192.0.2.10',origin:'CLI import',observedAt:'2026-10-09T08:00:00Z',output:'Local Intf: Gi1/0/1\nChassis id: aa11\nPort id: 10GE1/0/1\nSystem Name: LEAF\nSystem Description: Huawei CloudEngine\nManagement address: 192.0.2.11'};
const leaf={platform:'Huawei_CE_SW',protocol:'lldp',deviceName:'LEAF',target:'192.0.2.11',origin:'SSH inventory / neighbors',discoveryDepth:1,observedAt:'2026-10-09T08:05:00Z',output:'10GE1/0/2 has 1 neighbor(s):\nChassis ID: bb22\nPort ID: Ethernet1\nSystem name: ACCESS\nSystem description: Arista EOS\nManagement address value: 192.0.2.12'};
(async()=>{let calls=[],report;const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(fs.readFileSync('network-discovery.html','utf8'),{url:'https://test.invalid/network-discovery',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.confirm=()=>true;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};w.fetch=async(url,opts)=>{const p=JSON.parse(opts.body);calls.push({url,p});if(url==='/api/discovery/parse')return {ok:true,json:async()=>({graph:parse(p.sources),sources:p.sources})};if(url==='/api/discovery/collect')return {ok:true,json:async()=>({sources:[{...leaf,discoveryDepth:p.discoveryDepth}],warnings:[]})};if(url==='/api/device/test')return {ok:true,json:async()=>({steps:[{status:'PASS'}]})};report=p;return {ok:true,blob:async()=>new w.Blob(['test'])};};}});
const w=dom.window,d=w.document;w.eval(fs.readFileSync('network-discovery.js','utf8'));
try{
 w.NetworkDiscovery.restore({project:{name:'Brownfield test'},networkDiscovery:{schema:'network-discovery-v1',sources:[local],graph:parse([local]),positions:{}}});
 assert.equal(calls.length,0,'Rendering must never connect automatically');assert.match(d.getElementById('discoveryNeighbors').textContent,/LEAF/);
 d.getElementById('discoveryNeighborAll').click();d.getElementById('discoveryNeighborAdd').click();assert.equal(calls.length,0);assert.equal(d.querySelectorAll('#discoverySeeds tr').length,1);assert.equal(d.querySelector('#discoverySeeds input[type=text]').value,'192.0.2.11');assert.match(d.getElementById('discoveryNeighbors').textContent,/Already in SSH queue/);
 const inputs=d.querySelectorAll('#discoverySeeds input[type=text]');inputs[1].value='tester';inputs[1].dispatchEvent(new w.Event('input'));const password=d.querySelector('#discoverySeeds input[type=password]');password.value='transient-password';password.dispatchEvent(new w.Event('input'));
 d.getElementById('discoveryDetailsEnabled').checked=true;await d.getElementById('discoveryRun').onclick();
 const collect=calls.find(x=>x.url==='/api/discovery/collect');assert.equal(collect.p.target,'192.0.2.11');assert.equal(collect.p.includeDetails,true);assert.equal(collect.p.discoveryDepth,1);assert.match(d.getElementById('discoveryNeighbors').textContent,/Outside selected discovery depth/);assert.ok(!JSON.stringify(w.NetworkDiscovery.snapshot()).includes('transient-password'));
 d.getElementById('discoveryDepth').value='2';d.getElementById('discoveryDepth').dispatchEvent(new w.Event('change'));assert.match(d.getElementById('discoveryNeighbors').textContent,/Ready to add/);
 const core=w.NetworkDiscovery.snapshot().graph.devices.find(x=>x.hostname==='CORE');d.getElementById('discoveryDetailDevice').value=core.id;d.getElementById('discoveryDetailDevice').dispatchEvent(new w.Event('change'));d.getElementById('discoveryDetailCommand').value='show interfaces status';d.getElementById('discoveryDetailOutput').value='Gi1/0/1 To Leaf connected 20 full 100G 100Gbase';await d.getElementById('discoveryDetailImport').onclick();
 d.querySelector('#discoveryMap [data-link]').dispatchEvent(new w.MouseEvent('click'));assert.match(d.getElementById('discoveryInspector').textContent,/Observed speed: 100G/);assert.match(d.getElementById('discoveryInspector').textContent,/Description: To Leaf/);assert.match(d.getElementById('discoveryLinks').textContent,/20/);
 d.getElementById('discoveryDetailCommand').value='show etherchannel summary';d.getElementById('discoveryDetailOutput').value='1 Po7(SU) LACP Gi1/0/1(P)';await d.getElementById('discoveryDetailImport').onclick();assert.match(d.getElementById('discoveryLinks').textContent,/Po7/);
 d.getElementById('discoveryReportEngineer').value='Engineer';await d.getElementById('discoveryReportWord').onclick();assert.equal(report.name,'Brownfield test');assert.equal(report.sources.length,2);assert.ok(!JSON.stringify(report).includes('transient-password'));assert.ok(!('inventoryDeviceIds' in report));assert.equal(report.language,'en');
 const saved=JSON.parse(JSON.stringify(w.NetworkWorkspaceProject.snapshot()));w.NetworkDiscovery.restore(saved);assert.equal(w.NetworkDiscovery.snapshot().graph.links[0].aDetails?.speed||w.NetworkDiscovery.snapshot().graph.links[0].bDetails?.speed,'100G');
 for(let i=0;i<20;i++)d.getElementById('discoveryAddSeed').click();d.getElementById('discoveryDepth').value='2';d.getElementById('discoveryDepth').dispatchEvent(new w.Event('change'));d.getElementById('discoveryNeighborAll').click();d.getElementById('discoveryNeighborAdd').click();assert.match(d.getElementById('discoveryStatus').textContent,/limited to 20 devices/);assert.equal(d.querySelectorAll('#discoverySeeds tr').length,20);const beforeRemoval=JSON.stringify(w.NetworkDiscovery.snapshot());d.getElementById('discoveryRemoveSeed').click();assert.equal(d.querySelectorAll('#discoverySeeds tr').length,0);assert.equal(JSON.stringify(w.NetworkDiscovery.snapshot()),beforeRemoval,'Removing SSH targets must retain collected topology');assert.equal(d.getElementById('discoveryRemoveSeed').disabled,true);
 d.getElementById('discoveryClearMap').click();assert.equal(d.getElementById('discoveryDetailOutput').value,'');assert.equal(d.querySelectorAll('#discoveryNeighbors input').length,0);assert.deepEqual(errors,[]);
 console.log('Selected neighbor expansion, depth limits, no implicit SSH, interface imports, report isolation, credential exclusion and reset passed.');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
