const fs=require('fs'),assert=require('assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM('<div id="troubleshootingPanel"><div class="simple-deploy-head">Header</div><input id="troubleTarget" value="CE-1"><div id="troubleCommandGroups"><div class="verify-command"><input class="verify-command-editor" value="show ip route 10.1.1.1"><input class="verify-select" type="checkbox" checked></div></div></div>',{runScripts:'dangerously',url:'https://test.invalid',virtualConsole:vc});
const w=dom.window,d=w.document;let moduleKey='BGP',platform='Cisco IOS-XE',run=null;w.NetworkWorkspaceProject={diagnosticScope:()=>({module:moduleKey,platform}),diagnosticDesign:()=>({devices:[{id:'a',hostname:'CE-1'},{id:'b',hostname:'ISP-1'}],links:[{a:'a',b:'b',aPort:'Gi1',bPort:'Gi2',speed:'10G'}]}),diagnosticResult:()=>run};w.confirm=()=>true;w.HTMLElement.prototype.scrollIntoView=()=>{};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};w.eval(fs.readFileSync('path-diagnostics.js','utf8'));
function input(id,value){d.getElementById(id).value=value;d.getElementById(id).dispatchEvent(new w.Event('input'));}
const click=id=>d.getElementById(id).click();
try{
 click('pdLaunch');assert.equal(d.getElementById('pathDiagnostics').open,true);click('pdStart');assert.ok(d.getElementById('pdPlan').textContent.includes('CE-1'));assert.ok(d.getElementById('pdPlan').textContent.includes('10G'));
 input('pdFlow_source','10.1.1.1');input('pdFlow_destination','10.2.2.2');input('pdFlow_vrf','PROD');input('pdFlow_destinationPort','443');click('pdCommands');assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,1);
 const out=d.querySelector('#pdEvidence textarea');out.value='<script>bad()</script>\nObserved next hop 192.0.2.1';out.dispatchEvent(new w.Event('input'));assert.equal(w.bad,undefined);assert.ok(w.NetworkPathDiagnostics.summary().includes('192.0.2.1'));assert.ok(!d.querySelector('#pdEvidence script'));
 click('pdAddHop');assert.equal(w.NetworkPathDiagnostics.snapshot().hops[0].status,'Not collected');assert.ok(!w.NetworkPathDiagnostics.summary().includes('0% loss'));
 run={module:moduleKey,platform,target:'CE-1',observedAt:'2026-10-06T16:00:00Z',results:[{command:'show ip route 10.1.1.1',output:'Connected',ok:true}],mock:false};click('pdCapture');assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,2,'preserve manually entered output');click('pdCapture');assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,2,'repeat attach idempotent');
 const saved=w.NetworkPathDiagnostics.snapshot();w.NetworkPathDiagnostics.restore(null);assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,0);assert.equal(d.getElementById('pdFlow_source').value,'');w.NetworkPathDiagnostics.restore(saved);assert.equal(d.getElementById('pdFlow_source').value,'10.1.1.1');assert.equal(d.querySelectorAll('#pdEvidence textarea').length,2);
 moduleKey='OSPF';platform='Huawei_CE_SW';input('pdFlow_name','A');assert.ok(d.getElementById('pdStatus').textContent.includes('Workspace changed'));run={...run,module:moduleKey,platform};click('pdCapture');assert.ok(d.getElementById('pdStatus').textContent.includes('different module'));assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,2);
 w.confirm=()=>false;click('pdStart');assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,2);w.confirm=()=>true;click('pdStart');assert.equal(w.NetworkPathDiagnostics.snapshot().scope.platform,'Huawei_CE_SW');assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,0);click('pdAddEvidence');assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,1);d.querySelector('#pdEvidence button').click();assert.equal(w.NetworkPathDiagnostics.snapshot().evidence.length,0);
 click('pdExport');click('pdText');assert.deepEqual(errors,[]);console.log('Path Diagnostics: flow context, separate planned links, per-command editing, evidence capture, scope isolation, roundtrip and exports passed');
}finally{w.close();}
