const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
(async()=>{
 const dom=new JSDOM('<div class="v3-topbar"></div><section data-nc-group="projects"><div></div></section>',{url:'https://example.test/',runScripts:'outside-only'}),w=dom.window;
 const design={schema:'network-configurator-v3',project:{id:'p_lab',name:'Synthetic lab'},workspace:{platform:'Cisco NX-OS',technology:'VPC'},fields:{sshPassword:'synthetic-only'}};
 const report={schema:'network-configurator-report-v1',name:'Synthetic lab',vendor:'Cisco NX-OS',links:[],source:{projectId:'p_lab'},devices:[{id:'lab1',hostname:'LAB-1'}],inventoryDeviceIds:['lab1']};
 w.NetworkWorkspaceProject={snapshot:()=>JSON.parse(JSON.stringify(design)),apply:d=>{w.applied=d;Object.assign(design,JSON.parse(JSON.stringify(d)));},rename:name=>{design.project.name=name;}};
 w.sessionStorage.setItem('networkConfigurator.report.current',JSON.stringify(report));
 let saved,requests=[],rows=[],revisionRows=[{revision:2,created_at:'2026-10-06',note:'current'},{revision:1,created_at:'2026-10-05',note:'old'}];w.HTMLElement.prototype.scrollIntoView=()=>{};
 w.fetch=async(url,options={})=>{requests.push({url,options});let data;if(url==='/auth/status')data={username:'engineer'};else if(url==='/api/projects/status')data={available:true,configured:true};else if(options.method==='POST'||options.method==='PUT'){saved=JSON.parse(options.body);data={id:'123',version:saved.create_revision?2:1,updated_at:'synthetic-stamp',name:saved.document.name};}else if(options.method==='DELETE'){if(url.includes('/revisions/'))revisionRows=revisionRows.filter(r=>r.revision!==1);else rows=[];data={deleted:true};}else if(url==='/api/projects/123')data={id:'123',version:2,updated_at:'synthetic-stamp',document:JSON.parse(JSON.stringify(saved.document))};else if(url.endsWith('/revisions'))data={current_revision:2,revisions:revisionRows};else data={projects:rows,total:rows.length};return {ok:true,json:async()=>data};};
 w.eval(fs.readFileSync('project-library.js','utf8'));await new Promise(r=>setTimeout(r,15));
 assert.equal(w.NetworkProjects.available,true);w.NetworkProjects.show();await new Promise(r=>setTimeout(r,15));
 w.document.querySelector('#ncLibraryName').value='Saved synthetic lab';await w.NetworkProjects.save();
 assert.equal(saved.document.name,'Saved synthetic lab');assert.equal(saved.document.reporting.name,'Saved synthetic lab');assert.equal(saved.document.design.fields.sshPassword,undefined);assert.equal(saved.document.reporting.inventoryDeviceIds[0],'lab1');
 await w.NetworkProjects.save();assert.equal(requests.at(-2)?.options.method==='PUT'||requests.some(r=>r.options.method==='PUT'),true);
 await w.NetworkProjects.saveCurrent();assert.equal(saved.document.name,'Saved synthetic lab');
 assert.equal(saved.create_revision,false);assert.equal(saved.expected_updated_at,'synthetic-stamp');
 w.document.querySelector('[data-library-revision]').click();await new Promise(r=>setTimeout(r,15));assert.equal(saved.create_revision,true);
 rows=[{id:'123',name:'Saved synthetic lab',version:2,updated_at:'synthetic-stamp',has_design:true}];
 await w.document.querySelector('[data-library-refresh]').onclick();
 const beforeCopy=w.sessionStorage.getItem('networkConfigurator.library.context');const priorId=design.project.id;
 const duplicate=[...w.document.querySelectorAll('.nc-library-results button')].find(b=>b.textContent==='Duplicate');duplicate.click();await new Promise(r=>setTimeout(r,15));assert.notEqual(saved.document.design.project.id,priorId);assert.equal(saved.document.reporting.source.projectId,saved.document.design.project.id);assert.equal(w.sessionStorage.getItem('networkConfigurator.library.context'),beforeCopy);assert.equal(design.project.id,priorId);
 w.document.querySelector('[data-library-copy]').click();await new Promise(r=>setTimeout(r,15));assert.notEqual(design.project.id,priorId);assert.equal(design.project.id,saved.document.design.project.id);assert.equal(saved.document.reporting.source.projectId,design.project.id);await w.NetworkProjects.saveCurrent();assert.ok(saved.document.reporting,'Subsequent saves retain the report of the copied project');
 const historyButton=[...w.document.querySelectorAll('.nc-library-results button')].find(b=>b.textContent==='History');historyButton.click();await new Promise(r=>setTimeout(r,15));
 const revisionButtons=[...w.document.querySelectorAll('[data-library-history] button')].filter(b=>b.textContent==='Delete revision');assert.equal(revisionButtons.length,1);assert.ok(w.document.querySelector('[data-library-history]').textContent.includes('Current revision · protected'));
 w.confirm=()=>false;revisionButtons[0].click();await new Promise(r=>setTimeout(r,10));assert.equal(requests.filter(r=>r.options.method==='DELETE').length,0);
 w.confirm=()=>true;revisionButtons[0].click();await new Promise(r=>setTimeout(r,15));assert.equal(requests.filter(r=>r.url.includes('/revisions/')&&r.options.method==='DELETE').length,1);assert.equal(w.document.querySelectorAll('[data-library-history] .nc-library-row').length,1);
 requests=requests.filter(r=>!r.url.includes('/revisions/'));
 const deleteButton=[...w.document.querySelectorAll('.nc-library-results button')].find(b=>b.textContent==='Delete');assert.ok(deleteButton);
 w.confirm=()=>false;deleteButton.click();await new Promise(r=>setTimeout(r,10));assert.equal(requests.filter(r=>r.options.method==='DELETE').length,0);
 w.confirm=()=>false;deleteButton.click();await new Promise(r=>setTimeout(r,10));assert.equal(requests.filter(r=>r.options.method==='DELETE').length,0);
 w.confirm=()=>true;deleteButton.click();await new Promise(r=>setTimeout(r,15));assert.equal(requests.filter(r=>r.options.method==='DELETE').length,1);assert.equal(w.sessionStorage.getItem('networkConfigurator.library.context'),null);
 const current=w.sessionStorage.getItem('networkConfigurator.library.context');
 const priorReport=w.sessionStorage.getItem('networkConfigurator.report.current');const broken=JSON.parse(JSON.stringify(saved.document));broken.reporting.links='invalid';assert.throws(()=>w.NetworkProjects.openFile(broken));assert.equal(w.sessionStorage.getItem('networkConfigurator.report.current'),priorReport);assert.throws(()=>w.NetworkProjects.openFile({schema:'bad'}));assert.equal(w.sessionStorage.getItem('networkConfigurator.library.context'),current);
 const malformedDesign=JSON.parse(JSON.stringify(saved.document));malformedDesign.design.moduleStates={BGP:null};assert.throws(()=>w.NetworkProjects.openFile(malformedDesign));assert.equal(w.sessionStorage.getItem('networkConfigurator.report.current'),priorReport);
 w.NetworkProjects.openFile(saved.document);assert.equal(w.sessionStorage.getItem('networkConfigurator.library.context'),null);assert.equal(w.applied.project.name,'Saved synthetic lab');assert.notEqual(w.applied.project.id,'p_lab');
 assert.equal(JSON.parse(w.sessionStorage.getItem('networkConfigurator.report.current')).source.projectId,w.applied.project.id);
 console.log('Project Library: bundle, credential exclusion, create/update and working-copy restore passed');dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
