const fs=require('fs'),assert=require('assert/strict'),{JSDOM,VirtualConsole}=require('jsdom'),{execFileSync}=require('child_process'),guide=require('./vpc-report.js');
const dev=(id,tier,hostname,vendor='Cisco NX-OS')=>({id,tier,hostname,index:1,vendor,model:'',serial:'',modelSource:'',serialSource:''});
const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100"><rect x="10" y="10" width="280" height="80" fill="#e8f0f7"/><text x="30" y="55">Network devices</text></svg>';
const fabric={architecture:'spine-leaf',roles:{upper:'Spine',lower:'Leaf'},techPlacement:'upper',devices:[dev('s1','upper','SPINE-1'),dev('s2','upper','SPINE-2'),...Array.from({length:4},(_,i)=>dev('l'+i,'lower','LEAF-'+(i+1)))],links:[],specialLinks:[]};
for(const d of fabric.devices.filter(d=>d.tier==='lower'))for(const id of ['s1','s2'])fabric.links.push({a:id,b:d.id,enabled:true,upperPort:'Ethernet1/1',lowerPort:'Ethernet1/2',speed:'100G',detail:'vPC'});
const routing={architecture:'module',roles:{upper:'CE router',lower:'ISP router'},devices:[dev('ce1','upper','CE-1'),dev('ce2','upper','CE-2'),dev('isp1','lower','ISP-1'),dev('isp2','lower','ISP-2')],links:[{a:'ce1',b:'isp1',enabled:true,upperPort:'Eth1',lowerPort:'Eth2',speed:'',detail:'eBGP'}],specialLinks:[]};
const management={architecture:'module',roles:{upper:'Managed device',lower:'Managed device'},devices:[dev('mg1','upper','SPINE-1')],links:[],specialLinks:[]};
const modules=[{module:'BASIC',title:'System and Management',technology:'System and Management',design:management},{module:'BGP',title:'BGP',technology:'BGP',design:routing},{module:'VPC',title:'vPC / MLAG',technology:'vPC',design:fabric}].map(m=>({...m,vendor:'Cisco NX-OS',topologySvg:svg,topologyPng:'',deviceCount:m.design.devices.length,configurationCount:0}));
const source={schema:'network-configurator-report-v1',language:'tr',name:'Network design',vendor:'Cisco NX-OS',technology:'Combined · System and Management + BGP + vPC',architecture:'module',roles:{upper:'Network device',lower:'Network device'},techPlacement:'upper',upperCount:11,lowerCount:0,devices:modules.flatMap(m=>m.design.devices).map((d,i)=>({...d,tier:'upper',index:i+1})),links:modules.flatMap(m=>m.design.links),specialLinks:[],parameters:[],configurations:[{deviceId:'s1',source:'Combined Technology Workspaces',text:'hostname SPINE-1\nvpc domain 10\n peer-gateway'}],moduleReports:modules,scope:'',source:{module:'COMBINED',projectId:'unified-test'}};
fs.writeFileSync('/tmp/network-configurator-audit-payload.json',JSON.stringify(source));
for(const language of ['tr','en']){
 const p=guide.designPresentation({...source,language});assert.equal(p.narratives.length,1);assert.equal(p.physicalCount,10);assert.ok(!/Combined/.test(JSON.stringify(p)));assert.match(p.overview,/2 (adet )?Spine/);assert.match(p.overview,/4 (adet )?Leaf/);assert.match(p.overview,/2 (adet )?CE/);assert.ok(!/1 adet ağ cihazı/.test(p.overview));assert.equal((p.svg.match(/<svg/g)||[]).length,3);assert.ok(!/System and Management/.test(p.svg));assert.equal(source.links.length,9,'no cross-domain cables invented');
}
for(const vendor of ['Cisco NX-OS','Cisco IOS-XE','Arista EOS','Huawei_CE_SW','FortiGate'])for(const technology of ['BGP','OSPF','STP','EVPN/VXLAN','SD-WAN','MLAG','M-LAG']){
 const p=guide.designPresentation({...source,moduleReports:[{...modules[0],vendor},{...modules[1],vendor,technology,title:technology},{...modules[2],vendor,technology:technology==='MLAG'?'MLAG':'STP'}]});assert.equal(p.narratives.length,1);assert.ok(!/Combined/.test(p.technology));assert.ok(p.vendors.includes(vendor==='Huawei_CE_SW'?'Huawei CloudEngine':vendor));
}
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));let payload;
const dom=new JSDOM(fs.readFileSync('reporting.html','utf8'),{url:'https://test.invalid/reporting',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.eval(fs.readFileSync('engineering-locale.js','utf8'));w.eval(fs.readFileSync('vpc-report.js','utf8'));w.eval(fs.readFileSync('verification-plan.js','utf8'));w.sessionStorage.setItem('networkConfigurator.report.import',JSON.stringify(source));w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};w.fetch=async(url,opts)=>{payload=JSON.parse(opts.body);return {ok:true,blob:async()=>new w.Blob(['test'])};};}});
(async()=>{try{for(const language of ['tr','en']){const d=dom.window.document,select=d.getElementById('reportLanguage');select.value=language;select.dispatchEvent(new dom.window.Event('change',{bubbles:true}));assert.equal(d.querySelectorAll('.report-topology-narrative').length,1);assert.equal(d.querySelectorAll('.unified-topology').length,1);assert.ok(!/Combined/.test(d.getElementById('reportPreview').textContent),d.getElementById('reportPreview').textContent.match(/.{0,60}Combined.{0,100}/g)?.join('\n'));d.getElementById('downloadWord').click();await new Promise(r=>setTimeout(r,10));assert.equal(payload.unifiedDesign,true);assert.equal(payload.topologyNarratives.length,1);assert.ok(!/Combined/.test(payload.technology));assert.ok(payload.projectOverview);fs.writeFileSync('/tmp/unified-'+language+'.json',JSON.stringify(payload));const output=execFileSync(process.env.CODEX_PRIMARY_RUNTIME_PYTHON||'python',['-c','import json,sys,io;from docx import Document;from app import app;from fastapi.testclient import TestClient;p=json.load(sys.stdin);r=TestClient(app).post("/api/reporting/word",json=p);assert r.status_code==200,r.text;d=Document(io.BytesIO(r.content));text="\\n".join(x.text for x in d.paragraphs);assert "Combined" not in text;assert p["projectOverview"] in text;assert sum(x.text==p["topologyNarratives"][0]["title"] for x in d.paragraphs)==1;assert not any(x.text.startswith("System and Management ·") for x in d.paragraphs);open("/tmp/unified-"+p["language"]+".docx","wb").write(r.content);print("Word passed")'],{input:JSON.stringify(payload),encoding:'utf8'});assert.match(output,/passed/);}assert.deepEqual(errors,[]);console.log('Unified architecture, management scope, all-vendor composition, legacy reports and TR/EN Word passed');}finally{dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
