const {execFileSync}=require('child_process');const fs=require('fs'),assert=require('assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
let html=fs.readFileSync('web.html','utf8').replace(/\}\)\(\);\s*<\/script>\s*<\/body>/,'window.__managementAudit={reportingDesign,combineReports,managementTargets,applyManagementTargets,existingManagementTargets};})();</script></body>');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url:'https://test.invalid/',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.eval(fs.readFileSync('engineering-locale.js','utf8'));w.eval(fs.readFileSync('vpc-report.js','utf8'));w.eval(fs.readFileSync('verification-plan.js','utf8'));w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.fetch=async()=>({ok:true,json:async()=>({commands:[]})});w.SVGElement.prototype.getBBox=()=>({x:0,y:0,width:720,height:300});w.SVGElement.prototype.getComputedTextLength=()=>80;}});
const w=dom.window,d=w.document,pause=()=>new Promise(r=>setTimeout(r,100));const report=key=>({...w.__managementAudit.reportingDesign(),moduleKey:key,moduleTitle:key==='BASIC'?'System and Management':key,topologySvg:'',topologyPng:''});
(async()=>{try{await pause();const base=report('BASIC'),reports=[base];for(const key of ['BGP','VPC','EVPN']){d.querySelector(`.tech[data-tech="${key}"]`).click();await pause();reports.push(report(key));}const api=w.__managementAudit,targets=api.managementTargets(reports);assert.ok(!targets.some(t=>t.hostname.startsWith('ISP')));assert.ok(targets.some(t=>t.hostname==='CE-1'));assert.ok(targets.some(t=>t.hostname==='SPINE-1'));
const automatic=api.existingManagementTargets(reports);assert.equal(automatic.length,targets.length);assert.ok(automatic.every(r=>r.omitOob));const autoReports=await api.applyManagementTargets(reports,automatic);const autoCombined=api.combineReports(autoReports);for(const row of automatic){const dev=autoCombined.devices.find(d=>d.hostname===row.device.hostname&&d.vendor===row.device.vendor);const cfg=autoCombined.configurations.find(c=>c.deviceId===dev.id).text;assert.match(cfg,/SYSTEM AND MANAGEMENT/);assert.ok(!cfg.includes('192.168.100.11'));assert.ok(!cfg.includes('OOB-MANAGEMENT'));}assert.ok(!autoCombined.devices.some(d=>d.hostname==='SW-01'));
const stateContent=()=>JSON.stringify(Object.fromEntries(Object.entries(w.__workspaceModuleStates).map(([k,v])=>[k,{platform:v.platform,fields:v.fields}])));const saved=stateContent();
const rows=[{device:targets.find(t=>t.hostname==='CE-1'),iface:'mgmt0',ip:'192.0.2.11',prefix:'24'},{device:targets.find(t=>t.hostname==='SPINE-1'),iface:'mgmt0',ip:'192.0.2.12',prefix:'24'}];
const applied=await api.applyManagementTargets(reports,rows);assert.equal(stateContent(),saved,'source workspaces remain unchanged');const combined=api.combineReports(applied);for(const row of rows){const device=combined.devices.find(x=>x.hostname===row.device.hostname);const config=combined.configurations.find(x=>x.deviceId===device.id).text;assert.match(config,/SYSTEM AND MANAGEMENT/);assert.match(config,/feature ssh/);assert.ok(config.includes(row.ip));assert.match(config,row.device.hostname==='CE-1'?/router bgp/:/vpc domain/);assert.equal(combined.devices.filter(x=>x.hostname===device.hostname&&x.vendor===device.vendor).length,1);}assert.ok(!combined.devices.some(x=>x.hostname==='SW-01'));assert.ok(!combined.configurations.find(c=>c.deviceId===combined.devices.find(x=>x.hostname==='CE-2')?.id)?.text.includes('SYSTEM AND MANAGEMENT'));
combined.name='Device configuration composition test';combined.language='en';const word=execFileSync(process.env.CODEX_PRIMARY_RUNTIME_PYTHON||'python',['-c','import json,sys,io;from app import app;from fastapi.testclient import TestClient;from docx import Document;p=json.load(sys.stdin);r=TestClient(app).post("/api/reporting/word",json=p);assert r.status_code==200,r.text;d=Document(io.BytesIO(r.content));text="\\n".join(x.text for x in d.paragraphs);assert sum(x.text=="CE-1" and x.style.name.startswith("Heading") for x in d.paragraphs)==1;assert "SYSTEM AND MANAGEMENT" in text and "router bgp" in text and "vpc domain" in text;print("Word device grouping passed")'],{input:JSON.stringify(combined),encoding:'utf8'});assert.match(word,/passed/);
for(const vendor of ['Cisco IOS-XE','Arista EOS','Huawei_CE_SW','FortiGate']){const device={...rows[0].device,vendor,hostname:'TARGET-1'};const result=await api.applyManagementTargets([base], [{...rows[0],device,iface:vendor==='FortiGate'?'port1':vendor==='Huawei_CE_SW'?'MEth0/0/0':vendor==='Arista EOS'?'Management1':'GigabitEthernet0/0'}]);const config=result[0].configurations[0].text;assert.ok(config.includes('TARGET-1'));assert.ok(config.includes('192.0.2.11'));assert.match(config,vendor==='FortiGate'?/config system/:vendor==='Huawei_CE_SW'?/sysname/:/hostname/);assert.equal(stateContent(),saved);const omitted=await api.applyManagementTargets([base],[{...rows[0],device,iface:vendor==='FortiGate'?'port1':vendor==='Huawei_CE_SW'?'MEth0/0/0':vendor==='Arista EOS'?'Management1':'GigabitEthernet0/0',omitOob:true}]);assert.ok(!omitted[0].configurations[0].text.includes('192.0.2.11'));assert.ok(!omitted[0].configurations[0].text.includes('OOB-MANAGEMENT'));assert.equal(stateContent(),saved);}
const sameHostBase={...base,devices:[{...base.devices[0],hostname:'CE-1'}]};const reused=api.existingManagementTargets([sameHostBase,reports.find(r=>r.moduleKey==='BGP')]);assert.equal(reused.find(r=>r.device.hostname==='CE-1').omitOob,false);assert.equal(reused.find(r=>r.device.hostname==='CE-2').omitOob,true);
assert.deepEqual(errors,[]);console.log('Automatic management composition without repeated OOB entry, external exclusion, all vendor syntax and workspace preservation passed');}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
