const fs=require('fs'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{JSDOM,VirtualConsole}=require('jsdom');
require('./engineering-report.js');const build=globalThis.NetworkEngineeringReport.build;
function state(vendor,technology,module,text,extra={}){return {schema:'network-configurator-report-v1',name:'Engineering acceptance test',language:'en',vendor,technology,architecture:'module',techPlacement:'upper',upperCount:1,lowerCount:0,scope:'',source:{module},devices:[{id:'a',tier:'upper',index:1,hostname:'CE1',vendor,model:'',serial:'',modelSource:'',serialSource:''}],links:[],specialLinks:[],configurations:[{deviceId:'a',text,source:'Workspace'}],parameters:[],inventoryDeviceIds:[],...extra};}
const bgp=state('Huawei_CE_SW','BGP','BGP','bgp 65001\n peer 10.0.0.2 as-number 65002\nroute-policy PRIMARY permit node 10\n apply local-preference 200\nroute-policy BACKUP permit node 10\n apply local-preference 100\n');
bgp.devices.push({id:'isp1',hostname:'Provider Alpha',external:true,tier:'upper',index:2,model:'',serial:'',modelSource:'',serialSource:''},{id:'isp2',hostname:'Provider Beta',external:true,tier:'upper',index:3,model:'',serial:'',modelSource:'',serialSource:''});bgp.upperCount=3;
bgp.verificationPlan=[{included:true,vendor:'Huawei_CE_SW',technology:'BGP',hostname:'CE1',command:'display bgp routing-table'},{included:false,vendor:'Huawei_CE_SW',technology:'BGP',hostname:'CE1',command:'display bgp peer'}];
let plan=build(bgp);assert.ok(plan.sections[0].paragraphs.join(' ').includes('200 / 100'));assert.ok(plan.sections[0].scenarios[0].impact.includes('2 ISP'));assert.ok(plan.sections[0].scenarios[0].evidence.includes('display bgp routing-table'));assert.ok(!plan.sections[0].scenarios[0].evidence.includes('display bgp peer'));assert.ok(plan.sections[0].scenarios.every(s=>s.status==='Not tested'));
const single=structuredClone(bgp);single.devices=single.devices.slice(0,2);single.upperCount=2;assert.ok(build(single).sections[0].scenarios[0].impact.includes('No second ISP'));
for(const vendor of ['Arista EOS','Huawei_CE_SW','Huawei iStack']){const s=state(vendor,vendor==='Huawei iStack'?'Huawei iStack':'M-LAG','VPC',vendor==='Huawei iStack'?'stack\n mad detect mode direct\n':'dfs-group 1\n peer-link 1\n');const out=JSON.stringify(build(s));assert.ok(!out.includes('Cisco'),vendor);assert.ok(out.includes(vendor==='Huawei_CE_SW'?'Huawei CloudEngine':vendor));}
const combined=state('Huawei_CE_SW','BGP + System and Management','COMBINED','######## BGP · Workspace ########\napply local-preference 300\n######## SYSTEM AND MANAGEMENT · Workspace ########\nntp-service unicast-server 192.0.2.10\n',{moduleReports:[{module:'BGP',title:'BGP',technology:'BGP',vendor:'Huawei_CE_SW',design:{devices:bgp.devices.slice(0,1),links:[]}},{module:'BASIC',title:'System and Management',technology:'System and Management',vendor:'Huawei_CE_SW',design:{devices:bgp.devices.slice(0,1),links:[]}}]});const cp=build(combined);assert.equal(cp.sections.length,2);assert.ok(cp.sections[0].paragraphs.join(' ').includes('300'));assert.ok(cp.sections[1].paragraphs.join(' ').includes('1 distinct NTP'));assert.ok(!cp.sections[1].paragraphs.join(' ').includes('Local Preference'));
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));let payload;
const dom=new JSDOM(fs.readFileSync('reporting.html','utf8'),{url:'https://test.invalid/reporting',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){for(const f of ['engineering-locale.js','vpc-report.js','verification-plan.js','engineering-report.js'])w.eval(fs.readFileSync(f,'utf8'));w.sessionStorage.setItem('networkConfigurator.report.import',JSON.stringify(bgp));w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};w.fetch=async(url,options)=>{payload=JSON.parse(options.body);return {ok:true,blob:async()=>new w.Blob(['TEST'])};};}});
(async()=>{try{const w=dom.window,d=w.document;await new Promise(r=>setTimeout(r,15));assert.equal(d.getElementById('reportLanguage').value,'en');assert.equal(d.querySelectorAll('.engineering-acceptance-table').length,1);assert.ok(d.querySelector('.engineering-operational-plan').textContent.includes('200 / 100'));
for(const lang of ['en','tr']){d.getElementById('reportLanguage').value=lang;d.getElementById('reportLanguage').dispatchEvent(new w.Event('change'));d.getElementById('downloadWord').click();await new Promise(r=>setTimeout(r,20));assert.ok(payload.engineeringPlan);assert.equal(payload.language,lang);const result=execFileSync('python3',['-c','import json,sys,io;from fastapi.testclient import TestClient;from docx import Document;import app;r=TestClient(app.app).post("/api/reporting/word",json=json.load(sys.stdin));assert r.status_code==200,r.text;d=Document(io.BytesIO(r.content));print(json.dumps({"paragraphs":[p.text for p in d.paragraphs],"tables":[[[c.text for c in row.cells] for row in t.rows] for t in d.tables]}))'],{input:JSON.stringify(payload),encoding:'utf8'});const word=JSON.parse(result);const expected=lang==='en'?'Failure / operational scenario':'Arıza / işletim senaryosu';assert.ok(word.tables.some(t=>t[0][0]===expected));assert.ok(word.paragraphs.includes(payload.engineeringPlan.title));const section=d.querySelector('.engineering-operational-plan').textContent;assert.ok(section.includes(lang==='en'?'Not tested':'Test edilmedi'));assert.ok(!section.includes(lang==='en'?'Test edilmedi':'Not tested'));}
assert.deepEqual(errors,[]);console.log('Engineering reporting: dynamic Local Preference/provider count, vendor isolation, module scope, selected evidence, English default and TR/EN preview/Word acceptance tables passed');}finally{dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
