const {execFileSync}=require('child_process');const fs=require('fs'),assert=require('assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
let html=fs.readFileSync('web.html','utf8').replace(/\}\)\(\);\s*<\/script>\s*<\/body>/,'window.__managementAudit={reportingDesign,combineReports,managementTargets,applyManagementTargets,showManagementTargets,readManagementTargets,collectModuleReport,showCombineModal};})();</script></body>');
html=html.replace('function workspaceTopologyPng(svg){','function workspaceTopologyPng(svg){return Promise.resolve("");');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url:'https://test.invalid/',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.eval(fs.readFileSync('engineering-locale.js','utf8'));w.eval(fs.readFileSync('vpc-report.js','utf8'));w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.fetch=async()=>({ok:true,json:async()=>({commands:[]})});w.SVGElement.prototype.getBBox=()=>({x:0,y:0,width:720,height:300});w.SVGElement.prototype.getComputedTextLength=()=>80;}});
const w=dom.window,d=w.document,pause=()=>new Promise(r=>setTimeout(r,100));const report=key=>({...w.__managementAudit.reportingDesign(),moduleKey:key,moduleTitle:key==='BASIC'?'System and Management':key,topologySvg:'',topologyPng:''});
(async()=>{try{await pause();d.querySelector('.tech[data-tech="BGP"]').click();await pause();d.getElementById('platform').value='Huawei_CE_SW';d.getElementById('platform').dispatchEvent(new w.Event('change'));await pause();w.__managementAudit.showCombineModal();assert.equal(d.querySelector('[data-report-platform="VPC"]').value,'Huawei_CE_SW');
// Skip image rasterization in this DOM-only test.
w.URL.createObjectURL=()=>"blob:test";w.URL.revokeObjectURL=()=>{};w.Image=class{set src(value){setTimeout(()=>this.onerror?.(),0)}};
const reports=[];for(const key of ['BGP','VPC','BASIC']){const r=await w.__managementAudit.collectModuleReport(key,'Huawei_CE_SW');assert.equal(r.vendor,'Huawei_CE_SW');reports.push(r);}const combined=w.__managementAudit.combineReports(reports);const presentation=w.NetworkReportGuide.designPresentation(combined);assert.ok(!JSON.stringify(presentation).includes('Cisco NX-OS vPC'));assert.ok(JSON.stringify(presentation).includes('Huawei'));assert.equal(w.NetworkReportGuide.build(combined),null);assert.ok(reports.find(r=>r.moduleKey==='VPC').configurations.some(c=>/dfs-group|m-lag/i.test(c.text)));console.log('Huawei BGP/M-LAG/management report vendor and CLI regression passed');}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
