const fs=require('fs'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{JSDOM,VirtualConsole}=require('jsdom');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('Not implemented: navigation'))errors.push(e.message);});
const graph=sources=>JSON.parse(execFileSync('python',['-c','import sys,json;from network_discovery import build_graph;s=json.load(sys.stdin);print(json.dumps({"graph":build_graph(s),"sources":s}))'],{input:JSON.stringify(sources),encoding:'utf8'}));
const base={schema:'network-configurator-v3',project:{id:'p_demo',name:'Discovery test'},workspace:{technology:'BGP',platform:'Cisco IOS-XE'},fields:{bgpCustomerAs:'65001'},moduleStates:{BGP:{platform:'Cisco IOS-XE',fields:{bgpCustomerAs:'65001'}}}};
let collects=0,down=[],latestRequest;
const dom=new JSDOM(fs.readFileSync('network-discovery.html','utf8'),{runScripts:'dangerously',url:'https://test.invalid/network-discovery',virtualConsole:vc,beforeParse(w){w.sessionStorage.setItem('networkConfigurator.workflow.design',JSON.stringify(base));w.confirm=()=>true;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.URL.createObjectURL=blob=>{down.push(blob);return 'blob:test';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};w.fetch=async(url,options)=>{if(url==='/auth/status')return {ok:true,json:async()=>({authenticated:true,username:'synthetic'})};if(url==='/api/projects/status')return {ok:true,json:async()=>({available:false})};if(url==='/api/projects')return {ok:true,json:async()=>({projects:[],total:0})};if(url==='/api/discovery/parse'){const data=JSON.parse(options.body);latestRequest=data;return {ok:true,json:async()=>graph(data.sources)};}if(url==='/api/discovery/collect'){collects++;const p=JSON.parse(options.body);return {ok:true,json:async()=>({mock:false,warnings:[],sources:[{platform:p.platform,protocol:'lldp',deviceName:'SSH-CORE',target:p.target,output:'Local Intf: Ethernet1\nChassis id: 0011.2233.4455\nPort id: Ethernet1\nSystem Name: LEAF-SSH\nSystem Description: Arista EOS\nManagement address: 192.0.2.21',origin:'SSH inventory / neighbors',observedAt:'2026-10-06T17:00:00Z',identity:{hostname:'SSH-CORE',model:'C9300',serial:'SERIAL-TEST',software_version:'17.12.4'}}]})};}throw Error('Unexpected request '+url);};}});
const w=dom.window,d=w.document;for(const f of ['network-discovery.js','corporate-shell.js','project-library.js'])w.eval(fs.readFileSync(f,'utf8'));
const click=id=>d.getElementById(id).click(),pause=()=>new Promise(r=>setTimeout(r,30));
const input=(n,v)=>{n.value=v;n.dispatchEvent(new w.Event('input'));};
(async()=>{try{
 assert.equal(d.querySelector('[data-nc-discovery]').getAttribute('aria-current'),'page');assert.equal(d.querySelector('[data-nc-discovery]').closest('[data-nc-group]').dataset.ncGroup,'inventory');assert.equal(d.querySelectorAll('.nc-planned').length,10);
 click('discoveryExample');click('discoveryParse');await pause();const first=w.NetworkDiscovery.snapshot();assert.equal(first.graph.devices.length,3);assert.equal(first.graph.links.length,2);assert.ok(d.getElementById('discoveryMap').innerHTML.includes('DEMO-LEAF-01'));assert.equal(d.querySelectorAll('#discoveryDevices tr').length,3);assert.equal(first.graph.devices.find(x=>x.hostname==='DEMO-LEAF-01').managementAddresses[0],'192.0.2.11');assert.equal(d.getElementById('discoveryTransfer'),null);assert.equal(d.getElementById('discoveryInventorySeeds'),null);assert.equal(w.NetworkDiscovery.transfer,undefined);
 const project=w.NetworkWorkspaceProject.snapshot();assert.equal(project.fields.bgpCustomerAs,'65001');assert.deepEqual(JSON.parse(JSON.stringify(project.moduleStates)),base.moduleStates);assert.equal(project.networkDiscovery.sources.length,1);w.NetworkWorkspaceProject.apply(base);assert.equal(d.querySelectorAll('#discoveryDevices tr').length,0);w.NetworkWorkspaceProject.apply(project);assert.equal(d.querySelectorAll('#discoveryDevices tr').length,3);
 click('discoveryAddSeed');const fields=d.querySelectorAll('#discoverySeeds input');input(fields[1],'192.0.2.20');input(fields[3],'test-user');input(fields[4],'SYNTHETIC_PASSWORD');input(fields[5],'SYNTHETIC_SECRET');click('discoveryRun');await pause();assert.equal(collects,1);assert.ok(d.getElementById('discoverySeeds').textContent.includes('Collected'));assert.equal(d.querySelector('#discoverySeeds input[type=password]').value,'');const updated=w.NetworkWorkspaceProject.snapshot();assert.ok(!JSON.stringify(updated).includes('SYNTHETIC_PASSWORD'));assert.ok(!JSON.stringify(updated).includes('SYNTHETIC_SECRET'));assert.ok(updated.networkDiscovery.graph.devices.some(x=>x.serial==='SERIAL-TEST'));
 assert.equal(w.sessionStorage.getItem('networkConfigurator.report.current'),null);assert.equal(w.sessionStorage.getItem('networkConfigurator.discovery.inventoryImport'),null);
 click('discoverySvg');click('discoveryCSV');click('discoveryJson');assert.equal(down.length,3);w.confirm=()=>false;click('discoveryReset');assert.ok(w.NetworkDiscovery.snapshot().graph.devices.length);w.confirm=()=>true;click('discoveryReset');assert.equal(w.NetworkDiscovery.snapshot().graph.links.length,0);assert.equal(w.NetworkWorkspaceProject.snapshot().fields.bgpCustomerAs,'65001');assert.deepEqual(errors,[]);
 console.log('Discovery UI: real parser map, sidebar, SSH isolation, credentials, project roundtrip, brownfield reporting isolation and unchanged design/configs passed');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
