import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
const html=fs.readFileSync('reporting.html','utf8');
const logic=html.slice(html.indexOf('  let inventoryMode='),html.indexOf('  let maintenanceView='));
const devices=[{id:'one',hostname:'SW1',model:'Keep model',vendor:'Cisco NX-OS'},{id:'two',hostname:'SW2',serial:'Keep serial',vendor:'Arista EOS'}];
const elements=new Map();
const $=id=>{if(!elements.has(id))elements.set(id,{value:'',disabled:false,textContent:'',innerHTML:'',hidden:false,querySelector:()=>null});return elements.get(id);};
const rows=devices.map(d=>{const inputs={'target':{value:d.id+'.example.test'},sshPort:{value:'22'},sshUsername:{value:'test'},password:{value:''},secret:{value:''}};return {dataset:{batch:d.id},inputs,status:{textContent:''},querySelector(selector){if(selector==='[data-select]')return {checked:true};if(selector==='[data-result]')return this.status;return inputs[/data-key="(.*?)"/.exec(selector)[1]];}};});
$('batchRows').querySelectorAll=()=>rows;
$('batchPassword').value='test-password';
let calls=0,reportUpdates=0;
const context={crypto:webcrypto,$,val:id=>$(id).value,state:{devices,vendor:'Cisco NX-OS'},document:{querySelectorAll:()=>[]},deviceName:d=>d.hostname,esc:x=>String(x),vendorLabel:x=>x,renderReport(){reportUpdates++;},renderEditor(){},fetch:async(url,request)=>{const p=JSON.parse(request.body);assert.equal(p.password,'test-password');assert.equal(p.platform,devices[calls].vendor);calls++;return calls===1?{ok:false,json:async()=>({detail:'Test failure'})}:{ok:true,json:async()=>({hostname:'OBSERVED-SW2',model:'DCS-7050',serial:'',software_version:'4.32.1F',observed_at:'now',warnings:['serial unavailable']})};}};
vm.createContext(context);vm.runInContext(logic,context);
await $('runInventoryBatch').onclick();
assert.equal(calls,2,'failure must not stop the next device');
assert.equal(devices[0].model,'','failed latest reads must not retain old identity');
assert.equal(devices[1].serial,'','missing latest fields stay empty');
assert.equal(devices[1].softwareVersion,'4.32.1F');
assert.equal(devices[1].observedHostname,'OBSERVED-SW2');
assert.match($('sshInventoryResults').innerHTML,/OBSERVED-SW2/);
assert.match($('sshInventoryResults').innerHTML,/4.32.1F/);
assert.equal($('sshInventoryResults').innerHTML.includes('Keep serial'),false);
assert.equal($('batchPassword').value,'');
assert.match($('batchSummary').textContent,/1 collected · 1 failed/);
assert.equal(JSON.stringify(devices).includes('test-password'),false);
console.log('Multi-device failure isolation, vendor routing, partial collection and credential exclusion passed.');
assert.match(rows[0].status.textContent,/Connection failed/);
assert.match(rows[1].status.textContent,/Connection successful/);
devices.forEach(d=>{d.collectionMethod='manual';d.inventoryChannel='manual';});
context.fetch=async()=>({ok:true,json:async()=>({rows:[
  {row:'2',id:'one',hostname:'OBSERVED-SW1',serial:'00012',softwareVersion:'',model:''},
  {row:'3',hostname:'SW2',serial:'SN2',softwareVersion:'',model:''},
  {row:'4',hostname:'NEW-SW3',serial:'SN3',softwareVersion:'1.0',model:'M3'}
]})});
await $('inventoryExcel').onchange({target:{files:[{name:'inventory.xlsx',size:100}],value:''}});
assert.equal(devices[0].serial,'00012','Excel imports directly without an Apply action');
assert.equal(devices[0].hostname,'SW1','planned topology hostname is preserved');
assert.equal(devices[0].observedHostname,'OBSERVED-SW1');
assert.equal(devices[0].model,'','new upload blank cells clear previous values');
assert.equal(devices[1].serial,'SN2');
assert.equal(devices[1].softwareVersion,'');
assert.equal(devices[2].inventoryOnly,true);
assert.equal(devices[2].hostname,'NEW-SW3');
assert.equal(devices[2].serial,'SN3');
assert.equal($('excelPreview').innerHTML.includes('Report device'),false);
vm.runInContext('importExcelRows([{row:"2",hostname:"NEW-SW3",serial:"UPDATED",model:"",softwareVersion:""}])',context);
assert.equal(devices.length,3,'reimport updates the added inventory device');
assert.equal(devices[2].serial,'UPDATED');
assert.throws(()=>vm.runInContext('importExcelRows([{row:"2",hostname:"DUP"},{row:"3",hostname:"DUP"}])',context));
assert.equal(devices.length,3,'duplicate validation happens before any mutation');
$('manualRows').querySelectorAll=()=>[];
$('addInventoryDevice').onclick();
assert.equal(devices.length,4);
assert.equal(devices[3].inventoryOnly,true);
vm.runInContext('inventoryMode="automatic"',context);
$('addInventoryDevice').onclick();
assert.equal(devices.length,5);
assert.equal(devices[4].collectionMethod,'automatic');
assert.equal(vm.runInContext('batchSelection.has(state.devices[4].id)',context),true);
context.rawUpper=()=>"Spine";context.rawLower=()=>"Leaf";context.selectedDevice=null;
context.state.upperCount=1;context.state.lowerCount=1;context.state.links=[];
vm.runInContext(html.slice(html.indexOf('  function syncTopology(){'),html.indexOf('  function deviceCard(')),context);
vm.runInContext('syncTopology()',context);
assert.equal(context.state.devices.filter(d=>d.inventoryOnly).length,3);
assert.equal(context.state.links.length,1,'inventory additions do not create topology links');
console.log('Direct Excel imports, new devices, reimports, duplicate rejection, Add device in both modes and topology isolation passed.');
context.vendors=['Cisco NX-OS','Cisco IOS-XE','Arista EOS','Huawei_CE_SW','FortiGate'];
const previousCalls=calls;
const added=vm.runInContext('importSshTargets([{row:"2",hostname:"SSH-SW1",target:"ssh1.example.com",username:"engineer",port:"2222",platform:"Arista EOS"},{row:"3",hostname:"SSH-SW2",target:"ssh2.example.com",username:"engineer",port:"",platform:"Huawei CloudEngine"}])',context);
assert.equal(added,2);
assert.equal(calls,previousCalls,'upload must not start SSH connections');
const sshDevice=context.state.devices.find(d=>d.hostname==='SSH-SW1');
assert.equal(sshDevice.vendor,'Arista EOS');assert.equal(sshDevice.sshPort,2222);assert.equal(sshDevice.sshUsername,'engineer');
assert.equal(context.state.devices.find(d=>d.hostname==='SSH-SW2').vendor,'Huawei_CE_SW');
const count=context.state.devices.length;
vm.runInContext('importSshTargets([{row:"2",hostname:"SSH-SW1",target:"ssh1.example.com",username:"other",port:"2222",platform:"Arista EOS"}])',context);
assert.equal(context.state.devices.length,count);assert.equal(sshDevice.sshUsername,'other');
assert.throws(()=>vm.runInContext('importSshTargets([{row:"2",target:"valid.example.com",username:"engineer"},{row:"3",target:"bad.example.com",username:""}])',context));
assert.equal(context.state.devices.length,count,'invalid uploads cannot partially mutate inventory');
assert.equal(vm.runInContext('batchSelection.has(state.devices.find(d=>d.hostname==="SSH-SW1").id)',context),true);
console.log('SSH Excel target loading, default ports, per-device vendors, reimport and validation passed.');
const manualDevice=vm.runInContext('inventoryMode="manual";createInventoryDevice("SAME-NAME")',context);
manualDevice.model='MANUAL-ONLY-MODEL';manualDevice.serial='MANUAL-ONLY-SERIAL';
vm.runInContext('importSshTargets([{row:"2",hostname:"SAME-NAME",target:"separate.example.com",username:"engineer"}])',context);
const separate=context.state.devices.filter(d=>d.hostname==='SAME-NAME');
assert.equal(separate.length,2);
assert.equal(separate.find(d=>d.inventoryChannel==='automatic').model,'');
assert.equal(manualDevice.serial,'MANUAL-ONLY-SERIAL');
assert.equal(vm.runInContext('sshPageDevices().length',context),1,'upload shows only the new selected batch');
context.maintenanceView='inventory';vm.runInContext('renderInventoryManager()',context);
assert.equal($('batchRows').innerHTML.includes('MANUAL-ONLY-MODEL'),false);
assert.equal($('manualRows').innerHTML.includes('SSH-SW1'),false);
assert.equal($('manualRows').innerHTML.includes('MANUAL-ONLY-MODEL'),false,'the previous manual batch is cleared by a new SSH batch');
console.log('Manual/SSH data isolation, selected uploaded batch visibility and connection status labels passed.');

vm.runInContext('importSshTargets([{row:"2",target:"four-column.example.com",port:"",username:"engineer",password:"test-only-import"}]);renderInventoryManager()',context);
const fourColumn=context.state.devices.find(d=>d.target==='four-column.example.com');
assert.ok(fourColumn);
assert.equal(fourColumn.sshPort,22);
assert.equal(fourColumn.vendor,context.state.vendor);
assert.equal(JSON.stringify(context.state).includes('test-only-import'),false);
assert.equal(vm.runInContext('sshPasswords.get(sshPageDevices()[0].id)',context),'test-only-import');
assert.match($('batchRows').innerHTML,/type="password"/);
console.log('Four-column SSH imports, default platform and transient passwords passed.');

const beforeUpdate=reportUpdates;
vm.runInContext('setInventoryData(sshPageDevices()[0],{hostname:"ACTUAL-SSH",model:"C9300",serial:"DYNAMIC-SN",software_version:"17.9.5",observed_at:"now"})',context);
assert.ok(reportUpdates>beforeUpdate,'SSH inventory immediately refreshes the report');
vm.runInContext(html.slice(html.indexOf('  function reportInventorySnapshot(){'),html.indexOf('  const filename=name=>')),context);
const snapshot=vm.runInContext('reportInventorySnapshot()',context);
assert.equal(snapshot.find(d=>d.serial==='DYNAMIC-SN').softwareVersion,'17.9.5');
assert.equal(JSON.stringify(snapshot).includes('test-only-import'),false);
assert.ok(snapshot.every(d=>['hostname','model','serial','modelSource','serialSource'].every(k=>typeof d[k]==='string')),'legacy missing fields export as valid strings');
console.log('Immediate report refresh, current export data, legacy defaults and credential exclusion passed.');

vm.runInContext(html.slice(html.indexOf('  function currentReportInventory(){'),html.indexOf('  function reportRow(')),context);
vm.runInContext('inventoryMode="manual";importExcelRows([{row:"2",hostname:"LATEST-ONLY",serial:"LATEST-SN",softwareVersion:"LATEST-VERSION",model:"LATEST-MODEL"}])',context);
assert.equal(vm.runInContext('manualPageDevices().length',context),1);
assert.equal(vm.runInContext('currentReportInventory().length',context),1);
assert.equal(vm.runInContext('currentReportInventory()[0].serial',context),'LATEST-SN');
assert.equal(vm.runInContext('currentReportInventory().some(d=>d.serial==="DYNAMIC-SN")',context),false);
vm.runInContext('importExcelRows([{row:"2",hostname:"LATEST-ONLY",serial:"",softwareVersion:"",model:""}])',context);
assert.equal(vm.runInContext('currentReportInventory()[0].serial',context),'');
vm.runInContext('importSshTargets([{row:"2",target:"latest-ssh.example.com",username:"engineer"}])',context);
assert.equal(vm.runInContext('currentReportInventory().length',context),0,'SSH upload must not report earlier manual or collected data');
console.log('Latest-only manual list and report, blank replacement and SSH batch isolation passed.');

vm.runInContext(html.slice(html.indexOf('  function normalizeInventoryProject('),html.indexOf('  function openReport(')),context);
context.legacy={devices:[{id:'upper-1',hostname:'DESIGN',model:'OLD-MODEL',serial:'OLD-SERIAL'},{id:'old-extra',inventoryOnly:true,hostname:'OLD-HOST',serial:'OLD-SERIAL'}]};
vm.runInContext('normalizeInventoryProject(legacy)',context);
assert.equal(context.legacy.devices.length,1);
assert.equal(context.legacy.devices[0].hostname,'DESIGN');
assert.equal(context.legacy.devices[0].serial,'');
assert.equal(context.legacy.inventoryDeviceIds.length,0);
context.tracked={inventoryDeviceIds:['latest'],manualVisibleIds:['latest'],sshVisibleIds:[],devices:[{id:'upper-1',hostname:'DESIGN'},{id:'old-extra',inventoryOnly:true,serial:'OLD-SERIAL'},{id:'latest',inventoryOnly:true,serial:'LATEST-SERIAL'}]};
vm.runInContext('normalizeInventoryProject(tracked);normalizeInventoryProject(tracked)',context);
assert.equal(context.tracked.devices.length,2);
assert.equal(context.tracked.devices.find(d=>d.id==='latest').serial,'LATEST-SERIAL');
assert.equal(context.tracked.devices.some(d=>d.id==='old-extra'),false);
console.log('Legacy session cleanup, tracked batch preservation, archive pruning and idempotent reopen passed.');
context.cachedLegacy={schema:'network-configurator-report-v1',vendor:'Cisco NX-OS',source:{projectId:'project',module:'vpc'},scope:'Keep design scope',links:[],devices:[{id:'upper-1',hostname:'SPINE',serial:'OLD-CACHED-SERIAL',model:'OLD-MODEL'},{id:'inv-old-cache',inventoryOnly:true,hostname:'OLD-CACHED-HOST',serial:'OLD-SERIAL'}]};
context.sessionStorage={getItem:()=>JSON.stringify(context.cachedLegacy)};
context.freshDesign={schema:'network-configurator-report-v1',vendor:'Cisco NX-OS',name:'Project',architecture:'module',technology:'vPC',techPlacement:'upper',upperCount:1,lowerCount:0,source:{projectId:'project',module:'vpc'},links:[],devices:[{id:'upper-1',tier:'upper',index:1,hostname:'SPINE',model:'',serial:''}],parameters:[{label:'Keep engineering decision'}],configurations:[{deviceId:'upper-1',text:'Keep configuration'}]};
vm.runInContext(html.slice(html.indexOf('  function openReport('),html.indexOf('  $("openProject").addEventListener')),context);
vm.runInContext('openReport(freshDesign,true)',context);
assert.equal(context.state.devices.some(d=>d.inventoryOnly),false,'workspace reopen cannot append legacy cached extras');
assert.equal(context.state.devices[0].serial,'');
assert.equal(context.state.scope,'Keep design scope');
assert.equal(context.state.configurations[0].text,'Keep configuration');
assert.equal(context.state.parameters[0].label,'Keep engineering decision');
console.log('Technology Workspace reopen cleans legacy inventory while preserving design scope, parameters and configuration passed.');

context.state.inventoryRevision=2;
vm.runInContext('inventoryMode="manual";importExcelRows([{row:"2",hostname:"REMOVE-ME",serial:"REMOVE-SN"}])',context);
const removeId=vm.runInContext('manualPageDevices()[0].id',context);
vm.runInContext('manualSelection.add(manualPageDevices()[0].id);updateRemoveDeviceButton()',context);
assert.equal($('removeInventoryDevice').disabled,false);
context.removeId=removeId;
vm.runInContext('removeInventoryDevices([removeId],"manual")',context);
assert.equal(context.state.devices.some(d=>d.id===removeId),false);
assert.equal(vm.runInContext('currentReportInventory().length',context),0);
vm.runInContext('inventoryMode="automatic";importSshTargets([{row:"2",target:"remove-ssh.example.com",username:"engineer",password:"transient-secret"}]);setInventoryData(sshPageDevices()[0],{serial:"SSH-REMOVE",model:"C9300",hostname:"SSH-REMOVE"})',context);
context.removeSshId=vm.runInContext('sshPageDevices()[0].id',context);
vm.runInContext('removeInventoryDevices([removeSshId],"automatic")',context);
assert.equal(context.state.devices.some(d=>d.id===context.removeSshId),false);
assert.equal(vm.runInContext('sshPasswords.has(removeSshId)',context),false);
assert.equal(vm.runInContext('currentReportInventory().length',context),0);
context.state.manualVisibleIds=['upper-1'];context.state.inventoryDeviceIds=['upper-1'];context.state.devices[0].serial='REMOVE-TOPOLOGY-INVENTORY';
vm.runInContext('removeInventoryDevices(["upper-1"],"manual")',context);
assert.equal(context.state.devices.some(d=>d.id==='upper-1'),true,'removing inventory preserves the design device');
assert.equal(context.state.devices.find(d=>d.id==='upper-1').serial,'');
assert.equal(vm.runInContext('manualPageDevices().length',context),0);
console.log('Manual and SSH removal, report exclusion, credential cleanup and topology preservation passed.');

context.state.inventoryDeviceIds=[];delete context.state.sshVisibleIds;
vm.runInContext('inventoryMode="automatic";createInventoryDevice("PENDING-SSH");normalizeInventoryProject(state)',context);
assert.ok(context.state.devices.some(d=>d.hostname==='PENDING-SSH'),'a new SSH target survives report cache normalization before collection');
console.log('Automatic Add device survives current inventory normalization passed.');
context.currentManual={schema:'network-configurator-report-v1',vendor:'Cisco NX-OS',inventoryRevision:2,inventoryDeviceIds:['manual-one'],manualVisibleIds:['manual-one'],sshVisibleIds:[],links:[],devices:[{id:'manual-one',hostname:'CUSTOM-SW',observedHostname:'CUSTOM-SW',serial:'CURRENT-SERIAL',model:'CURRENT-MODEL',inventoryOnly:true}]};
context.sessionStorage={getItem:key=>key==='networkConfigurator.report.current'?JSON.stringify(context.currentManual):null};
context.freshDesign.devices=context.freshDesign.devices.filter(d=>!d.inventoryOnly);
vm.runInContext('openReport(freshDesign,true)',context);
assert.equal(context.state.devices.find(d=>d.serial==='CURRENT-SERIAL').hostname,'CUSTOM-SW');
assert.equal(context.state.inventoryDeviceIds.length,1);
assert.equal(context.state.configurations[0].text,'Keep configuration');
assert.equal(context.state.links.length,0);
assert.equal(fs.readFileSync('web.html','utf8').includes('sessionStorage.removeItem("networkConfigurator.report.current")'),false);
console.log('Home retains inventory; standalone inventory transfers to workspace reporting without changing topology/configuration passed.');
context.state={inventoryRevision:2,devices:[{id:'planned',hostname:'PLANNED',tier:'upper',collectionMethod:'manual',inventoryChannel:'manual'},{id:'entered',hostname:'ENTERED',inventoryOnly:true,inventoryChannel:'manual'}],inventoryDeviceIds:['planned','entered'],manualVisibleIds:['planned','entered']};
vm.runInContext('normalizeInventoryProject(state)',context);
assert.equal(context.state.inventoryDeviceIds.join(','),'entered');
assert.equal(vm.runInContext('manualPageDevices().map(d=>d.id).join(",")',context),'entered');
vm.runInContext('renderInventoryManager=()=>{};$("selectManualAll").onclick()',context);
assert.equal(vm.runInContext('manualSelection.has("entered")',context),true);
vm.runInContext('$("clearManualAll").onclick()',context);
assert.equal(vm.runInContext('manualSelection.size',context),0);
console.log('Planned technology devices excluded from inventory; manual Select all and Clear selection passed.');

context.state={inventoryRevision:2,devices:[{id:'remove-preview',inventoryOnly:true,inventoryChannel:'manual'}],inventoryDeviceIds:['remove-preview'],manualVisibleIds:['remove-preview']};
$('excelPreview').textContent='Old Excel upload rows';$('sshExcelResult').textContent='Old upload status';
vm.runInContext('removeInventoryDevices(["remove-preview"],"manual")',context);
assert.equal($('excelPreview').textContent,'');assert.equal($('sshExcelResult').textContent,'');
assert.equal(context.state.devices.length,0);
console.log('Device removal clears stale Excel preview and upload status passed.');
$('projectDetailFields').addEventListener=()=>{};
vm.runInContext(html.slice(html.indexOf('  const projectDetailDefinitions='),html.indexOf('  const rw=key=>')),context);
context.state={language:'tr',projectDetails:{customer:'Customer example',acceptance:'Failover evidence',documentStatus:'For review',risks:''}};
const detailRows=vm.runInContext('projectInformation()',context);
assert.equal(detailRows.length,3);
assert.equal(detailRows.find(r=>r.label==='Doküman durumu').impact,'İnceleme için');
assert.equal(detailRows.find(r=>r.label==='Kabul kriterleri').impact,'Failover evidence');
context.state.language='en';
assert.equal(vm.runInContext('projectInformation().find(r=>r.label==="Document status").impact',context),'For review');
console.log('Project report fields omit blanks, preserve engineer content and localize document status passed.');

context.state={language:'tr',name:'',scope:'',vendor:'Cisco NX-OS',technology:'vPC',projectDetails:{customer:'Existing customer'}};
vm.runInContext('applyProjectExample()',context);
assert.equal(context.state.projectDetails.customer,'Existing customer');
assert.equal(context.state.projectDetails.documentStatus,'For review');
assert.equal(context.state.name.includes('vPC'),true);
assert.equal(context.state.scope.includes('Inventory'),true);
assert.equal(Object.keys(context.state.projectDetails).length,8);
context.state.projectDetails.reference='CUSTOM-REF';
vm.runInContext('applyProjectExample()',context);
assert.equal(context.state.projectDetails.reference,'CUSTOM-REF');
console.log('Editable identity example fills blanks, preserves customer entries and updates project scope passed.');
