const fs=require('fs'),assert=require('assert/strict'),{JSDOM,VirtualConsole}=require('jsdom'),{execFileSync}=require('child_process');
const report={schema:'network-configurator-report-v1',inventoryRevision:2,language:'en',name:'Discovery reporting',vendor:'Cisco NX-OS',technology:'vPC',architecture:'spine-leaf',roles:{upper:'Spine',lower:'Leaf'},techPlacement:'upper',upperCount:1,lowerCount:1,devices:[{id:'upper-1',tier:'upper',index:1,hostname:'PLANNED-SPINE',vendor:'Cisco NX-OS'},{id:'lower-1',tier:'lower',index:1,hostname:'PLANNED-LEAF',vendor:'Cisco NX-OS'}],links:[{id:'link1',a:'upper-1',b:'lower-1',enabled:true,upperPort:'Eth1/1',lowerPort:'Eth1',speed:'100G'}],configurations:[{deviceId:'upper-1',text:'hostname PLANNED-SPINE',source:'vPC'}],parameters:[],specialLinks:[],source:{module:'VPC',projectId:'p_report'},inventoryDeviceIds:[],manualVisibleIds:[],sshVisibleIds:[]};
const payload={schema:'network-discovery-inventory-v1',projectId:'p_report',devices:[{id:'nd-seed',hostname:'DISCOVERED-CORE',vendor:'Cisco NX-OS',managementAddresses:['192.0.2.10'],identitySource:'SSH inventory / neighbors',model:'N9K-TEST',serial:'SERIAL-TEST',softwareVersion:'10.4-test',observedAt:'2026-10-06T17:00:00Z'},{id:'nd-neighbor',hostname:'DISCOVERED-LEAF',vendor:'Arista EOS',managementAddresses:['192.0.2.11'],identitySource:'LLDP advertisement',observedAt:'2026-10-06T17:00:00Z'}]};
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));let word;
const dom=new JSDOM(fs.readFileSync('reporting.html','utf8'),{runScripts:'dangerously',url:'https://test.invalid/reporting?view=inventory&discovery=1',virtualConsole:vc,beforeParse(w){for(const f of ['engineering-locale.js','vpc-report.js','engineering-report.js','verification-plan.js','discovery-inventory.js'])w.eval(fs.readFileSync(f,'utf8'));w.sessionStorage.setItem('networkConfigurator.report.current',JSON.stringify(report));w.sessionStorage.setItem('networkConfigurator.discovery.inventoryImport',JSON.stringify(payload));w.fetch=async(url,o)=>{if(url==='/api/reporting/word'){word=JSON.parse(o.body);return {ok:true,blob:async()=>new w.Blob(['word'])};}return {ok:true,json:async()=>({})};};w.alert=x=>{throw Error(x);};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};}});
(async()=>{const w=dom.window,d=w.document;try{
 const state=w.NetworkReportProject.snapshot();assert.equal(state.inventoryDeviceIds.length,2);assert.equal(state.devices.length,4);assert.deepEqual(JSON.parse(JSON.stringify(state.links)),report.links);assert.deepEqual(JSON.parse(JSON.stringify(state.configurations)),report.configurations);assert.ok(d.getElementById('manualRows').innerHTML.includes('DISCOVERED-CORE'));assert.ok(d.getElementById('reportInventoryRows').textContent.includes('DISCOVERED-LEAF'));assert.ok(d.getElementById('reportPreview').textContent.includes('SERIAL-TEST'));assert.equal(w.sessionStorage.getItem('networkConfigurator.discovery.inventoryImport'),null);
 d.getElementById('downloadWord').click();await new Promise(r=>setTimeout(r,30));assert.ok(word);assert.equal(word.inventoryDeviceIds.length,2);assert.ok(word.devices.some(x=>x.serial==='SERIAL-TEST'));assert.ok(!word.inventoryDeviceIds.includes('upper-1'));for(const language of ['en','tr']){const check={...word,language};execFileSync('python',['-c','import sys,json,io;from fastapi.testclient import TestClient;from docx import Document;import app;p=json.load(sys.stdin);r=TestClient(app.app).post("/api/reporting/word",json=p);assert r.status_code==200,r.text;d=Document(io.BytesIO(r.content));text=" | ".join(c.text for t in d.tables for row in t.rows for c in row.cells);assert "SERIAL-TEST" in text,text;assert ("Keşif · komşuluk kaydı" if p["language"]=="tr" else "Discovery · neighbor record") in text,text;print("Word inventory accepted")'],{input:JSON.stringify(check),encoding:'utf8'});}assert.deepEqual(errors,[]);console.log('Discovery import: Manual screen, report preview, current project and Word inventory agree; planned topology/configurations unchanged');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
