const fs=require('fs'),assert=require('assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
let html=fs.readFileSync('web.html','utf8').replace(/\}\)\(\);\s*<\/script>\s*<\/body>/,'window.__audit={snapshot,applyProject,reportingDesign,combineReports};})();</script></body>');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const w=new JSDOM(html,{url:'https://test.invalid/',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){for(const f of ['engineering-locale.js','huawei-istack.js','vpc-report.js','verification-plan.js'])w.eval(fs.readFileSync(f,'utf8'));w.scrollTo=()=>{};w.fetch=async()=>({ok:true,json:async()=>({platforms:{}})});}}).window,d=w.document;
const pause=()=>new Promise(r=>setTimeout(r,40));const change=(id,value)=>{d.getElementById(id).value=value;d.getElementById(id).dispatchEvent(new w.Event('change',{bubbles:true}));};
(async()=>{try{
 d.querySelector('.tech[data-tech="VPC"]').click();await pause();change('platform','Huawei iStack');await pause();
 assert.equal(d.getElementById('moduleTitle').textContent,'Huawei iStack');assert.ok(!d.getElementById('hwHost1'));assert.ok(!d.getElementById('vpcDomain'));assert.match(d.getElementById('output').textContent,/sysname CORE-ISTACK/);
 for(const count of [2,4,8]){change('isLeafCount',String(count));await pause();const report=w.__audit.reportingDesign();assert.equal(report.devices.length,2+count);assert.equal(report.links.length,count*2);assert.equal(report.specialLinks.length,3);assert.equal(report.configurations.length,2+count);assert.equal(report.vendor,'Huawei iStack');assert.equal(report.technology,'Huawei iStack');assert.ok(report.links.every(l=>l.upperPort&&l.lowerPort));assert.ok(report.configurations.every(c=>!/(vpc domain|mlag configuration|dfs-group|stackwise)/.test(c.text)));const guide=w.NetworkReportGuide.build({...report,language:'tr'});assert.match(guide.title,/iStack/);assert.ok(guide.topology.join(' ').includes(String(count)+' leaf'));for(const p of report.parameters)assert.notEqual(w.NetworkLocale.localizeParameter(p,'tr').impact,p.impact);}
 change('isLeafCount','4');change('isOutput','MEMBER2');assert.match(d.getElementById('output').textContent,/stack slot 0 renumber 1/);assert.match(d.getElementById('output').textContent,/port interface XGigabitEthernet0\/0\/28 enable/);assert.ok(!/^reboot|^save$/m.test(d.getElementById('output').textContent));change('isOutput','CORE');assert.match(d.getElementById('output').textContent,/interface GigabitEthernet1\/0\/1/);assert.match(d.getElementById('output').textContent,/mad detect mode direct/);
 change('isId2','0');assert.throws(()=>w.__audit.reportingDesign(),/unique/);change('isId2','1');
 for(const tab of ['verify','trouble','notes','deploy','config']){d.querySelector('.tab[data-tab="'+tab+'"]').click();await pause();assert.ok(!d.getElementById('output').textContent.includes('CONFIGURATOR ERROR'));}
 d.querySelector('.tab[data-tab="verify"]').click();await pause();assert.equal(d.getElementById('verifyPlatform').value,'Huawei iStack');assert.ok([...d.querySelectorAll('#verifyGroups .verify-command-editor')].some(e=>e.value==='display stack'));d.querySelector('.tab[data-tab="notes"]').click();change('designNotesLanguage','tr');assert.match(d.getElementById('output').textContent,/mantıksal kontrol düzlemi/);
 const state=w.__audit.snapshot();d.querySelector('.tech[data-tech="BGP"]').click();await pause();w.__audit.applyProject(state);await pause();assert.equal(d.getElementById('platform').value,'Huawei iStack');assert.equal(d.getElementById('isLeafCount').value,'4');
 const r=w.__audit.reportingDesign();const unified=w.__audit.combineReports([{...r,moduleKey:'VPC',moduleTitle:'Huawei iStack'}]);assert.equal(unified.devices.length,5);assert.equal(unified.configurations.length,5);assert.equal(unified.configurations.find(c=>unified.devices.find(d=>d.id===c.deviceId).hostname==='CORE-ISTACK').text.split('sysname CORE-ISTACK').length-1,1);r.verificationCommands=w.HuaweiIStack.commands();unified.moduleReports[0].verificationCommands=r.verificationCommands;assert.equal(w.VerificationPlan.build(unified).filter(p=>p.command==='display stack').length,1);r.language='en';r.verificationPlan=[];r.devices.forEach(x=>x.vendor='Huawei iStack');const plan=w.VerificationPlan.build(r);assert.ok(plan.some(p=>p.command==='display stack'));assert.ok(!plan.some(p=>p.hostname.startsWith('LEAF')&&/^display (stack|mad)/.test(p.command)));for(const language of ['tr','en']){
 const payload={...r,language,name:'iStack design',parameters:r.parameters.map(p=>w.NetworkLocale.localizeParameter(p,language)),technologyGuide:w.NetworkReportGuide.build({...r,language})};payload.technologyGuide.sources=payload.technologyGuide.sources.map(([title,url])=>({title,url}));
 const result=require('child_process').execFileSync('python',['-c','import sys,json,io;from app import app;from fastapi.testclient import TestClient;from docx import Document;p=json.load(sys.stdin);r=TestClient(app).post("/api/reporting/word",json=p);assert r.status_code==200,r.text;d=Document(io.BytesIO(r.content));t="\\n".join(x.text for x in d.paragraphs);assert "iStack" in t;assert "Cisco vPC" not in t;print("Word passed")'],{input:JSON.stringify(payload),encoding:'utf8'});assert.match(result,/Word passed/);
 }
 assert.deepEqual(errors,[]);
 console.log('Huawei iStack: UI, 2/4/8 leaves, two execution phases, report/TR-EN guide, validation, verification/troubleshooting and Save/Open passed');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
