const fs=require('fs'),assert=require('assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const shell=fs.readFileSync('corporate-shell.js','utf8');
function compareMenu(d){const entries=d.querySelectorAll('[data-nc-compare]');assert.equal(entries.length,1);assert.equal(entries[0].closest('[data-nc-group]').dataset.ncGroup,'projects');assert.equal(entries[0].getAttribute('href'),'/config-compare');assert.equal(entries[0].classList.contains('nc-planned'),false);assert.ok(!d.querySelector('[data-nc-group=operations]').textContent.includes('Configuration Comparison'));}
const options=url=>({url,runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.eval(fs.readFileSync("huawei-istack.js","utf8"));w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};for(const f of ['engineering-locale.js','vpc-report.js','verification-plan.js'])w.eval(fs.readFileSync(f,'utf8'));w.fetch=async()=>({ok:true,json:async()=>({platforms:{}})});}});
(async()=>{
 const main=new JSDOM(fs.readFileSync('web.html','utf8'),options('https://test.invalid/'));const w=main.window,d=w.document;w.eval(shell);
 try{
 compareMenu(d);assert.equal(d.querySelectorAll('.nc-sidebar').length,1);assert.equal(d.querySelectorAll('.nc-nav-group').length,7);assert.equal(d.querySelectorAll('.nc-planned').length,11);assert.ok([...d.querySelectorAll('.nc-planned')].every(x=>x.disabled));assert.equal(d.querySelector('[data-nc-stat="topology"]').textContent,'0');assert.equal(d.querySelectorAll('[data-nc-module]').length,8);assert.equal(d.querySelector('[data-nc-home]').getAttribute('aria-current'),'page');
 for(const key of ['BASIC','BGP','OSPF','STP','VPC','EVPN','SDWAN','QOS']){d.querySelector('[data-nc-module="'+key+'"]').click();await new Promise(r=>setTimeout(r,2));assert.equal(d.getElementById('v3Dashboard').classList.contains('show'),false);assert.equal(d.querySelector('.tech.active').dataset.tech,key);assert.ok(d.querySelector('[data-nc-module="'+key+'"]').classList.contains('nc-module-context'));assert.equal(d.querySelectorAll('[aria-current="page"]').length,1);assert.ok(!d.getElementById('output').textContent.includes('CONFIGURATOR ERROR'));}
 for(const tab of ['config','deploy','verify','trouble','notes']){d.querySelector('[data-nc-tab="'+tab+'"]').click();assert.equal(d.querySelector('.tab.active').dataset.tab,tab);}
 d.querySelector('[data-nc-home]').click();assert.equal(d.getElementById('v3Dashboard').classList.contains('show'),true);
 d.querySelector('[data-nc-start]').click();assert.equal(d.querySelector('.nc-project-flow').hidden,false);assert.equal(d.querySelector('.nc-project-flow [aria-current=step]').dataset.ncFlowStep,'network');assert.equal(d.querySelector('.nc-project-flow').querySelectorAll('[data-nc-flow-step]').length,4);
 d.querySelector('[data-nc-module="BGP"]').click();await new Promise(r=>setTimeout(r,10));const flow=d.querySelectorAll('.nc-project-flow')[1];assert.equal(d.getElementById('v3WorkspaceReportTopBtn'),null);assert.equal(d.getElementById('v3WorkspaceReportBtn'),null);assert.equal(flow.hidden,false);d.getElementById('bgpCustomerAs').value='65123';flow.querySelector('.nc-flow-next').click();assert.equal(d.getElementById('combineModal').hidden,false);d.getElementById('combineCancel').click();assert.equal(d.getElementById('bgpCustomerAs').value,'65123','workflow must not reset design inputs');
 d.querySelector('.nc-menu-toggle').click();assert.equal(d.body.classList.contains('nc-menu-collapsed'),true);d.querySelector('.nc-menu-toggle').click();assert.equal(d.body.classList.contains('nc-menu-collapsed'),false);
 Object.defineProperty(w,'innerWidth',{value:600,writable:true});d.querySelector('.nc-menu-toggle').click();assert.equal(d.body.classList.contains('nc-menu-open'),true);d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(d.body.classList.contains('nc-menu-open'),false);
 }finally{w.close();}
 const report=new JSDOM(fs.readFileSync('reporting.html','utf8'),options('https://test.invalid/reporting'));report.window.eval(shell);
 try{const d=report.window.document;compareMenu(d);for(const view of ['inventory','design','lifecycle','upgrade']){d.querySelector('[data-nc-view="'+view+'"]').click();assert.equal(d.querySelector('[data-view="'+view+'"]').getAttribute('aria-selected'),'true');assert.equal(d.querySelector('[data-nc-view="'+view+'"]').getAttribute('aria-current'),'page');assert.equal(d.querySelector('.nc-project-flow [aria-current=step]').dataset.ncFlowStep,view==='lifecycle'?'upgrade':view);}assert.equal(d.querySelector('[data-nc-module="BGP"]').getAttribute('href'),'/?workspace=BGP');d.querySelector('[data-nc-collection="automatic"]').click();assert.equal(d.getElementById('inventoryMode').value,'automatic');assert.equal(d.querySelector('[data-view="inventory"]').getAttribute('aria-selected'),'true');d.querySelector('.nc-flow-next').click();assert.equal(d.querySelector('[data-view="design"]').getAttribute('aria-selected'),'true');assert.equal(d.querySelector('[data-nc-flow-step="network"]').getAttribute('href'),'/?resume=1');}finally{report.window.close();}
 const deep=new JSDOM(fs.readFileSync('web.html','utf8'),options('https://test.invalid/?workspace=BGP'));deep.window.eval(shell);assert.equal(deep.window.document.querySelector('.tech.active').dataset.tech,'BGP');deep.window.close();
 const resumeOptions=options('https://test.invalid/?resume=1'),baseParse=resumeOptions.beforeParse;resumeOptions.beforeParse=w=>{baseParse(w);w.sessionStorage.setItem('networkConfigurator.workflow.design',JSON.stringify({schema:'network-configurator-v3',project:{name:'Retained project'},workspace:{technology:'BGP',platform:'Cisco NX-OS'},fields:{bgpCustomerAs:'65123',bgpCe1Name:'RETAINED-CE',verifyPassword:'SYNTHETIC_SECRET'}}));};const resumed=new JSDOM(fs.readFileSync('web.html','utf8'),resumeOptions);resumed.window.eval(shell);await new Promise(r=>setTimeout(r,80));assert.equal(resumed.window.document.getElementById('bgpCustomerAs').value,'65123');assert.equal(resumed.window.document.getElementById('v3ProjectName').value,'Retained project');assert.equal(resumed.window.document.getElementById('verifyPassword').value,'');assert.equal(resumed.window.document.getElementById('v3Dashboard').classList.contains('show'),false);resumed.window.close();
 assert.deepEqual(errors,[]);console.log('Corporate navigation: eight modules, reporting views, mobile toggle, dashboard and deep links passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
